<?php
$html = array(
"http://forlap.dikti.go.id/prodi/detail/NTRDRDUzQjItMDg1MC00RkVFLTk2QzUtM0E2QzdEODI4MzJC/0",
"http://forlap.dikti.go.id/prodi/detail/NEFENjlCNjQtRUZFNC00MUY1LTkzOUUtM0JDODA5OTBFNUM4/0",
"http://forlap.dikti.go.id/prodi/detail/RUFEMzgyMzktMDNDMi00NzczLUJDMjItNEY1RjI1NTc5Njc2/0",
"http://forlap.dikti.go.id/prodi/detail/QjE2M0I0QjctOEMwRC00MjA5LThBNEQtREQ0QUNFRDc2Q0M3/0",
"http://forlap.dikti.go.id/prodi/detail/NzA3QzBCMUUtMjM4QS00NzM2LThGNkUtNkRBQzZBNEQ5RDM1/0",
"http://forlap.dikti.go.id/prodi/detail/ODQ3QzAwREMtRjVENS00QTgzLTlGODItN0FGOEY0ODFEQUI0/0",
"http://forlap.dikti.go.id/prodi/detail/QjlDMjdGNjgtREQzNi00REY2LTkwQkUtMzFBMzU4NTA5NDk1/0",
"http://forlap.dikti.go.id/prodi/detail/MkIzNzhDNkMtQ0IxRS00Mjg4LUEzMUUtMjEzRTQ4OTBERENE/0",
"http://forlap.dikti.go.id/prodi/detail/NzE0OTY2MkEtQ0ZBNy00QkZDLThEMDAtOUY4NjlDMkEyMDVC/0",
"http://forlap.dikti.go.id/prodi/detail/QzI2MDI2MkUtMkY5Ny00RURGLUE2MUItMDdDMUY3QTFFNDdF/0",
"http://forlap.dikti.go.id/prodi/detail/RDBCQzVCQUQtRjE4NC00NUQ4LThDODAtREYwODUxODJGQUNB/0",
"http://forlap.dikti.go.id/prodi/detail/NjE4MTMwM0YtQTk3QS00MUZGLUFEOEMtRjRCRUUxMTE3MjdB/0",
"http://forlap.dikti.go.id/prodi/detail/QTc2RUJBNzQtOEQwOS00NzE1LTk0MjktNzAxMzRDQzQ5QUFC/0",
"http://forlap.dikti.go.id/prodi/detail/QTEzMkY3REMtQjlFQi00QjM1LUI1MDgtNEEyNjZBODkyRUVG/0",
"http://forlap.dikti.go.id/prodi/detail/MTE4M0E4NTktNzc4QS00MUQyLUEzNUMtQTg5MkQzOTkyMDM2/0",
"http://forlap.dikti.go.id/prodi/detail/NDk2MEVERjktRUQ0Mi00MTBGLUJDQjEtQkE2OTRFNEQ3MEJC/0",
"http://forlap.dikti.go.id/prodi/detail/NTdFMEQ5N0ItRTM4NC00ODg2LThGRTgtOTYxQjE4QzRCNTYz/0",
"http://forlap.dikti.go.id/prodi/detail/MzJCREY4MUItQTlGNS00RUIxLThFNjItMEEyMjZBOURCODkx/0",
"http://forlap.dikti.go.id/prodi/detail/Q0I0QkNFMTAtRURBOC00M0EzLTlCNDgtNjVFQTEwRDNEMTU4/0",
"http://forlap.dikti.go.id/prodi/detail/N0VERTc3M0MtQ0Y3RS00OERGLTkwQTgtNjEzOEZDRUNEMzI5/0",
"http://forlap.dikti.go.id/prodi/detail/MThFMjA4QTktMDg4My00NTI1LUI2NkMtRUU4Q0Q3NjAxNzYy/0",
"http://forlap.dikti.go.id/prodi/detail/RDQwNEQ4RkItMTcyRi00RTAyLTkzRTAtOUE4RDZGRjE5QjY3/0",
"http://forlap.dikti.go.id/prodi/detail/QTFDMEZCRDItQzA5OS00RERELUExRkItMkQ5NjgzMTkwNzk0/0",
"http://forlap.dikti.go.id/prodi/detail/NEQzRjVGMTEtNDlDQS00RTUwLTlCMEMtOEY0MTA3OUJCQzNG/0",
"http://forlap.dikti.go.id/prodi/detail/QzE3Q0M1RjAtNzBDQy00NkIxLTgwMjctMEUyMDc1OTA5Q0E3/0",
"http://forlap.dikti.go.id/prodi/detail/QTI2RDkzRTAtNzAyMS00QjA3LTlCQjEtQUMxRDNBMTZBRjlF/0",
"http://forlap.dikti.go.id/prodi/detail/NTIxQkVDNDAtQkJFMS00RUFELTlDM0EtOTBFQjBBRTk3QzU4/0",
"http://forlap.dikti.go.id/prodi/detail/QUZDOEZCOTUtMDhCOC00REE0LTlERjgtQkUzMEQxOUVGQjc0/0",
"http://forlap.dikti.go.id/prodi/detail/MTYzNUYwQzAtNjBBMy00RTY4LUJGRkMtQkI0NDVCMUM5Qzc0/0",
"http://forlap.dikti.go.id/prodi/detail/REU5QUYzMjQtOUY2My00RjE2LUEzMTMtODUyRTZFMzFENTRG/0",
"http://forlap.dikti.go.id/prodi/detail/ODFCQ0MyMkYtRjY3Ri00NTRDLTk4NTMtODYzQ0U1QjMwMUZE/0",
"http://forlap.dikti.go.id/prodi/detail/QkRFRUVEQzYtQjFCQy00MjYwLTkzMUMtODMwNjI4NTZBQ0E0/0",
"http://forlap.dikti.go.id/prodi/detail/RDhEMEZFRkYtRTYzNy00NkQ0LUEzNkYtQkFDMzkzQUYyNEIw/0",
"http://forlap.dikti.go.id/prodi/detail/NTZGMjE1OUEtNTNBNC00OEE4LThFODEtRjYzOTVFNEM0MEIx/0",
"http://forlap.dikti.go.id/prodi/detail/OTk2QUIzMTMtQjNBMS00NjE2LTk3RjAtRjZFQzI0ODhBN0E0/0",
"http://forlap.dikti.go.id/prodi/detail/NEUxNDExRDEtOUU5NS00REZGLUE2OTMtM0VENDQ1NDgyNEI5/0",
"http://forlap.dikti.go.id/prodi/detail/NjYyNDhGRTEtOTI3RS00NUFDLTkzRjItMTNGRTU3QjM3N0M0/0",
"http://forlap.dikti.go.id/prodi/detail/MjIwN0YzOEMtNjZEOC00Rjc5LThEQUYtNDNFNjIyQUM4QzFD/0",
"http://forlap.dikti.go.id/prodi/detail/QTc0NUVBNzctQTY4Mi00MEYzLTlBOEItRDE2RkQ3ODJCREE5/0",
"http://forlap.dikti.go.id/prodi/detail/MzBFQzhCNzEtRTJBNC00MTVBLUJGOEUtNTBDMTRFOEEzRTZF/0",
"http://forlap.dikti.go.id/prodi/detail/NkI5NTczRUItMzc3OS00MTkzLUExRTMtQTkyQThDNEJGMDBE/0",
"http://forlap.dikti.go.id/prodi/detail/RTQ3NzEwMTMtQTZGQi00QkZELTkzMDEtM0M2QUFCODY1RUEx/0",
"http://forlap.dikti.go.id/prodi/detail/RjVBMzFBRDAtQ0U4NS00OTM4LUI3NUMtNEU5MDk1OEUyRDUw/0",
"http://forlap.dikti.go.id/prodi/detail/MDcwNDM5MUYtRDA0MC00QTdGLUI0QkMtMTA5NDRFNDRFM0JC/0",
"http://forlap.dikti.go.id/prodi/detail/ODA5ODk3QUYtN0ZEOC00RDFELTlBNUUtQUExQjcwMzZFNjQ4/0",
"http://forlap.dikti.go.id/prodi/detail/NjMyNDA5REQtRUFGOC00MDNBLUE2NzUtNjU3NzIzMkEzRDQw/0",
"http://forlap.dikti.go.id/prodi/detail/MjJGNEM5OTYtMzlENy00NkFDLTkyQzItREMxRUFGRkFCRDk0/0",
"http://forlap.dikti.go.id/prodi/detail/MkE5MzlDQ0QtOTNFOC00QjIwLUIzQzMtMDNGRkU1QjU1MjFF/0",
"http://forlap.dikti.go.id/prodi/detail/RTBGNDZEMDYtQzU4MC00RjcwLTg0REUtNzk5MjFCMTQzNDky/0",
"http://forlap.dikti.go.id/prodi/detail/MjczNDVCMDUtN0VCNi00MjRBLTgxMzYtN0NEQ0Y0RjMwMDg5/0",
"http://forlap.dikti.go.id/prodi/detail/QjAxMUM5QjQtRTk0QS00NjI5LTk2QkYtNjMyQTlCRkM5RkEx/0",
"http://forlap.dikti.go.id/prodi/detail/MzIxRkEwNjItREFEMy00NTUyLUFGQUQtNTVDRjlGMUQyMjJB/0",
"http://forlap.dikti.go.id/prodi/detail/MkUwRjk4NTItRUM1Ri00QUY4LThCMjctNDY1MTVCNzZGMjQy/0",
"http://forlap.dikti.go.id/prodi/detail/RjQyMTE5NEYtM0M5MC00NzlELTlBRjktNDZEQjVEM0MxNkIw/0",
"http://forlap.dikti.go.id/prodi/detail/RTFEQzdBQUUtOTYzMS00NTgxLTgzQzMtRDY5NEE5RTA2RjEz/0",
"http://forlap.dikti.go.id/prodi/detail/MzBCODBDNUUtN0IxRC00RUFGLTk3NjItQjk2MDZFQ0YwMkE1/0",
"http://forlap.dikti.go.id/prodi/detail/QTY2RkRENjQtRDA4Mi00NTQ5LUFERDYtREJGQkI1MkZGNDM2/0",
"http://forlap.dikti.go.id/prodi/detail/ODgxNDgyOUItOTRCNi00REUzLUIyQkItOEZCRjBFMEI2Mjc3/0",
"http://forlap.dikti.go.id/prodi/detail/MzZEQjA0QkUtRjdCNS00MEI2LThBMzEtQURDNTk0ODAxOUVE/0",
"http://forlap.dikti.go.id/prodi/detail/RTg2NUY5MjQtM0YwNy00RThBLUEwQjctNTNFNUIyRjc0OUQ2/0",
"http://forlap.dikti.go.id/prodi/detail/QTMxMDI3NDMtMTczMS00NTAxLTgyMDctNUY0NDMyNDFBQThE/0",
"http://forlap.dikti.go.id/prodi/detail/QzQ1RDE1MDctQjNDRS00REZDLTkxRjAtOUYzMjRBQTg3MTNB/0",
"http://forlap.dikti.go.id/prodi/detail/RjVGM0VGQkUtMEE2RS00NkFBLTgzQzEtRTgwRTQwNTgzQ0FB/0",
"http://forlap.dikti.go.id/prodi/detail/ODJFMTBERDgtM0U5Ni00MDZDLUFDQjMtQTQyNjcxMjk3NjM4/0",
"http://forlap.dikti.go.id/prodi/detail/MUJDQjVFRDktQzlDRC00OEVCLTg4NjYtN0QxNzQyRDI5ODQ4/0",
"http://forlap.dikti.go.id/prodi/detail/NTY2MkQ2NTEtMTFFQi00Mzc5LUI0NDMtMzlENTZDRDg0MDhB/0",
"http://forlap.dikti.go.id/prodi/detail/NjA3MzM3OTctMzBGRS00NUE0LUJEQTEtNUVBQzg3NjRGRTUx/0",
"http://forlap.dikti.go.id/prodi/detail/MjkxNjAzQzItQjY5MS00NzUyLTk2MDAtRjNEQ0FBRkQwRDQy/0",
"http://forlap.dikti.go.id/prodi/detail/REU4Q0QwMDEtQjlBNC00RjlCLUFBOTUtMEE0QkRBMkY1MUI4/0",
"http://forlap.dikti.go.id/prodi/detail/REE2RTc4M0QtRTU3Mi00RkIzLUJCOUMtNjMwNzAxN0ExOEJE/0",
"http://forlap.dikti.go.id/prodi/detail/NEEzOEZBNzctMzI1My00N0RDLTk5MzAtMUVFNjhGQzVFM0Ey/0",
"http://forlap.dikti.go.id/prodi/detail/OTM2QzkzRkMtNUFBNS00QUQ2LUFCQ0EtOUU2MUJGQkQwREJF/0",
"http://forlap.dikti.go.id/prodi/detail/RjgyOEYyRTMtNEU1MS00NzRDLTgwOUUtMEREMDBFRTU1Qjg1/0",
"http://forlap.dikti.go.id/prodi/detail/NzBCRkM0OTUtN0JENC00REUzLTlGRDYtNEFGNzIxQkU1RTEz/0",
"http://forlap.dikti.go.id/prodi/detail/RDY4QjYwQzQtNjJBMS00QjM5LTlEOEMtMUQwMjgyOEU3NjY5/0",
"http://forlap.dikti.go.id/prodi/detail/NUI4NDcwRjYtOEYxMy00RUQ2LUJBOUItNTIwRUJFRDQwRkJG/0",
"http://forlap.dikti.go.id/prodi/detail/N0E5MTg0OTUtOTRCOC00OTc0LTk4MTYtMTc4MDhGQTk5QTg1/0",
"http://forlap.dikti.go.id/prodi/detail/QTcxODY1RDgtNzI0Ny00NEI0LTk5MTAtNTY4RkMwMkY5MTgz/0",
"http://forlap.dikti.go.id/prodi/detail/REUxQ0NEMTYtODM2Mi00QTMyLUI1NDQtMDg2QzM5MzZGOTBB/0",
"http://forlap.dikti.go.id/prodi/detail/NTZDQkQzOEYtRkZCOS00RjJBLUJCMTMtRkRGQTNDRTQ3MTIw/0",
"http://forlap.dikti.go.id/prodi/detail/NDgxMDY5QUMtMTM5My00RjdCLTgxQjEtNjI3MzM3NjRDQkUy/0",
"http://forlap.dikti.go.id/prodi/detail/MkVFMDkxM0UtQUI2MS00MEE5LUFEMDMtRUYxMjI5MUE5QUJF/0",
"http://forlap.dikti.go.id/prodi/detail/OUI0NTQzOEMtM0U0Ri00QTEzLTgxQzAtNjM1NTBDRURBQ0Y4/0",
"http://forlap.dikti.go.id/prodi/detail/MjBCRkM3MzMtNzg5NS00RThFLThCMEUtN0Q5OEM1M0UwODBG/0",
"http://forlap.dikti.go.id/prodi/detail/RjlBNjMwQ0YtNzQ2RC00QzZBLUIxNzktOURCNDQxOEE3QUYy/0",
"http://forlap.dikti.go.id/prodi/detail/Qzg5NDBBRjctMUE3RC00M0Y1LUJDMjctODFDNjlCNDA1N0Mz/0",
"http://forlap.dikti.go.id/prodi/detail/MTMwMzEyQzAtNjJFMi00MTg4LUJCODYtOUFENjFBQkMyMTBF/0",
"http://forlap.dikti.go.id/prodi/detail/QkJGOENGMzctRjRGNi00NzI1LTlGNjMtMTcyNkNGQTE3QkIy/0",
"http://forlap.dikti.go.id/prodi/detail/OTAzRjMwNDItNTBBQy00MDAzLTkzQTUtMjEwRkJENTZENTc0/0",
"http://forlap.dikti.go.id/prodi/detail/RkEzRjgyREUtRjMxOC00NUZCLUEzOTUtQUVGQUQ3MUVCODk0/0",
"http://forlap.dikti.go.id/prodi/detail/NEM3QTFBMDktRUVEMC00NzRBLUI4MUItRDE2ODhEMzUwNDdF/0",
"http://forlap.dikti.go.id/prodi/detail/RkNCNDRBMEYtNkNBMy00NDQ3LUExRjEtQTUzMkRDQUEyMzVE/0",
"http://forlap.dikti.go.id/prodi/detail/RjNCMjFGRkEtODY0Ni00RjZBLTkyNEUtNkRGQTg5RkRGRjJD/0",
"http://forlap.dikti.go.id/prodi/detail/RjdBMTQwNkUtRjk4NC00NEUyLTlGQkMtOTNFQkY5NDZCRUUw/0",
"http://forlap.dikti.go.id/prodi/detail/NUM4NDAzRDAtM0I1MS00NTA0LUIwQzktNUE4QTBEQzIzRjg2/0",
"http://forlap.dikti.go.id/prodi/detail/MjJFMTExNUUtMzRFQi00QTUxLTkzNEMtMEI0RTQwQUE2NDU3/0",
"http://forlap.dikti.go.id/prodi/detail/RTBCNTg2NUItOTA5MC00RUVGLUI3MTAtMjg4NEI3NUFDRTRD/0",
"http://forlap.dikti.go.id/prodi/detail/NEU0MjQ5NkQtMzQ2NC00N0RCLUFFOEYtNEEwRjI5QUVFMjhG/0",
"http://forlap.dikti.go.id/prodi/detail/MTYzQ0VBRDUtNkVDNi00RDhCLTlDRUQtNDg1MDI0MEY4RjZG/0",
"http://forlap.dikti.go.id/prodi/detail/OEM3ODY4NzEtQzFBMi00MTc2LTlGNTMtQUEwNTdCNTAxMEVD/0",
"http://forlap.dikti.go.id/prodi/detail/QjIyRTAxMUMtRTQzMC00N0M5LTg4MDQtMjNENzk3NzlBODYy/0",
"http://forlap.dikti.go.id/prodi/detail/OEZEMEYyQzgtQzFEOC00N0Q4LUI0QTAtMzM2ODA0QUUzRkE0/0",
"http://forlap.dikti.go.id/prodi/detail/M0E2MDYwNDAtODYxMC00QTQ3LUFGRUUtRkNCNThGNkMwODkw/0",
"http://forlap.dikti.go.id/prodi/detail/NjQxOUNFMkItODQwMy00QjNBLUE4ODMtRjJENDU4QTM4QzZF/0",
"http://forlap.dikti.go.id/prodi/detail/MTRCRTA0MjItMzVFNy00Nzc3LUJDMEItREI5NUQwQUFEMjMy/0",
"http://forlap.dikti.go.id/prodi/detail/RkU1RkYyQzYtQTgzNS00Nzc3LUE1OTQtRkQ3NDY1RjEzMzg5/0",
"http://forlap.dikti.go.id/prodi/detail/REVCRUQwQ0YtOUY5OS00OTg5LTlFRkMtMDE4NTZFRUM2OEJE/0",
"http://forlap.dikti.go.id/prodi/detail/MjMzRjlENjAtRjk0RC00RjgwLUJFQ0EtNzkxQTE3MUJCQUFE/0",
"http://forlap.dikti.go.id/prodi/detail/MjI4NDcyNTQtMDZBNC00RjVDLUFDMjAtQUNDNDlENEI4OEZF/0",
"http://forlap.dikti.go.id/prodi/detail/MDIwODRBOUQtMTYxNy00NTdELUJFOEEtOTY2MENFNzM3QzRD/0",
"http://forlap.dikti.go.id/prodi/detail/QkEyODg1QkUtREMwQy00MDM3LUI4NjQtNzM2REVDMjg4M0U1/0",
"http://forlap.dikti.go.id/prodi/detail/MDY0MjcwRTctNzZGMC00MzE5LUI1MUItOTE5MDk5REYyREVG/0",
"http://forlap.dikti.go.id/prodi/detail/REUxODQxNzktNDZBQi00RjZDLTg2OEYtN0I5OUM5NkREN0I5/0",
"http://forlap.dikti.go.id/prodi/detail/MkMxNTU5MjAtQ0NBOS00NEM4LUJFNDItNzgzNzVCMjI4REM3/0",
"http://forlap.dikti.go.id/prodi/detail/MTE0NTcyMzgtNjkzMS00MTAxLTlBODEtMDY4NjhCNzdFNEZF/0",
"http://forlap.dikti.go.id/prodi/detail/MzNGNjFEQTUtNTE5Ny00ODc5LUJBMDgtMTJEMDRENkEzRDE0/0",
"http://forlap.dikti.go.id/prodi/detail/MTY1QzAzMjAtMkYxMS00MEVDLTlDMjgtMDkwRDU3MjQyQTAz/0",
"http://forlap.dikti.go.id/prodi/detail/OEIxMkI4RDgtODE4Ri00REI1LUIzNzYtQTE2QUJCRUE3MkVD/0",
"http://forlap.dikti.go.id/prodi/detail/MzBDMTg5MzQtRDgxNy00MTdBLUI4NUItMzg1RkRBNDg5RDRC/0",
"http://forlap.dikti.go.id/prodi/detail/QkJGQUE3MjAtNTBEOS00MkI1LThFNzYtMkU4M0FFQTg5RDND/0",
"http://forlap.dikti.go.id/prodi/detail/QzNEQkRENzMtOTNBNy00M0VGLUFGQkItMjgxNUUzNTIzMDk3/0",
"http://forlap.dikti.go.id/prodi/detail/MjI1RkE2QUUtRDkzRi00MDBCLTgwQjctNDEwNkREMjNENzg5/0",
"http://forlap.dikti.go.id/prodi/detail/NDFBRjVENEItM0RGNy00QThBLTk2OTctOUM3NDNDODc3RDJE/0",
"http://forlap.dikti.go.id/prodi/detail/NDVBOTVGRkItRTBGMS00MUFBLTk1QjktQzA2ODY5RjREODVD/0",
"http://forlap.dikti.go.id/prodi/detail/Qzc5MUU2N0YtMjhDOS00MzYxLUI4NjItRjlGQ0FDOEVDMjc4/0",
"http://forlap.dikti.go.id/prodi/detail/NDJBNTFDMTAtOTE4Qy00Q0NCLTk5RTItM0RBODBBRjU4Q0M2/0",
"http://forlap.dikti.go.id/prodi/detail/RkVERkEwQkQtRUFFQS00MkMzLThFRDMtOTUyQjJCOTNENDdE/0",
"http://forlap.dikti.go.id/prodi/detail/OEU4NzdFREYtNzc2Ny00MDZCLUIxNUUtMTA2NDJDMEFBMTRB/0",
"http://forlap.dikti.go.id/prodi/detail/QTZBNUIwQUQtMEQzMC00QzVFLUE2OUQtNEM5NkQ3NUYwNjEx/0",
"http://forlap.dikti.go.id/prodi/detail/RjU4ODQ5RUEtQTcxQS00NjU3LTkyOUMtQUYwQUNFQzk2MzE4/0",
"http://forlap.dikti.go.id/prodi/detail/RkYyQkMxNUMtNTMwOS00OTA1LTgzMDAtMzQ0QjIxMTI0ODY4/0",
"http://forlap.dikti.go.id/prodi/detail/RTlFNDZBNjYtM0M4MC00NzE5LUI5RjEtQTg3RDU4QkQ2NjBC/0",
"http://forlap.dikti.go.id/prodi/detail/MjMwMTc5RUEtRkQ2Mi00NUUzLThCQjQtNUI1QjZEMTE4MEMw/0",
"http://forlap.dikti.go.id/prodi/detail/QTI1NkI1RjEtODNGOC00M0VCLTg5MTEtQTQ4RjYwNEZGMDcx/0",
"http://forlap.dikti.go.id/prodi/detail/REVBMkEwMkMtMzY5My00QkJGLUI5NEEtRDc5MzE5RkE4MDdG/0",
"http://forlap.dikti.go.id/prodi/detail/NUQxQzM1MjEtMjU5NS00RjQ4LTkwMzYtNTFBQjQxRUVDREE5/0",
"http://forlap.dikti.go.id/prodi/detail/MTAyRTQ3QTYtRTY5My00NTA3LUI3QkEtQjA1RjZDNDFGNEIz/0",
"http://forlap.dikti.go.id/prodi/detail/QkZDNjVDODItOTk0MS00OEFDLTlDMDctRDlGQTlCMUZCOTkx/0",
"http://forlap.dikti.go.id/prodi/detail/RDFEMkQ5NDYtNkU0NC00OTNFLUI5M0MtMDU0MEFGNUMyREY3/0",
"http://forlap.dikti.go.id/prodi/detail/NkJGNzlEQ0MtQ0VDNC00MEIwLThEQkYtNUI3MURFOUY4NTJB/0",
"http://forlap.dikti.go.id/prodi/detail/RjU0RTczRkMtMTI4RC00QzkyLUI4NTItODFDOTkxQ0U0MUUx/0",
"http://forlap.dikti.go.id/prodi/detail/QkQ5MDVGRjQtNDFEOS00RkVBLTlGNzAtMDhCQUMyMkM4NjRC/0",
"http://forlap.dikti.go.id/prodi/detail/OTAxQkFCRkMtQkM5Ri00Q0U5LUFBNDAtRTc0QzNGOUI5QjQ1/0",
"http://forlap.dikti.go.id/prodi/detail/MDk1OTQxNEYtQzdDMC00N0Q2LUIyMTEtRDVCODg5RDZFNjgx/0",
"http://forlap.dikti.go.id/prodi/detail/RDJBNEIyMUEtNTJDQy00NUMxLTk3QzUtMjY4QkYxNzdGMDU0/0",
"http://forlap.dikti.go.id/prodi/detail/NEJCRERGREEtNUY2Qi00NjU5LUFFODMtODA3NUY0QTc4MEQ5/0",
"http://forlap.dikti.go.id/prodi/detail/QkQ2REUxRjEtMTcwMi00NEFCLUI2QUYtQTY1OUYxMTNENUMx/0",
"http://forlap.dikti.go.id/prodi/detail/OEIyMDA0QTMtN0IzQS00QkU2LThFQTQtQ0JCQzBCMjdEQTg1/0",
"http://forlap.dikti.go.id/prodi/detail/RjdGRTM4OTMtRTcxOS00ODc1LUFERDgtQzczODE0RTA4QTEx/0",
"http://forlap.dikti.go.id/prodi/detail/MzQzNEEzRjgtMEMzNS00MEFDLUJFQjctMTY1NkZFMjA5RTRE/0",
"http://forlap.dikti.go.id/prodi/detail/NTVGRjc2MTgtQTEwNC00RTE3LTlBQzAtQjZGNkUxOEUzOUMw/0",
"http://forlap.dikti.go.id/prodi/detail/MkVBRkQwNkMtQTE1My00MDg5LUE2QjgtOThFRDA2RDRCM0NE/0",
"http://forlap.dikti.go.id/prodi/detail/MkE2NEE1MUUtMTYwMC00M0UzLTgwQjAtM0JDMjVGMDlBRUJE/0",
"http://forlap.dikti.go.id/prodi/detail/MTdBRkYxMjEtRkQ0RC00OTM5LThENzctRjFCQkFFQjIxNkZB/0",
"http://forlap.dikti.go.id/prodi/detail/OTE4MTAyNjktMjg4My00NTY1LTkxMzYtOUYxMzE2REMyRjM1/0",
"http://forlap.dikti.go.id/prodi/detail/ODEwNUY4REItMjRBRi00RjI2LUFERDktQThBM0FCMDRCMDcz/0",
"http://forlap.dikti.go.id/prodi/detail/OTA0NDk5MDAtRjQ4OS00OTdDLUExMzgtRDE3OUJEREYyNkFG/0",
"http://forlap.dikti.go.id/prodi/detail/OTdFRTEyMkUtNjA0MS00NkI4LUEwMDUtMDI5M0JENTJCMzFB/0",
"http://forlap.dikti.go.id/prodi/detail/MEYwOTBFMTQtMDExNS00OTk5LUE3QUQtMjU1REZEQjc3NjIz/0",
"http://forlap.dikti.go.id/prodi/detail/NTIwRkFFN0ItNTA4OS00RDdGLTg5ODMtRkEwMEEyMjZCOTEw/0",
"http://forlap.dikti.go.id/prodi/detail/NTU3Njc5MjktOTFGRi00QjA4LThGOTQtNUE0Nzc0Mzg4NDJG/0",
"http://forlap.dikti.go.id/prodi/detail/RTM1Nzk4OEUtNDlGNi00RjdCLUI3NDUtOEU5RjlFOEEyRjQ5/0",
"http://forlap.dikti.go.id/prodi/detail/OUVGNThCQjctNzNBMC00NDAzLUE1MEYtMjhGNTIxRjU1OERE/0",
"http://forlap.dikti.go.id/prodi/detail/RTkzNTNEMzEtNUE2OS00NkRDLThFNTQtQzFGMjNFMDdDMUJC/0",
"http://forlap.dikti.go.id/prodi/detail/NkNCNUM4NzYtMjk5Qi00QUM0LUFDRTMtRjkxM0JGQUMzMUU2/0",
"http://forlap.dikti.go.id/prodi/detail/QTE0MkRDQTQtOEIwMy00M0M0LUI4RDItQzIyRjk2QTYwQjMw/0",
"http://forlap.dikti.go.id/prodi/detail/OTk0OEQ3QUQtRjMxNy00QjA0LUIyRkQtREY0OEMxRkQ5QURG/0",
"http://forlap.dikti.go.id/prodi/detail/NjE3QUEwRjUtN0NGOS00RURGLTg0QzEtMjY1MEQ2QUVBNjBG/0",
"http://forlap.dikti.go.id/prodi/detail/MDhCODM5MjMtRTMzMC00REM3LUFGODMtNTE4MThFQzQzQkRC/0",
"http://forlap.dikti.go.id/prodi/detail/RjdERjdBREQtMTlBMy00NEI5LUEyQUYtOTZCRDJCRTRDNUY1/0",
"http://forlap.dikti.go.id/prodi/detail/MUY5NTYzRjktMjE3OS00QkI2LTkwNEUtODlEMzU1RDg4RTc2/0",
"http://forlap.dikti.go.id/prodi/detail/RTYwNDMzQzQtMjRERC00REZCLUE2QzgtNjdENjZENTBBRDhB/0",
"http://forlap.dikti.go.id/prodi/detail/RTgyQ0NDRTEtRkJDNS00OTM5LUI5OTgtQUQ4N0M0QTEyRThG/0",
"http://forlap.dikti.go.id/prodi/detail/MEUzRkU3NDUtNTVBNi00NTUzLUI5QzItRjA3N0FEOENFQzhF/0",
"http://forlap.dikti.go.id/prodi/detail/ODJFQUIyOTktNzc5RS00ODBFLTg1RTYtODUxREI5MDI4NTdG/0",
"http://forlap.dikti.go.id/prodi/detail/NDZFRUJEMDgtQkI0My00NDE2LTg4NTEtNTU2OTkzNUU4MEY2/0",
"http://forlap.dikti.go.id/prodi/detail/RTgxMDlGRDYtMjc4Qy00MEY1LUIxMjEtOTU3MjlGNjQ3NUFD/0",
"http://forlap.dikti.go.id/prodi/detail/QjMyRTIzRTEtRENGQy00QjIyLTlCOTAtOEYxOTgzRERCREFC/0",
"http://forlap.dikti.go.id/prodi/detail/NkQwNUY5N0YtRkI2Ri00MUEzLUFFQkItMURDN0I2Q0E4NUM4/0",
"http://forlap.dikti.go.id/prodi/detail/RUQ4NzQ4RTQtOTQyNC00OTIxLUI0MDEtMEY5Mzg5RTIzRDBB/0",
"http://forlap.dikti.go.id/prodi/detail/MThDRDQwNzYtMUQ5Ni00NDVELUJCNzctQTkzREY2MzQ0MkJF/0",
"http://forlap.dikti.go.id/prodi/detail/NkY2RjRDM0YtQzFBNC00ODA3LTk0MTQtRDJFQjUzRjNEQTAy/0",
"http://forlap.dikti.go.id/prodi/detail/NzgwREE3QzMtRTVBRi00MEE1LTlFOEQtRjUxQUVCQTY1Q0NC/0",
"http://forlap.dikti.go.id/prodi/detail/NTYzQTBDMDItMzExNy00QTMwLTg1RkItRkY5REQzQjhENTg4/0",
"http://forlap.dikti.go.id/prodi/detail/QUFDQTdBRjAtNjJCQS00NDBFLUE2REQtRjA2NjFGMzA3MEE5/0",
"http://forlap.dikti.go.id/prodi/detail/QkI1REEzNDktODkzMy00MTY4LUJBMEEtRERGMkFBM0M0MUE1/0",
"http://forlap.dikti.go.id/prodi/detail/NzkxOTdEOUItMUJGNC00QjlGLUJEMTAtQjExNjI3QjFFN0Qw/0",
"http://forlap.dikti.go.id/prodi/detail/NkE2Q0ZFQjEtMzBENS00MjZELUIyQ0YtQkNGMTNGRTdBRTg5/0",
"http://forlap.dikti.go.id/prodi/detail/QjAzRTZCOUMtOTkyMy00MURBLThEMEYtN0EyNkI1REY0M0Y0/0",
"http://forlap.dikti.go.id/prodi/detail/QjZDMTIzN0YtOTY4My00QTg0LUI4MjQtMjEzQjAzNUI4MEJC/0",
"http://forlap.dikti.go.id/prodi/detail/NjEzMDkwMDktRjJCRS00NUJGLUFGM0MtNzc1RTc4M0I4Q0VC/0",
"http://forlap.dikti.go.id/prodi/detail/MjU0QkNGOUUtRTU3MC00NUU3LUFDOUItRDI4Rjc4QUJDNEU2/0",
"http://forlap.dikti.go.id/prodi/detail/OERFQ0EzRDgtNjNDNy00QUNCLUJBMEItMzM4ODQ3RTk0N0JF/0",
"http://forlap.dikti.go.id/prodi/detail/MzM2OUQzNTItMjE0OC00MTMyLThDQTctMUIyMzRGMDVBMEEz/0",
"http://forlap.dikti.go.id/prodi/detail/Q0FCODY0MjQtNzgwMy00NjUzLThGMTItN0E1QkU2OTA5REQ2/0",
"http://forlap.dikti.go.id/prodi/detail/MUNGNUNFODItNzBBMS00NEU1LUFGQUYtOEFEMjY0QzRCMTUz/0",
"http://forlap.dikti.go.id/prodi/detail/MTYzOTJDRDctNEZDMC00NzcxLTgwQjUtQjU1MUNENjYxNDRB/0",
"http://forlap.dikti.go.id/prodi/detail/NDc3QjRCNzEtM0Y1Ri00QTJCLThCNjAtNUVEQUY2NzhCRDM5/0",
"http://forlap.dikti.go.id/prodi/detail/QUU5MDlEQjYtNURGQS00Q0Y0LTg3NEQtMDVGRTk3ODAwNzNB/0",
"http://forlap.dikti.go.id/prodi/detail/QTNEREVERDEtRUE2QS00QzM2LUJCOEEtNUU1Q0E3MEQ4QUI0/0",
"http://forlap.dikti.go.id/prodi/detail/RjI5NjlDMDEtMEU4OS00NjJELThCQzItOUI0NDIzREZEMEFC/0",
"http://forlap.dikti.go.id/prodi/detail/MTdFRUU0NkUtNTZBRS00QTIyLUE1Q0QtNkQ5MjQzMUVFNTRG/0",
"http://forlap.dikti.go.id/prodi/detail/OTIxN0FCQzktNTY3RC00OEY3LUJFM0UtNTkxQjg4ODAxODFC/0",
"http://forlap.dikti.go.id/prodi/detail/RDI1RTU3OTgtMkNEMy00QzA4LUE5OTYtNUJBOUZDREI5NkYz/0",
"http://forlap.dikti.go.id/prodi/detail/RDY3QTIxRDItRkIyQS00MkJELTk1NjMtNkNDMzE0RDJDOTMw/0",
"http://forlap.dikti.go.id/prodi/detail/RDRCOUFFOUUtNzRCQy00MjIwLThDQ0UtNUVBREI2Q0M5QUM0/0",
"http://forlap.dikti.go.id/prodi/detail/QkJERDk3RjAtQUIzNS00NjNBLUI4NUYtQzI2NkEzQTU2MDE1/0",
"http://forlap.dikti.go.id/prodi/detail/NzAwNkFBOEItNkNDNS00QzVELThFNkMtODhCMkMzRkI4MEIx/0",
"http://forlap.dikti.go.id/prodi/detail/MkZDRjQ5QjktMTBGRC00ODg4LUEwNDQtNEM3Q0IwQkEzMjU3/0",
"http://forlap.dikti.go.id/prodi/detail/Njk4MEZBQUUtMjJDRS00MkZDLTkwOTktOTY5MjE5RDE5RUJD/0",
"http://forlap.dikti.go.id/prodi/detail/RjIwMDkzODktRjM5Ny00NzY1LTgzMDktMjNFRUM1QkM2QzI2/0",
"http://forlap.dikti.go.id/prodi/detail/RjQ1MUNGQjktNEFCMi00RDk0LUIzRDQtNTU3Njk4RTlGNzQz/0",
"http://forlap.dikti.go.id/prodi/detail/MEU4RDU2RkYtNzFGNy00NTZBLThENzEtMzAzREZDMDE5NDA1/0",
"http://forlap.dikti.go.id/prodi/detail/QjY0MDE5RkMtNDhDNC00QzA5LThBQkItNzY5M0Q3MUMwNDFB/0",
"http://forlap.dikti.go.id/prodi/detail/QTc5RjY4RTAtRjk2NS00QUIzLUExRDctOUUyMkNBOUFDNzYw/0",
"http://forlap.dikti.go.id/prodi/detail/MDBFM0ZCODAtNUYyQi00Q0Y3LUFDNkMtN0Y3RTY2NTQwMjA5/0",
"http://forlap.dikti.go.id/prodi/detail/NTY3REE1RTAtNTU0Ri00QzMxLTlBQkMtOEVFOTQ1NkJDMzY2/0",
"http://forlap.dikti.go.id/prodi/detail/NjhGMEY1N0EtQzg1QS00ODc2LTg3NzAtRkY0NkY0MEJGRkVC/0",
"http://forlap.dikti.go.id/prodi/detail/RUQxQkU5RTMtRTUzOS00QjQ3LTk4OUQtQzkzMUQ5MEFGNkZC/0",
"http://forlap.dikti.go.id/prodi/detail/RDdDNUIzQkEtMDQyRC00OEY2LUIyNzUtQTM2NUQxQkJEN0Q5/0",
"http://forlap.dikti.go.id/prodi/detail/N0FENEY2NzItODQ0MS00NTc1LThCQjAtMjA4RURCQjU3MThB/0",
"http://forlap.dikti.go.id/prodi/detail/MzNCMjk2NEMtQkQ0MS00MzAyLUJBQjUtRTk1ODVBQzY5NzIy/0",
"http://forlap.dikti.go.id/prodi/detail/RTM3QUNDNkEtQjFDNy00QzkyLUE5QzctRjQ5Q0YyMkYyM0E1/0",
"http://forlap.dikti.go.id/prodi/detail/NDI1N0JGNzYtOTg4NS00QzZBLTkwQkEtNjM4REEzRjdFMUE1/0",
"http://forlap.dikti.go.id/prodi/detail/ODM0QkU4MTctMzEzOS00MkZELTk3M0ItMzA5MEU1RUQxNEM3/0",
"http://forlap.dikti.go.id/prodi/detail/QjA3NDUwNDYtQzkzQi00QzI1LThDN0QtNTMwMzQzNTJFRDRF/0",
"http://forlap.dikti.go.id/prodi/detail/OUIzRkFGNjItMjdFQy00QkJDLTk1MjYtRDg3NjkxNzNCMUVB/0",
"http://forlap.dikti.go.id/prodi/detail/ODREMkM1MEUtRTBFMi00MTIzLTg4MkEtREVEQ0NDOUMyRkQy/0",
"http://forlap.dikti.go.id/prodi/detail/NURDRkJCOTYtM0FDNi00RUQ4LUIxM0YtQTVBMDdFNDg3QzU2/0",
"http://forlap.dikti.go.id/prodi/detail/NkFENDJDQjctNDI1NS00ODVCLUE0QUEtNjk0RkNGM0UzQzhG/0",
"http://forlap.dikti.go.id/prodi/detail/NEUxRDE1OTYtNDIxRC00MjZDLUE0MjUtMjI3NTZCRDRCRjYx/0",
"http://forlap.dikti.go.id/prodi/detail/QzI5MkNGODktNDc3Mi00QzBDLTg0N0MtQzIyMUJCNDE0QjNF/0",
"http://forlap.dikti.go.id/prodi/detail/NThDRjk4NTItNEQ3OC00Q0FFLTg0OTgtNUY0RkM3NzJCMTEz/0",
"http://forlap.dikti.go.id/prodi/detail/QjYxMDBCQUEtNDNDOC00NUVFLUE4NkMtM0JGMEM0Nzg5NTdC/0",
"http://forlap.dikti.go.id/prodi/detail/REI5MTU1MzEtQzJERC00RUVBLTg3NkYtNjBERDM0M0FGQkZB/0",
"http://forlap.dikti.go.id/prodi/detail/MDM1QTI1M0ItOUJBQy00MkE1LTk1QTMtNTI0MDdEREM0RkJB/0",
"http://forlap.dikti.go.id/prodi/detail/M0VGQkEzODMtRDRCOS00OEIyLTg5NjItMTc3OEEwNUUyMTIy/0",
"http://forlap.dikti.go.id/prodi/detail/QzZFRDFCMjUtMDEwNy00Q0VFLTkwMkItMzc0Q0M3QzE5MDgw/0",
"http://forlap.dikti.go.id/prodi/detail/OUE1QTVFRkYtRjY1OS00OERELUFBMTYtMzYyMThDMkRGMURF/0",
"http://forlap.dikti.go.id/prodi/detail/REE5RkMyODUtODJGQS00NzYyLThBMTgtQkJFODA1N0M3ODE2/0",
"http://forlap.dikti.go.id/prodi/detail/NzMyOTVGNzQtODE4Qy00MjEzLUEyNDktQjA0MUFDREIxOEQw/0",
"http://forlap.dikti.go.id/prodi/detail/RDg5QTUwNEQtRjFEQS00MTA1LUIwNDctRTQxQ0ZFNzE1MTMy/0",
"http://forlap.dikti.go.id/prodi/detail/NTNCMjY3MjgtNTEyRi00RjU4LTk1MTMtQkU4NTk4RjgyNjM4/0",
"http://forlap.dikti.go.id/prodi/detail/RDM0RDdCQjMtNkRDNy00MTdCLTk0OEUtRUNCNDFFQzg1MkVG/0",
"http://forlap.dikti.go.id/prodi/detail/Njg1RDcwNTctMEVFNC00NEI0LUJFRkMtMjVGRTMzMEQzMjAy/0",
"http://forlap.dikti.go.id/prodi/detail/RTIwNTQ4QjEtRTc2QS00NUMwLTlCNUItRjlDQjgyRDFCRTVE/0",
"http://forlap.dikti.go.id/prodi/detail/RTBENzQzMzQtRjZDMC00MDM4LTk1RUMtODIxRjEyOTk5MzVG/0",
"http://forlap.dikti.go.id/prodi/detail/RDI1REQyM0QtRTg4My00MTJGLTgzRDYtMzFDODA1OTMwRjNC/0",
"http://forlap.dikti.go.id/prodi/detail/OTlDQzIyNTgtMEU5Ni00REVCLThEMkQtNDczQTdBMzA1NzBF/0",
"http://forlap.dikti.go.id/prodi/detail/RUQ0Njk3REMtOTBGQS00NjY4LUI4QjEtQzczRDlBRTg2NENB/0",
"http://forlap.dikti.go.id/prodi/detail/NzVGNzBEMzYtNUZFOC00QTY3LUE2ODgtMTlFNjM0QUIzM0VE/0",
"http://forlap.dikti.go.id/prodi/detail/MTcxRTcxRjItOEREQi00REM2LUFBOTAtMjQ2QjZCRDgxMDNF/0",
"http://forlap.dikti.go.id/prodi/detail/MjcxQjg3MzktMDM3NC00QjIyLTg0MzctOUU4QzVDMjJCM0Y3/0",
"http://forlap.dikti.go.id/prodi/detail/NkEyMDUwNUItQUUyRS00RjU0LTk0MjctRThEODdEOThGMjUx/0",
"http://forlap.dikti.go.id/prodi/detail/NEIwRUNCREItQUExNC00OTY0LThDMEItNTc1NkZFQjhDNDI0/0",
"http://forlap.dikti.go.id/prodi/detail/NkYzOUFFMjItN0E0My00OUY5LTkzMkItOEMxMTFGQzk0RjlD/0",
"http://forlap.dikti.go.id/prodi/detail/Q0Q4NUJFQ0UtM0ExNi00OEVFLUI0RjMtNzlGMDVGN0FDMEYw/0",
"http://forlap.dikti.go.id/prodi/detail/Mzk0OTA4NzMtMjMwNy00QkZELTk5NDItNEMwMzdFNjczQUZB/0",
"http://forlap.dikti.go.id/prodi/detail/RURBQURCODEtNkMyOS00QzhCLTk2MTktOUREQzAwNTBENDMx/0",
"http://forlap.dikti.go.id/prodi/detail/RDU5QkM5OEQtRDBEMi00MEVFLTgyMjctQkY1MjRDRkYxOTE1/0",
"http://forlap.dikti.go.id/prodi/detail/QzMzNkUyNUMtOTBDMi00NzAzLUJCNDYtMjMxQTY2MEYyNjM3/0",
"http://forlap.dikti.go.id/prodi/detail/MDM1M0YyODMtMDdCOS00ODU4LUE3RDgtOTJENjlFQzFEQTc3/0",
"http://forlap.dikti.go.id/prodi/detail/NTk0MDFCRjktRDkzNi00ODZCLUEwQUUtM0MzMTIxNTEzMzA4/0",
"http://forlap.dikti.go.id/prodi/detail/RjQwNDBFMDQtQTA2OC00RDE0LTg3QUQtRUFCN0MwMUREQjNG/0",
"http://forlap.dikti.go.id/prodi/detail/NzFBRDk3QzktMTZBQi00NTU3LTkxNEMtODg1QTQ1MzM0QzZD/0",
"http://forlap.dikti.go.id/prodi/detail/M0Y4ODhENzktRDc3NS00QUVBLUE2NjUtNTA1NENBMkRENjUw/0",
"http://forlap.dikti.go.id/prodi/detail/QkQyMjk4QTgtRjZDMy00QTI4LUE4MzEtMkUwNEM1OTJFQzgw/0",
"http://forlap.dikti.go.id/prodi/detail/OEI2NDc0MzItNDQzNi00NTE4LUE1N0YtMDhEMzlDOUE0MUY3/0",
"http://forlap.dikti.go.id/prodi/detail/RThEMDMxOEUtRjBGMC00QTc0LUJDNEEtMzc0QzI2N0Q0NkJF/0",
"http://forlap.dikti.go.id/prodi/detail/MDkyRTYyM0EtMjk5NC00NjY2LTg2QjktMDk5OEE1NTg3Q0VD/0",
"http://forlap.dikti.go.id/prodi/detail/RkVGOEQ1NDMtOTA4Qi00RUU2LTkwRjctMzRBRUYzMERENzI5/0",
"http://forlap.dikti.go.id/prodi/detail/Q0Y2ODhDMzktODQwRS00NDA2LUFDNTMtNkJGRkM5QUMzQjUx/0",
"http://forlap.dikti.go.id/prodi/detail/RDE2NTM1MjctMTkwNy00M0QzLUFEMjItREMwNDE3RkY0ODI4/0",
"http://forlap.dikti.go.id/prodi/detail/MjA2M0IzQzktMkQ1Ri00MzgxLThFNzctMzc2MDE3MUVCQzg2/0",
"http://forlap.dikti.go.id/prodi/detail/QzZBOEE4RDgtMkRDMS00MkM2LTlCRTgtNDVDRDhGOTM5MEVC/0",
"http://forlap.dikti.go.id/prodi/detail/MDE2NDI2QzEtQUUwMy00Q0E5LUE4MjQtRTlBODI4QUNCOUQ1/0",
"http://forlap.dikti.go.id/prodi/detail/OUZERDhCMzAtMjFBRS00RURCLTk4MkItMzJERUYxQkYxNThG/0",
"http://forlap.dikti.go.id/prodi/detail/M0FGNTNGMzgtQkFERS00NjEwLUFCRTgtMzY2RTkwNzgxODEz/0",
"http://forlap.dikti.go.id/prodi/detail/MTQ0Rjc5NEMtRDBCQy00OENELTg4QTgtQTM5QTY5QzY0QzU4/0",
"http://forlap.dikti.go.id/prodi/detail/MUEyQjBFMDUtRjNFQy00NEU4LTlFQ0YtMjAzOUY5NTkwRjVG/0",
"http://forlap.dikti.go.id/prodi/detail/QTUyN0NDQkQtRjBFRC00NTM1LTk4MDYtRkQxMzMyQUIwQzYy/0",
"http://forlap.dikti.go.id/prodi/detail/OEQxNTM4QjEtREYzQS00RDgyLTlENUQtNTMxMkMzRTdCODlF/0",
"http://forlap.dikti.go.id/prodi/detail/MjAyMDIyNDYtMTA1My00QkI0LTg3REYtNUJBN0I5OEFEQjQz/0",
"http://forlap.dikti.go.id/prodi/detail/NUNBQzEyNTAtQzFERS00NzlFLUIxMUQtRDFCOTdCN0Y4QkNE/0",
"http://forlap.dikti.go.id/prodi/detail/QkYyRUZEMjYtMzg3NC00QjMwLTlGMEYtNTZBOTM2OTcwMTcx/0",
"http://forlap.dikti.go.id/prodi/detail/RDE5OTIxQzAtQUYxOC00RDgwLUI4OTMtNzg4NDY3REVGMzY5/0",
"http://forlap.dikti.go.id/prodi/detail/NzQ1NzczNzgtRTU5NC00MTFDLUI5NEQtMDFGN0U5QkNDMjY3/0",
"http://forlap.dikti.go.id/prodi/detail/QUMxNTI0MDgtM0VFOS00Q0Y2LUFCRTAtRjM5Q0IyQjQ2NjRE/0",
"http://forlap.dikti.go.id/prodi/detail/RTdCNDZEQjMtMURFOS00MThELTlCNTktRkI2QTc5RUZENEVE/0",
"http://forlap.dikti.go.id/prodi/detail/MDExQTQ2RUYtRjFGMS00RTJELTkxRkQtRDQ1RTcxOURFRjU4/0",
"http://forlap.dikti.go.id/prodi/detail/NkE0RUQ2M0QtOTc5RC00MDJELTlEMEQtQzY5RUZBMUEwRDlG/0",
"http://forlap.dikti.go.id/prodi/detail/RjY1QzY2RkMtRkJDMC00RjVBLTgxMUEtREQzNTU3M0EyRkIx/0",
"http://forlap.dikti.go.id/prodi/detail/RUNCQkUyMDAtRDY5RC00MjUzLTg4QjktNjcwREVGMEQxQzlD/0",
"http://forlap.dikti.go.id/prodi/detail/QTBGRjgyN0UtNjcyRS00OUQwLTlGRDItNzEzMTJEMTRFOUJB/0",
"http://forlap.dikti.go.id/prodi/detail/MjUyMzg1NDUtRjVEMC00MjAxLUFDOEEtNDQ5NDEyMTY0NzY4/0",
"http://forlap.dikti.go.id/prodi/detail/OUNBMTNDOTctRUZDMi00NjZBLUJFMEUtNjI4NTAxN0Q0NTQ2/0",
"http://forlap.dikti.go.id/prodi/detail/Mzc4MDU4NTEtRkM2My00RTFCLUJBOUItN0U4ODZGNzhCNDVB/0",
"http://forlap.dikti.go.id/prodi/detail/NjU3NTg1MzctRDJBQy00REM1LUJBQTgtQjhDMzk2RENBNzQy/0",
"http://forlap.dikti.go.id/prodi/detail/NDBGREQ4QzgtQTdCNC00RkQ3LTk5N0EtM0ZBODkwNzQwMjBD/0",
"http://forlap.dikti.go.id/prodi/detail/OUVCQTI0NzgtMTI5MC00QkRELUI0M0MtMDcwMEI4RjNCMDcy/0",
"http://forlap.dikti.go.id/prodi/detail/MkUzNUU1NTgtNjIzMS00OTVCLUI5NDUtRjlCRDdGNjlDNTU4/0",
"http://forlap.dikti.go.id/prodi/detail/RDI5MzhEOEYtNDQ1NS00NDUzLUE2OUYtNkVCODFENEU2QzdE/0",
"http://forlap.dikti.go.id/prodi/detail/QUFBQzNCNDYtNUZBRi00NTEwLThENTMtNzc4MDUxOENDMjkx/0",
"http://forlap.dikti.go.id/prodi/detail/MDJEMDVERTctM0VCMy00NENGLUJFODEtRjg3N0E4QTEyODMw/0",
"http://forlap.dikti.go.id/prodi/detail/QjhGMThFMjQtOTNFNi00NzIxLTk3NTMtRkU4QzY0RTdGNjQ2/0",
"http://forlap.dikti.go.id/prodi/detail/QTA3QjBGRkQtQkE3Ri00RDE0LTk5MTktNjAwM0FEQTA0NjRB/0",
"http://forlap.dikti.go.id/prodi/detail/OURENTgwRDMtNjkzQi00NjBCLTlFMkYtMDQyRUVFRkJEMzkz/0",
"http://forlap.dikti.go.id/prodi/detail/Q0UwQzdFN0QtREY4My00OUEzLTg3NjgtNjZCRDAwQjNCQjFD/0",
"http://forlap.dikti.go.id/prodi/detail/M0JDMDE4OUItRThDMy00NEJCLThDQTEtRjNBQzk5QzIxMzBC/0",
"http://forlap.dikti.go.id/prodi/detail/NDcxQ0UyMjItREQwOC00QjZDLUI3MUQtN0QwOEQzRThDNTJG/0",
"http://forlap.dikti.go.id/prodi/detail/NzU5MUVCOUMtQkE2RS00MDc4LUE0QkUtRDZDQjc2M0VDQUQ1/0",
"http://forlap.dikti.go.id/prodi/detail/NzAwMzIzMjUtQzlCOC00MjE0LUJCNEItNjgyNEFCMzEyMkQ5/0",
"http://forlap.dikti.go.id/prodi/detail/RDA4RjgyQzMtRTY3MC00MzQyLThDMkYtMjZCRkU2RjVFRTBC/0",
"http://forlap.dikti.go.id/prodi/detail/RTcwRUIxMkEtNEFFNC00MzM2LUExMUMtN0M5QTYxMTA2QkJC/0",
"http://forlap.dikti.go.id/prodi/detail/RDYxMkQxQjQtNzU1NS00MEMzLUI1QjAtMUJCN0M5NjlBNjFD/0",
"http://forlap.dikti.go.id/prodi/detail/N0FFQjY5RUQtQUU2QS00Mjc1LUE4MDktRDA0RUQwODE1MUI0/0",
"http://forlap.dikti.go.id/prodi/detail/RENGRDUyRkEtRUJCRi00RDNELTlBOTAtREQyREVDMEIxRUE4/0",
"http://forlap.dikti.go.id/prodi/detail/ODc2QzNFNTEtQzIwMC00RDExLUI5RDMtNEY1NzE1OEM2NUU2/0",
"http://forlap.dikti.go.id/prodi/detail/Q0U3QTE1QzctNDU4MS00ODgwLUJCMDktRThDMjQ2RERCMTFB/0",
"http://forlap.dikti.go.id/prodi/detail/OTJENjUxOTEtMUMxRi00MjIwLUIzRUQtOTJGRUI4QTc3NjM1/0",
"http://forlap.dikti.go.id/prodi/detail/OUU2NEY3OTYtMTkzQi00RTMyLTlFMEUtNEMzNDIyOEI1MzdE/0",
"http://forlap.dikti.go.id/prodi/detail/NDY2NTFCRUItNDY4RS00RDJFLTk0MUYtOEUzNDYzRkUwMTAy/0",
"http://forlap.dikti.go.id/prodi/detail/MjVDOTcxMTMtNDRGMC00N0VFLUFDRDQtOEY1M0FEMjJGRTEx/0",
"http://forlap.dikti.go.id/prodi/detail/N0FBMzEyMTEtNjI1RS00MzIxLUE1NjQtOUJCRTdCOTQzOEYz/0",
"http://forlap.dikti.go.id/prodi/detail/M0NGRUM5MkMtMTNBRS00QTAyLTkxM0QtQ0UzN0E2NzMxNDNE/0",
"http://forlap.dikti.go.id/prodi/detail/QjlERjE1MTEtNDQ4My00NkIwLThBQUYtOUQxODFENDREMDZE/0",
"http://forlap.dikti.go.id/prodi/detail/N0RCNjFFRDUtNkYwNS00MzAwLTkxMDctNUU2MDA3QUI1ODgz/0",
"http://forlap.dikti.go.id/prodi/detail/RTNFRTg1NEQtMkQ5Ny00RjdELUIzOTctQjA3NTE4Q0NBQURE/0",
"http://forlap.dikti.go.id/prodi/detail/NDU4Rjc3QzgtQUExQi00MzY5LUEwMzMtQ0FBODFGN0JDMUFC/0",
"http://forlap.dikti.go.id/prodi/detail/RTkyNUM2ODYtRDZGRC00RDZFLTkzNEQtNzU4QzcwOTFERTEx/0",
"http://forlap.dikti.go.id/prodi/detail/MkNGOEFBQUMtMDkzRi00Mjc4LThDMTgtRDE5QjQ3Mzc2OUI4/0",
"http://forlap.dikti.go.id/prodi/detail/M0VDOUU5RDctOEM4Ri00MUE5LTlFQ0YtRDc1RjI0OTIwNkUx/0",
"http://forlap.dikti.go.id/prodi/detail/MDY2NEZCODYtMTU1Qy00QzJDLUJBMTktQzRBODVCRDRGMTlB/0",
"http://forlap.dikti.go.id/prodi/detail/MEI4NDEzNDgtQjU3Qy00MjFFLUFFQjEtMTk0QTU1ODI2MjRB/0",
"http://forlap.dikti.go.id/prodi/detail/Qjc2NDYzMUEtNzY4Ri00MTVFLTlFMjktMkE4RDlDMTkzREM0/0",
"http://forlap.dikti.go.id/prodi/detail/RTJFMkM0RUQtNjA3NC00NkE5LUE4NzEtMDI1NTVENUEwMjY2/0",
"http://forlap.dikti.go.id/prodi/detail/NDFFNzREQjItODBGNC00NzA5LUE5NTItOUIzMTdCNDk3NDE0/0",
"http://forlap.dikti.go.id/prodi/detail/NTlBQzE0QUItMTMxMy00Q0U5LTg3ODUtNDdDRDg2NDM0OUMw/0",
"http://forlap.dikti.go.id/prodi/detail/QUJCRjMwMzAtMTVGNy00OUM0LTg0QTgtQzM5RERDQjQwRjA3/0",
"http://forlap.dikti.go.id/prodi/detail/NzkwQUM4M0QtMTcwRi00NkVDLUJFQjctNDlEQTQ5RjA5NDU1/0",
"http://forlap.dikti.go.id/prodi/detail/M0FBOEFFMUYtNDNFOC00Mzc4LUE5MUItMTc5Q0VEMDhGRDk3/0",
"http://forlap.dikti.go.id/prodi/detail/M0EyQTdDNEItQjdDOC00MkYxLTk0QUEtQjRBQjMzNzAzRjU3/0",
"http://forlap.dikti.go.id/prodi/detail/NDAwRkU2NDMtNkE4Mi00ODM3LUI1NzQtNjM5M0EzMjlDNEVC/0",
"http://forlap.dikti.go.id/prodi/detail/NEIyRUYwRjgtOUI1Qi00QzE5LTk1NkEtQjY5MEI5ODc4N0Ex/0",
"http://forlap.dikti.go.id/prodi/detail/NTg5NUMzQkUtMDA2NC00MDBELTg4ODEtMDBCNzk5REM0RTEy/0",
"http://forlap.dikti.go.id/prodi/detail/ODdDOTU5RjAtRDNCNi00NjgwLTg1M0YtM0MyNThFMjk1NDMw/0",
"http://forlap.dikti.go.id/prodi/detail/NkY0QTY0MjAtMDlCQy00RDA5LUJBQkEtMDEyRUMxMjg3OTA0/0",
"http://forlap.dikti.go.id/prodi/detail/NTdBNzZDNTItNUJFOS00MDMxLUExNjctOTg4NjM1OTE1QkI2/0",
"http://forlap.dikti.go.id/prodi/detail/QzUwNkJGQUMtQ0RFMy00MzRFLTk0NkQtNkUyRDg5MDA2Nzc5/0",
"http://forlap.dikti.go.id/prodi/detail/QUNDNzE3RjUtNTc0OS00RDI0LUI2MUQtMDlGM0Y3OTI5QzdD/0",
"http://forlap.dikti.go.id/prodi/detail/NjRCNUJGNzgtRjVDNS00MTFGLUI2NDgtNEI4NUJCNUM2RjEx/0",
"http://forlap.dikti.go.id/prodi/detail/MUVCMEY4OUUtMDY0MC00QkIzLTgzQUQtNTc0NEE5ODgzQ0FF/0",
"http://forlap.dikti.go.id/prodi/detail/MkU1Q0NGMzktQ0QyNi00QzNGLUJCNTYtQjZEQzUxQ0MzODhD/0",
"http://forlap.dikti.go.id/prodi/detail/NENFREY0QjItMEQ5Ri00RTcyLUE2REYtQTUxNzc5MkNBODEx/0",
"http://forlap.dikti.go.id/prodi/detail/ODEyMTc3NkItNDdCRC00RDE5LTg0Q0EtODk5MjQ2MkVEMjg0/0",
"http://forlap.dikti.go.id/prodi/detail/QTM5QjZFMzEtNzNDNi00QTg1LThGMUItMTU3NUE5NUQ2MDZD/0",
"http://forlap.dikti.go.id/prodi/detail/NDNERjU4NTUtNTI2RC00QUJDLUFBMzQtRjlBRDQyNzY5RjMz/0",
"http://forlap.dikti.go.id/prodi/detail/OTdFQjI1RUQtMkFDNS00Q0Y3LTgyRjMtQTA2NzcxNUZGRENE/0",
"http://forlap.dikti.go.id/prodi/detail/OTBGMEQyOTgtOTM5OS00OEVFLUJCMjUtQkJGMzU4RDYxRjVC/0",
"http://forlap.dikti.go.id/prodi/detail/NzYxMTk2Q0QtQThFQS00MEZFLUI0NkMtMkQzQkMxRjM3OUEy/0",
"http://forlap.dikti.go.id/prodi/detail/QTk1QkZEREEtNTI1Mi00QjU4LTkwNDYtNUZGMThBRkY4MjQw/0",
"http://forlap.dikti.go.id/prodi/detail/NkZEQzM1QjYtOTE2OC00NDk0LTlGN0EtRTU4QTJFMjk2NTgx/0",
"http://forlap.dikti.go.id/prodi/detail/OEUxNUQ0QTAtRjJGQy00MENCLUIwMjMtNEM3NjhEQzk2MEQ4/0",
"http://forlap.dikti.go.id/prodi/detail/N0EwMjM2REEtNUVFNi00QkVELTg4MjQtQzY2MUZGM0MyM0Y4/0",
"http://forlap.dikti.go.id/prodi/detail/MThBNUMwMDYtQTE1Qy00MTExLUFEREQtNjFBNjdENzlCRkNE/0",
"http://forlap.dikti.go.id/prodi/detail/QThEQzMxQUYtQTQ0Ni00OTlGLUFEQTQtQTI1NThFNjlGQTRD/0",
"http://forlap.dikti.go.id/prodi/detail/MkExQjM3NjYtQ0IwOS00RjJGLTkwMTgtN0M0N0JGMzU2OEQ5/0",
"http://forlap.dikti.go.id/prodi/detail/MDg2RDc3MkItODFFNS00RTBCLTgwREUtRThDNkY1RTczQUMy/0"
        );


function bacaHTML($url)
{
    // inisialisasi CURL
    $data = curl_init();
    // setting CURL
    curl_setopt($data, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($data, CURLOPT_URL, $url);
    // menjalankan CURL untuk membaca isi file
    $hasil = curl_exec($data);
    curl_close($data);
    return $hasil;
}

date_default_timezone_set("Asia/Jakarta");
echo "=========================<br>";
echo ">> Mulai : pukul " . date('h:i:s') . " WIB<br>";
echo "=========================<br>";

echo "No : Nama PT : Kode Program Studi : Nama Program Studi : Alamat : Kode Pos : Telepon : Faximile : Email<br>";

for($x=0; $x<=367; $x++)
{
    $kodeHTML = bacaHTML($html[$x]);

    $namaPTN = explode("<td class='tright' valign='top'>Perguruan Tinggi</td>", $kodeHTML);
    $namaPTN1 = explode("<td class='tright' valign='top'>Kode Program Studi</td>", $namaPTN[1]);

    $kodeprodi = explode("<td class='tright' valign='top'>Kode Program Studi</td>", $kodeHTML);
    $kodeprodi1 = explode("<td class='tright' valign='top' width='200px'>Nama Program Studi</td>", $kodeprodi[1]);

    $namaprodi = explode("<td class='tright' valign='top' width='200px'>Nama Program Studi</td>", $kodeHTML);
    $namaprodi1 = explode("<td class='tright' valign='top'>Tanggal Berdiri</td>", $namaprodi[1]);

    $alamatPTN = explode("<td class='tright' valign='top'>Alamat</td>",$kodeHTML);
    $alamatPTN1 = explode("<td class='tright' valign='top'>Kode Pos</td>",$alamatPTN[1]);

    $kodeposPTN = explode("<td class='tright' valign='top'>Kode Pos</td>",$kodeHTML);
    $kodeposPTN1 = explode("<td class='tright' valign='top'>Telepon</td>",$kodeposPTN[1]);

    $teleponPTN = explode("<td class='tright' valign='top'>Telepon</td>",$kodeHTML);
    $teleponPTN1 = explode("<td class='tright' valign='top'>Faximile</td>",$teleponPTN[1]);

    $faxPTN = explode("<td class='tright' valign='top'>Faximile</td>",$kodeHTML);
    $faxPTN1 = explode("<td class='tright' valign='top'>Email</td>",$faxPTN[1]);

    $emailPTN= explode("<td class='tright' valign='top'>Email</td>",$kodeHTML);
    $emailPTN1= explode("<td class='tright' valign='top'>Website</td>",$emailPTN[1]);

	echo $x+1;
    echo $namaPTN1[0];
    echo $kodeprodi1[0];
    echo $namaprodi1[0];
    echo $alamatPTN1[0];
    echo $kodeposPTN1[0];
    echo $teleponPTN1[0];
    echo $faxPTN1[0];
    echo $emailPTN1[0];
    echo "<br>";
}

echo "==========================<br>";
echo ">> Selesai : pukul " . date('h:i:s') . " WIB<br>";
echo "==========================<br>";

?>
