<?php
$html= array(
           "http://forlap.dikti.go.id/perguruantinggi/detail/MEI3QTg4REQtRENENi00Q0Q1LTlBNTUtMUM4OTc5RjYyRjQw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MkYzRkY5MDMtQ0Y5Qy00MTVELTk1RjMtOTYwOEM1ODAxQjIy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzlCNUU4REEtMkU5OS00QjIyLTgyOTYtQkQyQUY2MDRCQzdB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDYwQzZBNUQtOTNFMy00OTE1LUE2MUMtMUI1NUM2MkFGNkI4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTE1NDBBRDAtQjI3Ri00MTQ0LUFFNjItMzM3NkJEM0RFNDg4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NUUwN0MwN0QtQTBBNy00MkVFLTgwRTgtRTQ1NjRDNjhFNjU2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkFEOTY2REYtRUEyQS00MjJDLTgyRDgtNUZCRDkyM0Q3Q0Ew",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkRGNjE3RDctQkUzMi00NTAxLUJGMjAtNDQzREY4QTRFNjUw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODY2MDI0RDgtMTQwNS00MUI2LThERDctQkRCMkNEMENDREYy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODc0NDgxQTMtMzk2Ny00ODE0LTg3MjAtOEIxMkJFQUM3NTFF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODg2MUE2MEYtMTZFRS00MjdELThEQTgtQTc2OEIxMkFFQUJE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODhFMzgzRTMtOUJBMS00MEEyLTlENUItNDgwOEMyNjY5N0Q5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OERDNUZGMjctQTFCQy00NjAxLUI4NTctRUYzNDY4QjIwQ0Q2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QUMxQUNEMkMtQzQ5OS00NUFDLUI3OTAtNzZGNUU3Mjk2REY5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QkY4QTU5OEItRjQzNC00QjBCLUEzMDctMzM4NkNBQjkyOTdD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzQ1MDUyQUMtRUU2Ri00NTVELTg4ODItODA4REUwMEJGMDFG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzVBQjI5ODctQzNCNy00Q0FBLUEwNkItQ0IxNjYyOEFGMEIx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDY2ODM5QTEtNkExNS00RDg1LTlFNkUtOUM4QzAxREUwQUI2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RThFMzIxMzUtNDUwRS00NjQ3LUIxOUItODIwMTk1QzYyQjg1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RUNBQjk5M0YtRTA2Mi00RkRGLTk0OUYtMDZGNTEwQzVENjdB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MUE3MEQ3RkQtMERCOC00Qzk3LUEyN0MtMzY0MjNBMzcxRjdC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MUI2MTdGNzYtRDYzRS00OTU1LUJBQ0UtNDc2OEI3MUZCOUJD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MkU4RThBNDctRTUwOC00RkM1LUI1MzEtQkI1QjU1REZCMjdF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzE2N0JENTUtRDQ1RS00NjM1LUFDMEEtQTRFQzFERUI0RjJE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzYwQjdGMzktRDBBRS00RURFLTk3QTAtMEQ5NDlGQzUxMTVE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDREQUIwMjgtOUUxMy00RUJBLThBOTYtMEU2MzM0OUYwMjM4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDgxNUJBMkEtN0I1QS00MERDLTkzRTEtREEwMkM2Rjk3Q0Yw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDkwRTUwRjktODE3MC00NDc1LUEyMTgtNkY5NTZCRTU0RTBE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTRBM0FBOUUtNUE3Ri00OTRELTgxRjQtMjk3RTg0RjNBMkYw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OEQ3NTlGNkEtOTBFMS00QzM3LTgyMTEtOEU1OUVEMUYwRTk0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTEyNkIyOUYtNTJGQi00MzU2LThBRTMtM0IwMTI3OTcxQkE0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTMyMDdBNTMtMTJENC00RjMyLUIzMkQtRTA4OEVDNUEyQTM0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUY2MDBGMEEtMEVDRi00Rjc1LTk3NTEtMDdBQTVFNUYyMDNF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTZFQTAzNEMtMEM3Ni00OTVGLThFODktQTJFOTUzQzlCQUNE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QkNEOEFEMzctODUyRS00N0MyLUI4RUUtNUQ2QTREOTg4RkYx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTE0QTQ0QkQtQkQ3RS00RjVBLTgzMTQtRDZEN0IyMjMyMzVF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTE5MUVEQkMtOUYxRC00MTg0LUFDQkItQkYzN0ZFNUM1NDA4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTIzQjY2MEUtRkU2My00QkRELTlFOUUtMzYyMjQ0MTJCNTRF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjU2MDE5RTQtQkNFOC00NEM0LUJGRjItNUE1RkNBRUM3QkI2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RkU4RjhEMTAtQzE4Qi00NkM0LUE4OTMtRTdCRDhGOUMxMTg4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/M0Y5RERBOTktODgxQy00M0QwLThCOEUtRjc1MTFBQzVCQkRF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDQ3NDk2NUEtQzAxOC00NEYxLTlGMDItNDE0RTg2MjAxQjdG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDU2MTNGOTktMTFDNi00QkZCLTkzRjYtNjU2MTdBQ0ZGNjQ2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MENDNkNDRkItMzQ0Ny00NzkwLUFDOTMtNkQ5RTlDODUxMDc3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/N0RDNDRGNDMtMjY0MS00MjAxLTgyOEEtQzQ1MzdBQTEyQTM2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/N0ZEMUU3REMtMjEwRC00OEQ4LUE4MUYtQTk4QTE4ODBDRkJB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NEY2NDg2QUEtMjU2OC00ODQ2LUExMEMtOTg3QTM1ODI1Q0Mx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjlCMzNGRjctNDQ3Qy00RUU2LUE5OTgtQjFCQjVDNDgyRTFD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTZDMjE4QjMtODMzNy00QjY5LTgyNTMtOTIxNTZERTBDMDI3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTc5NTY4QzEtMTBFNy00QzM5LUJEODEtRDlDQjM2MzNGMDlD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTg2OTkwN0QtODVBQS00QTM0LUEyMjMtN0RBNDc2NTcwQTkx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTEwQTk4MjktREQyQi00NEQ3LTkwN0EtMkI5NDMwQUY1RUE3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTM3MzA3MjItRDdCQi00MkI3LThCMkEtNUQ5N0I2NEMyNzQ1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QkE3MTkzMjYtMEU0Mi00MjYyLTlFQzItQzczQzA4NjI1Njgz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDA3NkQwQUQtQUY5RS00NjM2LThFRkItM0RBQkM5NzZCMTND",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDZBNzczOTMtMjQ2Mi00MzkyLTkzNDYtODk3NDkzRjYyREIy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/REY4QTVGOTQtMDI1Mi00QTYwLUIxQTEtQUMzNjg2QThBQzQw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjMwMDE2RUMtNjRBOS00MjNDLUJGMEYtMjMzRjY4NTVDQUVE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjhEREE2QzItMTFGQy00QTE5LTkwNjctRjYzRTMxQ0JDRkJG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RkE2RjE0RDItNDEzMi00MDUyLUFFM0YtOEQ2OUVBODBGMEI4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDI2RjlENjEtMUQ0Ny00QkM2LTlBQkUtNjc2QUMzODAzNDBE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDgyMzBFQ0MtQkIwQy00NjY3LUE3Q0EtQjRFNTJGOEY1MDkx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MEVCMDEzRTItRjIxNi00NTQ4LUIxRkEtMDJGOEQ4NzUzNDA4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTI2NzVBNkUtMTMyMC00NTVGLTkyMjYtMDgwQTM3N0QyODc3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MUQ3NDE1RUEtQThDRS00QzFBLTg0MTYtQUMzMTAzQkU2RkJF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzY1RjEyNzgtQjVCQy00QTM5LUIzRjgtQzNGRjE0MDg3MzhC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/N0Y1RDJBNzktRjk5QS00MkVFLTk2OUUtMTMzQjExNTA4MjJE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NEFBRTkzQUQtNURDMy00QzUwLTg3RkEtMzg5NzQ3N0E2MzQ4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTQ2OUQ2MDQtOEVBMS00Mzk1LTgwM0UtMjU3MThGMkI2OUZF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTlENDA5QjctMDBCMi00QzM2LUE0ODktNTJBRTA2QzhBMEVG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkY5REQ4QjItODVCNC00OUU2LTg5OTQtNUJENThGQjMwMUY5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODE4RTY0MDEtRTQ3OS00NjAyLTkxRTYtNEQ2OUQwMkNCRkYw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODk3REI2OUEtQjY4Qi00MDcyLThCNjUtOUZCNTI0M0NDQjQ4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OThEQzI2RUQtRjE5Qi00MDlELUIyQjgtQjI3Q0ZFQTZFRTFE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUFCRDFDRTgtOTdCQi00QjIwLTk3QjMtNDczMEUwMTQ0OEFC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0E5NEJBNDQtQkVDRC00OURELTg2NTctRjY5NDhDODFBQzQ2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0MwMjVFRTgtM0REQi00MTM3LUEyOEEtNjkxNjU2OUYzM0U5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTU1MTkxMzYtNUQxMC00RDNDLTg0NzgtNzc3NDYxNEQxMDBC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTZEMDk5NUQtNzMzOS00REIzLThFM0MtMjUxRUFEREVFRjY4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTg1NEREN0UtQTQxQi00MkIyLUE4MjctNzE0QjNGQjlCNEZD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDBGQzM3NDAtNjlDQS00QTY5LTg0RDItM0I2MjM1MDREQTNF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDBGRkY2NTYtQjA4RC00MkRBLUJEMTYtN0ZDNDlBREMzQUE0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MUI0NzY3ODctMEIyQi00QzRFLTg0RjEtNzFBOEIyRjk3M0Qz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MkJGNkExNTEtQjU3MC00MjNCLUE2QUYtOEExNjMyQUJENEVB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/N0ZCODY4N0ItNEJGOC00ODlDLUIwMDMtRDE5MTAwNjk3Q0I0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDcxMzUzMEUtNjNFNi00M0Q5LUI2Q0QtMURBQ0U0QjkyQjRE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzkwRTc1NTgtNURDQi00MDk4LUJDNzYtRUYzMjRGMUNFQkQy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTNDNEE1OTMtM0IwQS00QzkwLTg1MzgtOTFFNjFFNjJDNTZG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTk4MDREMEItMUM0NC00OTdELUE4NzItQTk5RTc3Qzc1NTc3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUY2REQ0NkItNzEwQy00M0E5LThCNTktNzc4NUFCN0VFRDEz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0MzNUMxQTctRDIwMC00MjAzLUI0NDMtRUM5RTgzQzg4MUND",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTAwODUzQzAtNkU0MC00RTAwLUJFREYtMzg1RTAwNDFBODY3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTQzQThDNEYtQThDNi00NEYyLTg5QjYtQTAxMjZGNzVBQ0Iw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QUYwRTEwQTMtNTM0NC00OUMxLUFFOEUtMTJFMDIxQzFCMzFB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjJGNThCNzgtRjk3Ny00MzBCLTgyMTgtQzEwNTFFRDlFQzAw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QkE3OUVDNkYtOTMyQi00OTNCLUE4NkItMDQwNTM1NDI3RkND",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzRDN0U1RTQtNEZBNC00RkEwLUFCNzktMDhFODFEOTYxNUE3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzkyNzRBRkEtQjlDMi00NDc5LThDRTctN0E0OEUxMzU5MzlB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDg2MEI3NTMtMzcwOS00RDJELUFFNDMtREE4NTVCNUI3MjdF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/REU3MDRBNTktN0UyNC00NEM4LTlDMUQtNDBCRTlCNEJCRjFF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTgzQkY2ODEtMUNEQi00NDAzLUI5N0MtNEIzMURGMUVEQUJD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjI1QUNFNDItMTcwRS00QzUxLUIwMzgtNEZEQkRGRDk1RjY3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDUwRUFFM0UtREFFOS00NDcxLUFERjUtRjIzN0QyODlFMDZG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTE5MjMzRUEtRDIzOS00NDlBLUEzRkUtQ0JERTVBNzc5NzVF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTQ0MzUwNTMtNDQ3Qy00OTdELTkxQjYtQzYwMTg5ODk3Njgz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTczNUVFNEEtRDM5OS00MjdELUI3ODktMzZBRUZDODA1MUI3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkEzOUI3RTEtNUI5My00NDA1LTg2ODgtODc3RUUyN0Q5ODI1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzMxM0NEQzUtNzlGNC00NEJELTg1NDUtODYyMUE3MzAyREEz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTQ1MTdEQjAtMTM1RS00MDRFLTk1NzUtODkyOTFCOUVGQTlE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUYwMjlBQjQtOTlDRS00MkNDLTlBMzMtRTE5NjdEOTQ3RDlD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0IyRDA0MTYtODEwNS00MDA2LUFGRjAtNDI0RkM3MEI5RDVG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTJCRUJBRUYtNTcwRC00N0ZFLTlGQ0YtOURFQzQ4OUI4QUNB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QUREMDhCQkYtMUU1RC00NjYyLTg2QUYtMjRBRDg2QkQwMDZF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/REZGQTI5NTctNDE1QS00NDI2LTkwOTItQTBEMzI2NTY0NEFE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTA5Q0E5NjQtQTMxMi00RTYyLTk0QzAtNjM0ODA0NkQzNjhB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTJBQTExMTQtNDkwNi00NjcyLTg4MUQtQTcyODE5QjMyRDUy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTQwMDlGMzItQzNGMi00MjRGLUJBMDYtM0EwM0FDODMzNTQw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTlGNEMyRUUtNkNDNi00REM2LTg1MzktREMxQzhGMjA3RDVD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjJDMjEwOTQtNkEyOC00Q0VGLUJCRjAtNkE1NTI5OTQwOEYw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjgwQUFENTAtMzI5OS00MzFCLUFDRTUtQjk3NzM1MDQ2NjdC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDYwODEzODQtRDM1RS00OTYyLUI5OTYtOTlBOTIxQjRFMDNG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDgwQkUxMjQtRDVCMS00QThCLTg1MjAtQjM2RUY3Mzc1MkFD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDk2QzI0RDEtNUVFNi00MjhFLThBRDctQjE3RUVFNTM1MUNE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTNCRDE3MzYtREY1MC00MTg2LTg4Q0ItODgxNzU0RTA3MEJC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTYxMTc3QTItRjUzOS00QTU0LUE4MkUtRjIxRDA5RENDRjND",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjZFRkY4RDctQjc3Ny00MUM3LUFGQTctMUMxMzQzODA4OEVB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NUM2QzhCMTEtQTgyQi00QTZBLUE4MjctOTRCQTVGNURDM0NE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODRCOUI4ODctNkI0QS00NzI1LTkyOEItQzU1RDdCRDk4NUNE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODZENkEwRDAtMDNBNy00N0ExLTgxN0EtQjY3QzdEOTU5RTQ2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTZDMEYyMzYtMENBMC00NEVBLTg1NzItQ0EyRDQ3REQ2MDM4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUI5NDUyQTUtRThFNi00Q0E5LUFBNDMtMkJCOEU0RDhBNEIx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0REMEYxRjAtQTdEMi00REUzLThFM0MtMjA3RjY0MDFDN0RC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTc4Q0FBMTEtQTdCQS00MjI2LUIwMUUtMTQ0Nzk0Q0FCMzI5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QUQ0Rjk4MEYtNDAyNC00MEFFLTk3Q0UtNkY0RTAyNUIxQjFE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjlENkM3ODQtNkY0MC00MkQ0LThGNEYtOEVFOTA2OTAxNzIw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QkU3MkJBQTQtOUM2QS00RTg5LThGMjgtRkU0MDU2NEEyMjJG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDg3Q0VEQzAtRTAzQS00NzQ3LUEzMkEtNDhDRTgxMjgxNjlC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RUNDMzNGQ0UtQzNDMi00M0VBLTlCRTEtQjdDREMyNDcyNkI5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjM4NzE2RTgtNzhDNy00NEY1LThFNzktNjA0M0IwRjdERTE4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjVERjQ1NEUtRjQwQS00ODRELTkyMDItQUJCM0E1ODZDNTI1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTNCRENEMEEtRkM0Mi00OUI0LTg2RDQtQTdFMUFCNTVEMjA3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTdBQkZCMTQtNkNDMS00NjNCLUJFRDQtMUJBNUUzQ0E0MzNC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjEzRjMyMjItQjM3Qy00NDAxLUFCNTItRDZGOUU3REE4M0Uz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzhGMzg1MUItRkE5OS00NzY4LUFERkQtRjAxRTI5REZCQzc5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/N0Q0MkRBNzItOUZGRS00NUQyLThGNjEtNEU1NEE0NTE0QUEz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTU1MTg5NzAtMzAzRC00NDJGLUEzOTAtRjRCRUU3NUM5MkY5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTk0Q0I4QTMtNEExRC00MjNCLTg3OEYtRTJBMENGNTFGREYz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODQzMzlGNjgtMTlFNy00MkEwLTkzMkItQjhBOTY2QTFGN0U2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODUxQkY0NDUtMUUzOS00NzRCLUE5RjItNTM3QUFEMEVGOTc4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OEUxQzg3MEMtOTcxMC00MUVFLTlDRkYtMzk4NDkzM0YyMjg5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTE4NTE0QTQtN0M2MS00NjJBLTlCMjEtMTE5ODEzMTgxMkI1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTE4RjA4NTYtMTI2NC00MzNGLTk5MTUtMjFBMjJGQURGMzgw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTgzMzNGN0UtRjAyMi00OUI3LTlCMTctN0JEQjhCNzhBRTBB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QUM3MkNGRjgtOEZBRC00NjdFLUJGRDgtRThEMERDQUYyQjQ3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QUQwOEMzNjMtNzkwQy00NTFDLTgyQkMtQ0I2NjY3MzA4QTAy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QkYwQzBCNjctRURFQy00NjJELTlFNEQtN0RBN0VERjA2RDdD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzQ0NDREMzctQkNFRS00M0QzLTk3QTgtMDRCM0Q5RjFBMTUy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzU0QTZFMEQtNTA2Ni00ODM1LUI5MkYtMzFBNzI0RUNCQ0Uz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RUJFQ0ZENjQtODlFQi00MTQwLThEMTAtMkNGRjRDNjU4RjY4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RkQ3RjUyNDItNzlCMi00MDgzLTg4QzAtMzE0MDIzMEYxRTRC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/M0VDNThEQzYtQUUxQS00QUM2LTlDMTYtNjE4NzE4MTQ5NENG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDIzMjE1OEMtRUNENC00NkRBLThFMkYtN0U1NUJBOTYwMDk0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MEUxNkUwOTktRjI5Qi00NEY5LUIwMjAtMjFEMTk0OUE1RDNB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTdENzc4Q0UtNTFERC00QjA4LTg0NzItODUyMzMwMTA3MjA0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjE1RUJGQzYtNzEyRC00OUNELTk5MzktRjYxQkVDN0YzQjk2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/N0Q4QUQ1NjQtOUJDRi00RUNCLTk4RkEtN0E4RkVGNEY3OUVB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTBDQTdFOUMtNkFGNC00NDc3LTgzOTktMjJCQ0NBN0RDODIy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTEyMTM5MTctMzhEOC00NjQwLUFBOUUtNjAwMjlGMDJGNjI4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTZDQTcwQjctRDNCQi00Q0NCLTkwNkUtRjkxOUJBNDg3M0I2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkZFRUY2MTgtQzk1QS00RjNGLUIwRkItQ0U0RDY1OUMzN0E0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzMwMEY4RDEtQkNGOS00NDcyLTlCMUEtRUU3OUE4RDcyMTIw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzRCQjhBREQtMEM5RC00QUYwLUJCRjMtODM4NDFDN0IzNTND",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Nzk3MURDRDAtNTRBRC00NjQ4LUI4RUItQkExRDYwMUJDRDQ2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QUQ0QjZDODYtOTMxNy00QURGLUE0QTMtNThFRDI1Nzk4QUU0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QUQ1QUE0RkEtOTY1My00REQwLUE2NjQtRjdEODZEODE0MTNG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDBGRkYxMkItNjM3NC00NDIzLUJDODAtODdDMUM3ODVENTNE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTA1ODAwNkYtNTlBMi00RkU2LUIxNTktREQxMjFCN0U0NENG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTM5MjM0M0YtOTgwQy00ODc2LTgyREYtRENFRDAxQkFCNDU0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTU4OTNBRjgtNDkyRS00OTk1LTg1NEQtNEU2RUYzRUU0QTc2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTY1QzcyMDQtQTg3Mi00NjE3LUE5QjItNjgzRDUwQkE4MjBB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MEI5MUY4NEMtRjk4My00NTc1LUFDM0QtNUNENzRCNzBGRDY1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MUJBNEI0OTEtMzlDRi00QzJELThCNDctRTlFNjI0MkIwMDFC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjA2M0I5MDktRkNFMC00MzA2LUI5RjMtRkI5MjQ5OUYxQjM0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MkNDQjE5MDEtQTVFRi00QkUwLUJEQjItMkNDRjE5NzVDM0Ex",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MkRGNDZDQTItNTNGRS00NDlDLTlDMTQtMDUxMzVDNEFCNDIz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzlBNDUyNDAtN0U3MC00ODUxLTg4MjYtNTc3QUU3QzgzQzAw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/N0QyNTU0RTktNDI4NS00NDBDLThEMjItMDI0NjczQzI4MTM2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDA5RTM4MzMtODgyMC00RUFDLTg0NDQtRDI5MTA5MTBFNTIx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTgwNDFBNDgtQ0U4OS00Nzg1LUI4NTMtQjgxQjdDNDVBMDI2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NUE3RkMyQjUtNDYwRi00REI4LUI3QzYtOUFGNUI4RDExOUEz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkM4MjdBQjQtMjhDMi00Njc5LUIyMDAtOEE5MjFBODNFQjY2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzA4QTI1NzYtOTBGMC00QzIwLUI4RDQtMzBFNUZCRTIyQkI3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzAwNDQxNEMtQUY3Mi00ODEzLTg0MEEtMjQ4RkNDQkVFQUVG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODI3Q0RBMEEtMEExQi00QjZBLUExMDctRDk2MjAzRTU5NTc1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTI3MTcyMTgtMTBEQy00NDBELTkxOTYtQTYxRkQ4RDAyNTk1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTY2RkJGODktOEU1MS00OTlGLUI5OUItNzg0NjRBQkJEN0Y5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjUxRkM5RDUtRTYxMy00MDZBLThEODgtMjdBQTM5Q0Q1M0Qw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzE4OEU3RDktMEJDQS00RTNELTlDQ0MtOTM1MjREMDIxNTQw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDhGMUYyMkQtQ0MwNy00N0YyLTg4MUQtRjJCQTBDMDdCNjg5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/REIzOTI4Q0MtRkM2NS00M0IyLTlFNzItRTZEMDZGRTk1RDgz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDJDRTc0OEYtQ0Q3RC00MEQ3LUIxQjItMDJEQ0Q5NDA3NTQx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDQ5QkM2MEItODg5MS00NTcyLUI1MEMtMkUzRjQ0NUI4QTFC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDlBQ0VEQTAtQjVGNC00MkJGLTlGNzktOUQ4RTU3Q0FGN0Q3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTNDNzE5OTAtMUI1Qy00QThDLUE5REMtMjI2MzdDNTZDQUQy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MThGMjlCRTEtMkM1MS00RDMyLUE0MkUtNUQyNzY4MDRDMzIw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Mjk3ODMyOTMtNDkyMC00RDQ1LTlBM0YtNEEyODc5RTMyREVF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzQ4MDNGQUYtRkJCNi00Qjk1LTg3OTAtMUVFMDdGMzNCQjQ0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Mzc0NDk1MDItQkQzNC00OUM3LTg5NDAtOEEyNUVDMEUzNEJF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NEZBMDM5RDgtOEQ0Qi00N0VGLUFGQzktODM3NDYwQjI0RThE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkJGMDEwOUMtRTM5QS00Q0IzLTg1MUUtRDQzOTZBMEUyREMz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Nzg3NkI5MTktRDIzRC00MTI0LUIwQzAtMDAwRDBDNzczREJE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OEY5MjgwNjctNjFDNC00NzE1LTlDNjItNEY1NTkzOURCQ0VE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTBDM0Y0MDEtMUIzMC00NUQ0LUE5MUYtQkI4ODY4QTY5RUJD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTJBQkQ0NEMtRDBDQy00Q0FBLTkxNTktMkFBMTQ4ODREQ0VF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUVBM0YzNkEtMTRCNC00M0Q1LUFGQkYtNTI5RTQzOUFGRkVE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjU1QUJFMTktNUNGQi00QjU0LTkxN0UtMzg0MDE5OEJDODBE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QkYzMjg2NTItNDg5Qy00REMyLTk4MEYtQUUxRjlFREY2NzQw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDE0QjY4QTEtNDg1Ny00QzIyLThERjMtREYyQzc1Nzg3MkM3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTJFQjREQTEtNkVBOS00Q0MzLTg0MzAtQTI1NkIyQUZCMDZF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjFDMkE0OTktRjRCOS00OTVGLUEyMjAtM0FDODFEODg3MzJF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDY0QjZDREEtQTVDNC00MzMyLTg4NDYtQzExODM0OTZGMEQz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTA5QTdBMzYtQjM1OC00QjJFLTlDRkItNjdBQkFDNEM1MTYx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTkwN0NDQzUtREZGMy00RjMzLUI3RTAtMDI1QzhBNkI3Q0E3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MUI3MDU2MjQtNDRGMC00RUM1LUJEOTctQzRDMzZDQzNCQjUy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MUZFNEM1NkItODEzQS00QUIwLThCOUEtMUQzMkZBNTZENTcz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzY4MjEyNEMtOTA2QS00RDY0LUE3RTItNTg4NzEwQ0M1REI3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDBENUQ3NDUtMzI0RS00QjZELTlDNTAtMkZBOUY0MEY5QkEw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDcxNTA5QjQtODAzMy00RTBGLTg1NjItMzQ0QzNDRkUwQkQy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjFFODEyNTAtOEI0My00M0RELUEwODMtRjk0Njg3QUJDM0VG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODQ1NjY3QzgtODg3RS00NTRBLUIyM0ItMDc0Qjk1M0IxRUQx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODYwNjE0QTAtMTc4Mi00Njc1LTg2NzItQjFCQkE1RDc1QzlB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTFCREZGNTMtMDY2RS00M0VFLUI4QzYtNzZEMTc4NERCRTIx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTI5MDVBQkUtMzI3NS00QkQyLUIyRDYtQTVEQzEyNjc2QTVE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTdBNEIzNjItMTRCRS00QzRBLUFBRDAtQURFNDE3RTE4NkU4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUNGNjlCM0ItRkY0QS00QjJFLTlFOTYtMjJERkUyMUI0MDkw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTRGMjlCQzAtQ0I5QS00REQ2LThCM0ItODhGN0M2MUEyMUI3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Qjk1RjlCNEYtQjYxNi00QzgyLTlDRDUtQjc1NTcxNTZCRTVB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QkQxQkQzQUQtNkM1OS00OTA0LTkwNzUtRkE4RkE5Mjk4ODk4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDhCRkQ5NjctQ0Y0QS00RjcxLUFCMEItNjdBNkFCMjM3MkJD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RkRDOTAyMUEtRjlCNS00RjNELThBRDMtMUYwQzFDQjMxRTlB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MEE0QjJCNDgtRThFRC00MEJDLTgyRDYtMTZGQTNFMzc4OTVE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MERGQjhBQjctOUYxQi00QjAzLTk0MjYtOEU4Q0U0MjI2NDEz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDM4RTI4NzItRTkwMC00MTI5LTgyN0EtMEY2MDExMjMxNzlG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTAzQ0E1NjAtQTgzOS00MkIwLTg5RUYtQjczMEU1MUM2NTIy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTQ3MjdBQjktM0U4NC00QkU3LUIyQzctMDAzOEIwOEI4OTYz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NUE0Q0I4MEMtRjNBRS00MjQ3LTgxRDEtMzZDNjVEMUY4MjQw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODY3RjY1MzItMTY2RS00QTFDLThEMkMtRjFFNkREMzc3Q0Iz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODhFQUYzMDMtQjhFMi00QkJBLTlENDktMTc3RDdDNjEwRjVD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OENFMzEyMjItMTI5NS00NEI3LUE2NkMtM0Y1NDU1OEUyNTMy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUJCQzI1MkYtNjBDRC00ODAwLThENUItMDA2QTIzMzM4QzFF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTFBRUNDMTktQjczOC00RTVELUIzRkUtOUUxRTZGOEJFMDA5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTM5QTY5QzMtNDI4MC00QjIyLTg0OTgtNjk2MUE0QjEyOENC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTg4RDZBRUMtMTdGQS00NUQ3LTgzQjktNzAzMTg2NzhCQzZB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTk3RERBQ0ItOTdFRS00NTZCLUFEMzItRTdGODU1RjFGMzM5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjA0ODVDNDUtMDAyMi00Mzg4LUE2RjgtQkFBOUY2MzU4QjNE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Qjk0MDBGQkUtNTg1Ri00QkE5LTlFOUEtRjIyNDM2RDNDMzBE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QkYzNTcxODctQjVCMi00NkNGLUI3RjctQzQ2ODc1M0NGQUIy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDc3MUVGREEtMTMzRS00QjA1LUI5MUQtRDFGMUExMUFCNkM4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTI3QUJGQjktMTM5Ni00RERDLUIyNDAtNENFMUFGMDIxRjJF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjhEQzkzRjktN0NBRS00NEYwLUI5MjItNERFRTVCNjA4MEFD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/M0Q3MzU2REEtMEM0MC00QTUyLTg1QkQtMkYyNTA2NjIyMUVD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/M0UxNUU4RDAtODA4Ny00RDY3LUJENDQtMEU5MDkxNjg5ODE2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDdEODcwNjYtOEY4QS00MUQ4LUJFQUUtQUQxREI2QzNDMEZG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDlCQTVFNkUtNzkyNC00ODFGLUE5NTYtMDAzMDFBQjRDNEI0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MEEzRkVERTAtNzNFNy00NUI0LUJEMkItNTFBQUJEN0FDOTZD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Mjc3NTJDNzAtMTdFMS00REQ0LTg5NzMtMjVCNEM0NDdCQTg4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzlBMEE5MjctNDQ4My00RDlDLUExMjctREY0OEY4QjUzNkUz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTUyNTQ5RUQtQURGNi00QTQ5LUE4Q0MtMzVCRDUxNzY3MTZC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTVCOTY4QjQtMTFFMS00QUUyLUExODQtNTcwRjIwRTQxNThG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjNERDg4QUItRTg2RC00RDQyLTg4RTEtQjkwMjlEQUE1ODhG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjQ4RERGRjMtMjExOC00Q0FGLUJGM0QtNTlEN0VFNzlENDgx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkEwNUJBOEUtRjcwMi00NjcyLUI5MTgtNERCRUM2RkI2OUM0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkQ0NzlDOTAtM0Y5Mi00NTQ4LUFCRkItQjk5QjQ2REMzNkE0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzI3NENDRkMtMjY5OC00NkI4LUIxMjktMjdCN0I4RDA4Njgw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OEJGQTYyMTgtMkI4Mi00QTMyLTkwNUItQkJFOUNEODNDMDY3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTk0OTZFRjYtRThFQS00NkRDLTkyQTktQzg5NTE2RDgxREJF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTg3M0NCQUQtNjlFNS00Qzk0LTg4MkYtRDlFM0JBQzEyOTBB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RUJGMUZDOUUtOUJBMS00NEE3LTk3QTUtQkQwOEMxOUNGQzVB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjRBMjI4Q0EtOTk5My00ODQ0LTg5N0EtQTdFRjY0QzQ2OTJF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RkE4NUFERDUtNEVDQi00RTQ5LTgxMDEtQTAyOUM3OEUzRDU1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDVGRjg1M0MtQThFQy00RDVGLTlCRkYtMzMyMDY2RDJBQkRE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDkzMjlFM0UtQzMzRC00RTUyLTk1REEtRTZBODIxQ0YyQkVF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTdBMzc3RTAtMDFCNC00MDlDLTk2NzgtNDg2QjY1OEU1MjFB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MUY1NkEzRjgtQTc4QS00OUQyLTlCRTUtNzEyMTk1MDJEOTc5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjVERkE0NDQtRjlCQS00RDNFLTg0M0QtMUU4NkYxMzNDMzky",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzNFRDk2MjgtNDI3NC00NkNDLTgzOTItRUIyNTBBQTEzMDBF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NERGMEUzMzYtM0VCRS00M0FFLTkxNEItODFFNjkxQjBDRjNF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTIwREQ1MEYtRDkyRi00Mjk4LThBNkYtMEU3MDIzMjM5QTU3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjNDMDgyRjUtMjU4Qi00MzU3LTlEMUUtOUM5NUVFNkNDMEM2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Njc5QzNFNzYtNjZGMS00NDg5LUFBQzYtQjNEMEM3NzUzNjU2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkI2QTQ5NTctRTYwQi00QzdELTk5MDgtOTUwNzEwMzVERDJE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTc5MTI1OUItQTIwNS00MDkzLTkyRDgtODczNEFDMjc2MENB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTdENzE5QzAtMzZEOC00RDEzLThFNDgtOEU5NEU0OTEzNDEy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RERBMUE5MUEtMDE5OC00MDNCLTlBNzAtN0YwMzhBQjQxN0Uz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/REYyREM0NjItMEI4Qi00RDBCLThFQjYtODM1MTMyNTJFMDQ1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTlFRTlCNTUtNzc2Ni00RTMxLUIxM0UtMTZDRjBGRTlDNTI2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjMwMzM2RjAtRTE1OC00OTY0LTg0RDQtNkE0RkY1QjQ1QzUz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjY0QzY0QzItMzg3OC00QTc5LUJBNzMtOTM1RTQwMTUyNEJE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjZGNzU0M0ItMjg0NC00MDE4LUE3REItQkU0NkQyRDlDNjAy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RkMwRUEyODEtQzZGNy00NzVBLUI2MjQtOTZCMkE0RjE2NjEx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDgwMjNDREYtOEE5RC00MEFFLUEyNzctQUY1Qjg3QUE0Q0JE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTVFMTQ1NUUtQTMyQi00RjlELTg3MEUtODY2RkQ0NEM3NjdE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTc2RDk0OUUtQTRBMS00NDZDLUExRUQtQzA3MzMxQkZGQzI1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjRCNjdDRTgtRDIyQS00RDM5LUI2RUEtMjVGRjE0RkM1MUI3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjcwRTdCNjItNzUzRS00RDkxLThBNDktMDYyNEFCOEZBMkM0"
       );
function bacaHTML($url)
{
    // inisialisasi CURL
    $data = curl_init();
    // setting CURL
    curl_setopt($data, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($data, CURLOPT_URL, $url);
    // menjalankan CURL untuk membaca isi file
    $hasil = curl_exec($data);
    curl_close($data);
    return $hasil;
}

echo "No : Nama PT : Alamat : Kota/Kabupaten : Kode Pos : Telepon : Faximile : Email<br>";

for($x=0; $x<=304; $x++)
{
    $kodeHTML = bacaHTML($html[$x]);

    $namaPTN = explode("<td class='tright'>Perguruan Tinggi</td>", $kodeHTML);
    $namaPTN1 = explode("<td class='tright'>Tanggal Berdiri</td>", $namaPTN[1]);

    $alamatPTN = explode("<td class='tright'>Alamat</td>",$kodeHTML);
    $alamatPTN1 = explode("<td class='tright'>Kota/Kabupaten</td>",$alamatPTN[1]);

    $kotaPTN = explode("<td class='tright'>Kota/Kabupaten</td>",$kodeHTML);
    $kotaPTN1 = explode("<td class='tright'>Kode Pos</td>",$kotaPTN[1]);

    $kodeposPTN = explode("<td class='tright'>Kode Pos</td>",$kodeHTML);
    $kodeposPTN1 = explode("<td class='tright'>Telepon</td>",$kodeposPTN[1]);

    $teleponPTN = explode("<td class='tright'>Telepon</td>",$kodeHTML);
    $teleponPTN1 = explode("<td class='tright'>Faximile</td>",$teleponPTN[1]);

    $faxPTN = explode("<td class='tright'>Faximile</td>",$kodeHTML);
    $faxPTN1 = explode("<td class='tright'>Email</td>",$faxPTN[1]);

    $emailPTN= explode("<td class='tright'>Email</td>",$kodeHTML);
    $emailPTN1= explode("<td class='tright'>Website</td>",$emailPTN[1]);

    echo $x+1;
    echo $namaPTN1[0];
    echo $alamatPTN1[0];
    echo $kotaPTN1[0];
    echo $kodeposPTN1[0];
    echo $teleponPTN1[0];
    echo $faxPTN1[0];
    echo $emailPTN1[0];
    echo "<br>";

}

?>
