<?php
$html= array(
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDlFRDU0MDEtRDM3OC00RjEwLUJGRDMtMTNGNTg3MDc0RTUz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTEwNjBBMDUtNURGRi00QzAzLUE0MjktMzc1MUI4OTAzOEVG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTEzQjREMDYtMzRDQS00QTZFLUEyOUEtOUFGMzcyOTMzQzhG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MUQ1MUM0RjUtRTU4My00RTJGLUJERTUtMDRGRkNGOEQ2MzRB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjY1MEJFRjQtMzEyQi00NDM3LUJBMjAtQ0I2NTU2Q0Y1NEU5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzM0MUFFMzItNEFCNi00QTJBLUE3OTktQUFFMUQ0QkY5N0Q2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/N0NDQUFCNTgtNzIzNS00NEZBLUE1RTgtRTI1NTA0QTgxNjA1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDNGMEM0OTctNEQzMS00NjM1LUE1MjEtRkY2QkI1OENBQzFE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTMxQTgwMDQtOENDMy00QUU1LUIwNEYtMkJFNkE5NkI4MzY5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NUM1MEIxNEQtN0VBMC00QzBELUEzRTAtOEQ0QzdGNTAyNEY4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkU1RENCMjUtNUU5Qi00QUM1LUE1MUYtRDhEMkQyRERCQTFG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODA1ODYyODctODIwRi00MTRGLUE5RTItODdEMEQ4MjEwNkE3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODA5QzhBODEtNEIzMy00REQyLUFGQzEtODU4MjBCQzhGNzhE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODcyOTI4MDUtQ0U4RC00NzdELTg5NTAtRTJFNjZGODkzRTlD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0U4NUIzQTYtNTIwNS00QjlCLTg1N0YtQThBNkQ3NzcwRDlE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTVCMDQ4MTAtQTNCNy00NUY3LTk0QTYtNjRBMDNBMDFBMDcw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QkVCMDk2NjMtQjYyQy00MTFCLThFRDctMDBBMjc3QjE5MzJD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RUVFODY3Q0QtMTY1NS00RkZCLTlCMzQtNDNBMkE2ODAyNkJE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjBCQTY0RjctRDJGRS00RjQ2LUI4QUMtRERCNUYzMTBGQjU1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RkUzMDEyMzktODZGOS00MTFDLThEMUQtNjU3NTY2QUVGQUMy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MEJDRTREQjctQjIwNy00NDVELThEMDMtMEM1NEI3Njg4MjUy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MUE0QjJERUItNTE5RC00RTI3LTgxRUYtNDM1QzNCQjY2MUQ3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MkZERTgzMTgtNTI3MC00ODY0LUJCNkItRDkyOEYyMDlFNjND",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzYwQzFFRjYtNkFEQy00MDgzLTgzODMtMEVBMUY0MUE1RERD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzZDMzdFNzItRTFBNC00MTdCLTg2RkUtMkMzNUIxQThGNzUw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NEE1Q0NCREItMERBNS00QkJDLTk5REUtNDlDNjY2NkI5MTIx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkM5MTc1NUUtNTBFNS00QUNGLUI0NTQtMzdBMDU4QkE5QkNC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzgzRUQ3N0EtQUEwQy00ODYwLTkyNUMtOTJEQkYyNTFCM0JD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTQ2MThCRDQtQ0U4NC00NTE0LTlEQTctN0VEMEIzMEFFRTNC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0E1OTI5MkYtRUJCRi00QTk4LTk5M0ItNjEyQTFEQTYwQTgy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0I4NDRGODYtNEZFRS00QzBELTk1NzItMUQyNjZFQTM5MEMy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0U3QzI0MEMtNUNDNi00MDlFLTlGNjktQkQ2OTM3MTQ1Rjk0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTJGODMzMEUtRUU3Qy00RjI1LUE2MUItOTg3QUJGMjE5NEEw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QUM2NzAwMEItMEMxRi00NjRGLTlDOTEtRTZFODc1Nzk0RUM4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Qzg4MkIyNDMtNzYwNS00MkQ2LTlBRkEtQTJDOEQ1NkQwOUVE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDAzODMzNjItRjQ5Ni00MzA1LUFBRDItMDQ4NzcwNjUwOTIw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDYxNjAwMjYtNDFBRC00QkZELTkxNEUtRjlCMzNEQjVBMzFB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/REQ2RkMyM0YtN0I4OC00QzE5LTk4NDAtRjcyNjkzMTgwNDZE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTJENUUyQ0YtQkY5OC00Q0RFLThFMjEtNzA0NEY0NDhEQ0FE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjM2MDdFRDMtQTc0RC00RDdDLThEMzItOEU5OTg0Q0EwNDg1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDcxNjYzODYtQ0NERi00ODNGLUJCOTYtNzMyQTE5NUMzOTlG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MEY2QjA4MUItMUJGOS00NzgyLUFBM0YtMjQwMjE2QkM3RDU1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTA3NjM2NkQtOUIwRC00Q0Y2LTlERTYtRUZDMDc5NUMxQzIx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTFDRjg2MUYtNDEzOC00QTc5LTk3OTMtOEYzNDFEMEY0OTAw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTdBOTVCQkItMjE0RS00NkM1LTkyNEEtQTNEMEVDMTc2Q0Qx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTg1MEM5MkYtNjg5Qy00NUU0LTkzODItMDEyMTlEMzVDNTM0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MUMyQ0EzQzItNDhEMS00NDU5LTg4QTYtOUJFNEQzMEE3N0FG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MkU5MUQzOEUtODc2Mi00MTRFLTgyODMtM0MwN0IyODkxRkVD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MkVDRjVENzYtOTM5OC00MzU0LTg1QUItRTRFQUYwRkY0NzAz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NThBNEFBNzYtMjBEMS00MEIxLUJFMjAtRjYxMzNDQTAzOUIz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODA1MjUxRTItRDlEOC00MTNDLUFCRTktQjQwN0Q0RDVBNTcy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODI2MjFGQTUtQUQ3RS00Q0QxLTgyMkEtNENFMkQ4NkNGOEQw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QUJFNkFENjUtRkFCMC00RTkxLTg0MjAtQjk3NkRGMUE1Mjg1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QUU4MDdBRkMtQzQyQi00NjBFLUJFM0ItRkFGQkUwQUM4RjBC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QUVENzVGQzItNEM3OS00QzMwLTgzNDgtOTFDMDYyOEYxMzJC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QkUzNzhDRTgtNjE5NC00MEE4LUJFRUYtMTNDQkYyRjk4ODcw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzM1QkQ1ODMtNUY0Ni00QzY2LUE5OUYtMkMxRUJGNDBGRkU4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDEwQTA4MTMtRUJCQy00NzA1LTgwREUtOTJBQjQ3NUVDOEFF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDRFQkZBODgtOUUyQi00RURBLThBQUQtRjcyNEY3MzU5ODU4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RkM0OTE1OUUtQTVDNy00QkUyLUIxRjktNTg1RDQwNzNFODhC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/M0QzQkU2MDUtM0UwMC00NEEyLUEyRTYtQzUyM0IwOURFMjEy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MEFBMjA1NTMtNjY5Ny00M0Q5LThGNjUtOEE0NEFBRjJBNTQ5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjFFNDYwRkUtMzI3RS00MEUzLThCMDYtNUFEQkNFOUE3MTZB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjdBMEUwNzEtNEUzQy00NDJGLThGN0QtNjJCQTQ5MjZENUVC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MkQyQjA5MTMtMzc5Qi00OTA5LUIzNzgtOEUwRDM2NTFCMEE4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTI4ODBCRUUtMDY1NC00NkUzLTk3MjgtNjc0MjZCQTVDM0I0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTMyNkU1N0EtNUU5Qy00MDQ0LUFDOUEtN0E0MkE5ODhEN0Iy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTMzRTYxMDctNThENy00QzM2LTkwMjAtMDc2QkZBMjk1RDE0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjdERTYxRTItMDY0RS00QkEyLUI2MTYtNkUwNDcxMTRBNjNF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkU2OEZGNzYtNEUwQS00QzFCLTk2MjgtMjk2MzNDMTRGMzlC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OEUwODEyQTMtRDhBNi00MTBGLTg1QzEtQ0Q2Qjc3ODREMEY4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTRBMkUzOUMtMTQ2NC00N0RBLTk5NzctNTk5NzFFNTY1NEVD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OThCNzY0REUtQ0ZGRC00QTBFLTlFN0EtMUI3RjZBODI1MTZF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTE5RkFEMzAtNjY2QS00NjBCLThEREQtQkM5NjQxQjZFMEU2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTVBRkJCREUtN0ZGRS00MkVGLUEwQjctMkI0NEFFQ0YzQkMy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Qzk5NDk0MzgtOTMxRS00QTQ1LUJEQ0QtMEFBQUM4NDY0NUIx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/REUyQTIxRkMtODE4Mi00QThGLTgwRDEtMTExRTNDN0I0MENG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/REY4MUVCQTYtOTZBRC00RjlDLUJEQjUtMzIyNUI5MkM5QTU0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RUQ2RTY2MTgtMDExOS00OTRDLUIwRTktQjNGNkQ5NEJBRDYx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Rjk0MkVEODUtRTUzRi00RjFDLUIwREUtQjNEOTYwQkQ1NTRC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/M0EyN0FBRDgtQUI3QS00RjgxLUFFOTAtOTUxOUUxOUI3MTFD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDg2NkUxRkMtM0E0QS00MjE0LUI0MDAtQTNGNTc5NjIxREU0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MEU4Mzg5RDYtN0Q2Qi00OTEyLThFNzctQUFFNzZFMzRCQTY2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTg1RTkwMTQtODQwRi00REJELUJFRjUtNUI4NkRGREY1NDU4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MkE1M0VGMzEtQkE3MS00OUJFLUJCNUYtQzAxMjk1RDdEQTdB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzdGRTM3QkYtMUU5Qy00M0UzLUIzNUQtOTdCQkRENUM4NkQ4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDI1QjA4QkMtMzc5RC00NkYwLTkwMEYtRTc3QTRFRTZFMDEw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTEzRURGMDktOTVBMC00NkU4LUJDRDItNkRCQTM4MDNGMjkw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTdENkJGQzEtMEJFNi00QjZBLUJEQTItQ0I5ODk1RkI2Njkz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkFBQjNFNjEtRjgyNC00NzA2LUI3Q0EtNkE3RjU5QkY3NkUz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODA4MzNBOUUtREY4Ny00OTFELTg3NTYtRjNEM0ZGMTk0RjlE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OEE2MkFFRTItRTc2Ni00NkI1LUI2RkUtMTAxNzdERkM0OTdD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUQ1NkMxQUMtMUY2QS00NUEzLUJERjAtQTJENTA1NTc1N0FG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTgwMkM5MjItQzVGMS00ODc3LUEwMkItRTMwOEI2RERCMjQ4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QUY1OUQ0OUEtODYxRS00QTJGLUE4QzItMTMyQzMxQTcxOEUw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjFFNDAwNkItRTlEOS00NzdDLThGMDktQkUyMjg3NTM1MkNB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjlFNzMxMjUtQ0RGMy00N0E1LTg1RjYtRDU2RDlFRkNFRTlD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/REI4MTg3RTItRENBQi00NEFFLUJGRUUtRDkyOUY4NTkxOTMw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RENCOEY4MjUtN0M4Ni00NDdELUE5MUMtNkNERTMwQTFCNDcw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjAxNTAxNkYtNzg0Mi00NjQ1LTg5NjUtQjBFNDUxMjRCNDhF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDk3RTUyMDUtODRCNy00QUZCLUFENkMtQzVCNTBDNUVBMDYw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTQzODdFRTktQTkwRS00NjVBLUFEODUtMDVENEQ1ODhCMTM5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Mjk0NTdERDgtOTFFNi00MDY0LTk5OTctNkEzODIyRUEzNkUx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzA3M0JEQjMtQ0Q0Qi00N0ZGLUJGMjctREU2MkZCM0U3RkND",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzFGNzM4M0YtMzQwNS00MEZFLUFDMDctQjg1NjM0RjI4QkZC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzZBNTk1MjgtMDkzOS00MEM4LUE5M0EtMDc3Mzk2OTI5NzE1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkQ3RTA2MEMtRTlFMC00NTk4LTkyMjEtOTVDMTVEQUE4QUM5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzY1NDgzMTEtREJCMS00QTE3LUFEMDItNDYyM0E5QzEwNEZD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODhBRjJBQkYtMDY1NC00MzRDLUFBMkEtOTBBNjNCQTAyOTk5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUU5ODg5RUMtNEU1Ni00NEE1LUFGMkYtRUM2NDMzNzg1Mjcy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0YxQTIxMDktNjk2MS00MkUzLTlDREYtRTNBOTIwRDRDREVD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTJDQzgyQjctMTBBQS00RUM2LUE0QzUtMzhFQUIyRkNBQTdB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjA2OEVDRTEtRkM2RC00MUEzLTkyNUUtOTlCN0ZGMDk1NDYw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjBCN0M3MjAtMjJFMi00RjQ5LUIzQUItRDFGM0RBNDUzRTIw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjI1NzA1RDktMzk3NS00RkFCLTlBMUUtRDBBRkU4N0UxRTUx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzIyMTRERUQtQTkyQi00RUU1LTk4MjMtQzlDM0U5OTk4RDE1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzREM0Q2MDItNjA4OC00RUFGLTk4RTAtQ0VGQjg3QzRGNkM4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDUyOTYxMDMtMjhERS00QUExLUJCNkQtMjcyQkI2Qzg4RTQ1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/REJFMDY3NEYtOUY2Ny00MzNCLTkxMDItOTkwRDBBQUQzRkI5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjVEM0Y1NzYtNzcxMS00MUU5LUExN0ItRjhBQTM1NzEzQkU0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDg0NkMyNjQtOEM0OC00MkMzLTk0MTEtM0JBQjI2RjIxQzAw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjRBMTUyNUYtNEUxRi00OEQyLUI2QUItNzQyRDI2MzRCMjdC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjU2M0REMjEtMEJBMi00QkE5LUJDN0YtNEU2NTlGMzJCNjVB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzBGOEI0MTYtNTM5RC00MDNCLUFFNTYtNTAxRDhFMzEyMzEz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzFEOTQ2QTAtOTIyRS00OTZFLUFFOUYtQUNBRUVEQTYyNUNC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NEM4REY4MEUtQjdEQi00MDgyLTgyMzEtOTRDMDJGOUY0RDhG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjAzRjE2NDktRkVBMy00QTdBLTg1N0QtMkNERDEyRTcyNjgx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjdCOTI1NTktOTMzMS00QUE1LThGOEEtNzFFNzlFOTIzNTMy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzA3QzM4OTUtQjU0Ni00REE1LUE2QTctRUZFNzQ2MUE3QzdF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODI2RTY4NDItMUQ5Qi00RjlCLUI4ODQtQzQ1MDJCMUU5QjdC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODJDODJBOTUtOUZDMi00RDM4LUEwRTQtRDRENkVDNzZGRjlE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODk5M0YxRUItNjlCNi00QTc3LUFCOUEtMzM4ODY5MkYwQTEy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OEY1RTI3OTItRjUzNC00MTgyLThFMzAtMkJCNDQ1NjA0ODMw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTFFNzkzREQtMzg3OC00NzZCLThFQTItQzlENjA2N0U3QkI3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTZGRDcyN0QtM0UxMi00OTY1LUFCRjMtMTEyMzg1NzlFN0ND",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QUFDNzE3MkMtMkFEMi00QUE3LUEwMzItMDkyQUZCNDhENjcz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjIwMzdFNUMtMTdFNi00OEQyLTlDMDUtRkMzOTBCMTE1REJB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDIzN0YyMEEtOUFFOS00RTk5LUEwOUYtQ0M1RkZFMjNFMkNE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTlDQUUyQTItREZFOS00MDUzLUE4MzQtMTdBMEZCM0EwMTUw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RUJEQjdDMDUtNEZBQy00RDNDLTlGM0EtOTc0QTNEMjBERTJG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/M0Q3RkFFN0ItNEI2Qi00MTAyLTk1NUUtOTA5MjFFQTg0Q0Ey",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDQ4NjA2QTctOTM2QS00QjNGLUFBOTktRTVCOUNEODlFQTFG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MEY3NjkzRUYtRjQxNC00RjRELUE2Q0UtMzM2Mjg2NzhFRTg0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTk4RTc5MEMtMTE3Ni00MEM4LUIxNTktM0YzOEVGNkI3RjEy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MkU1RkQyRkEtMUE4My00OURELUJGMjQtN0E5N0Q2Nzc2QTFD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDQ0NzBGMjUtREQ0MS00NTQzLUE2NTMtMjA3N0RGQzI4MTIy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDVCOUNENzMtODZDQy00MkE2LUJCNDctNzZBMUM5ODgxNjE3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NEQyNTNBNjYtNTNGQy00REU1LUIyODgtMkY3QTIyRTA4MDg3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTI5REVFOUUtMTQ4NC00NjNFLTg2RUItRUVCQ0FEQTc4RENB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjlDNTI3NTMtNUJDRC00RkRFLUI5RkUtMUYwNkVGM0ZGMTcz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkZFRjY4N0EtQTQ0QS00NjRBLThBRjAtNjdCNzBEN0FGNkMz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzFDMERGRDktNkM1NC00MkQ0LUJGQkItNjk2NTIyMzlFMUZC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTI2RkQ3NzctNUE5MS00NkUwLTkzNEEtQTVFMjFDNUY1NDhE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0IyQzA5MkYtM0JGQi00NDBELUIzQjUtRTUwQTA2OTlFQkZB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTU0NkM4MTUtRkI0My00QkI1LUI3RDAtNkMwNDhFN0IxNTQ4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTU2NzM5N0UtMDdGNS00RjAyLUI3NjAtRUYwRTBBMkQzMjI1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzQ1MDhFOTctNEYzQS00MUNDLTlDRTQtOENGMUE0MEM1QUU5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzQ1MzZFQkQtMTUyRi00MUNGLTk5NTctRDI4MURBM0UwMzA4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTM5MEFGQTctQ0ExNC00MzNFLUI4MDItQjJEMjk3QUI0MEJE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjdDQkJGMEQtQTIxOC00QzI3LTg2QjUtOENFMzdFMTRDNzkx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDg2NDhGMUMtOUExMS00MDlBLThGNTYtREVGQzQ0N0UzRUEy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MEU3RjZBMjQtN0M2Mi00QkE2LUJEQjQtMkM0MEM3RDZERkE5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MUEyMDFBNDEtNkE1NC00OTA3LUIxRTUtNDFENDU2QzAwRTE3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjA2RTkxMkMtQThFNS00Q0JELTkzRjMtRDVFMkVFMDFFRDhG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTA4NjlDNzctQ0VERC00MUNELThDNDgtRUIwQjdBRUM4Qzcw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkFBN0FBREUtNEZDQS00QzFBLTlFQ0QtNzA1MjQ5NjNDQkRE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkUwN0JDQzctNkMyNS00MEJFLTlBOEItQkExQTg2NTRENjMz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODRENjhFQkYtQzI2OC00ODBGLUIxMDYtOUE2RjdEMzRBMkUy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUYxQjRFMDctMUM2MS00MjUwLUEyQjYtNjgxRjIzNjJEQTQ2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0Y1QUY0RTYtNkRBMC00RjU5LTlDRUQtNDM1Q0E2OEEwREM0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTZGNjNCQjMtOEFBNy00MzMyLUFDMjctQjQzQzcxREIxREZD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjdBQjRDRTQtNEVDMi00MTNELUE5MTYtNDg3MTA1NjEzQzAz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QkIyOEM4RjMtN0M4Ri00RDBBLTgyMUItRDlGNzgyQjc1NzY3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzBCQTEyNDctNjQ1Ni00NUQ4LUE0Q0UtQzBCRkQ0NjkxQ0Qx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzBDNEU1MTItOENEMy00QzFBLUI5NTktOUQ5RjI4QTI1OTcz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzBEQUEzMTEtQkMxNC00M0EwLTk1MUMtQTUzNjYwMDdENDkx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDJFRTYwMkItN0I3Ri00MkQ1LUFDNDAtNkI1MzYyMDQzQUIx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDgxQTY3M0MtMDExNy00NjlGLUI1QzYtNDg1M0I5Rjk5RTNB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Rjk2ODgyQkEtQzNGOC00MjY3LTkxRjEtMDlGMzE1MkMwOTg0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RkFCNDdGMTAtNEQyQS00QkM4LTg5NDMtRjQ0NDdFMjg1NEJC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/M0VCNkNDMjgtMDFDMi00NzQ1LTgzRUUtOTEzNDlBMDYxRkY1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDNDNTE0QjctQzBGOC00Q0FBLUIwODYtRjE3Njg5QjgzMTlF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MEI0QzJGRTgtNTcxNy00Mzg4LTk3OUMtNkRBRTIzNzJFREJG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTVDNTlFN0YtRTg4Ny00RTJBLUE1NEQtODY3RkI5RTREQjhF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MUQ5MTQ2MzEtQTY1OC00MTY1LTkyNzktNUM3QkIxMDg5NDgz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzU3RDRFNjctNEFERS00MDQ3LTg3REMtNDU3NjdGOEY3MTQ3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzY5ODI3RjYtOTI0MS00OUY3LTk4M0EtMDIwMjUyNkFFMzg4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/N0M3RjY3MzItRjU5Ni00OEE3LUFEODQtQ0JBM0U1QUVERkNG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDdDRTgxMjItMjcxMC00QjM0LUIyMTgtOUVBOTNEMjU1MzYx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTQ2QThDOEMtMkI4My00QzQ0LUI1OTMtOENGRDE0MTQ0RTFF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzhGREJGOEUtQjBDRC00OUMyLUI3MTMtRDcwMzM3MzEzNUQz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OERFNUIxRDAtQzQ2Ni00QzlGLUE5MzQtNUExQkU4RTgwNDI4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTJGNDY4NjQtRkQyMS00NDJCLUFEREEtRDYxMzIxQjk5QjA1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTc3QTE3NUEtRUIwRS00QzI2LTg1NUEtMDY2NThDRTYzNDU5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTgzNTkyNDUtMUUyMy00NDk5LTlGQ0YtRUVCRUJDMEM0MjU0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QkU2QzYxMTMtRUVERC00N0ZBLUEyNjgtQzVENUEwNjk3RkUy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTBEMEEwMjctMjUzMC00ODVCLTlBNkQtRTkyOUZDRUQzMzNB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjA3NjkyNjktQURFMi00QkJCLUI2M0MtNUJEQjM2QkUwRUEx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjVDMTk2RDItRDM1QS00QzA1LUJFRUItMjg2MTExRjhGOUYx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RkFEQzJBNzgtM0UwOS00MzM0LTlDQ0YtMjc0RTQzNEI0RDFC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDNFREU4QTktNjJBQS00Q0JFLUEyMkEtQzI4NTRFMzNCRjM2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MEUwODBFNUMtMTRGRi00Nzk5LUEyQkItMzE3RUU3ODYyRDAw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTQ2MDhFODktQUE0Ri00OTVDLThEM0ItODhERjIxNUEwMzA0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTUzNjRFNDQtRUJGNi00NUQ3LThEQUQtNjc3Nzg3NkEyNjFD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MUVFNjVCRTctRDY2Ny00QTdELTgwQzctMzU5QTNGQzM3NDRC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzE1QzUwNzktNEQ2NC00OTU5LTk4ODgtNzdBMTdENTQwNUI4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzU3Mjc2RDgtMkM5Ni00MzdELUE5QzktRDlDMkMzODk0MTBF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDlENTI3MzQtRERCMC00NDg2LTgzOEItMkRBRkZBRjFDOTZC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTFBNTFCNkQtMDg3OS00QzZCLTk5QUItMjVCMTY2OENFOTNE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTJFRkE1NDMtMjA5QS00QjdGLUIxQ0YtNTMwNDNCM0JERTQ1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTNDMUM5OTgtNkYxNS00QUM4LUExQjgtMjQ3OThBNkJBQjg5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkQ5MzI1RTItMkVEMC00Mzc1LUEwRTItQ0NGQzg4ODY3Q0VB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkUxNDMxMUEtREJCOC00REE3LThBQUQtRTg0MkE0RTZDMzM0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODQxNTE3MEQtMjE1My00QkI3LTk4QjUtQTE2Rjc3NjVDODMx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODg3QzU3MjYtRDRGRS00MTRCLTk2NzAtMDA0QjU5OEEzMDkz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OThGMDczQjAtMjZGMi00RDdGLUE0QjItRTc4NUVGQThBRkYz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0UyQzU3MUYtNkNGMS00NDFFLTk2ODctMDM3NTIzMTc3QjMy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QkE5MUIwRjAtODVCMi00Njc0LUE3RTItNjA2Q0U1MzRBMTBD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTNBMzQ4ODUtOTJCNS00QkZCLTlBN0UtNDY5Njk0MTk0Q0U5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RkE2MUUzQjEtOENCNy00NjNDLTg5OEQtNUQ3MEZERkE1NDMz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDA2QzAzMzMtRjg5OS00N0M0LUEyODktMDdBMkRGOURCRjgy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDc4RjYwQjAtM0NCNS00QkU1LUFBMUYtNzM0RDk2MzA3ODk5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTk0RDM0MzYtNjczRS00ODc3LUEzMzYtOTFBRTA2RkZFQUU1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjlDRDMzQ0EtMkY2Qy00NEZFLTg5QTYtNzQ3N0VFOEJCQUNC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzNERUM4MDUtMzI3MC00REVELTg5RDYtQUNBOEQxRDM4QkNF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/N0M4NTY5OTktNkJGRC00NjVCLTlFRjUtOTNCNzM4QjY3NTU4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDFFMjFDRDQtNTBDRS00QUQ5LUI5NkYtQjVEQjA2NTQ5ODZD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDVFOTczMDMtNDNFQy00QkMzLTk3NEUtOURDNENGQzg1MkQ1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NEE3NkQ1NEQtRkQ2OS00OEI1LUIyQ0YtRTFFQzZEMTI5MDFF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTIxNkZGREQtMzcxMi00NEU5LTg0MTQtMEZCMEZEQjlENzlD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTlCN0M0N0MtODNFQi00Njg0LUIyREYtMEZCOTNDODkyQ0VC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkUxMDYyQzMtNTg4RC00QkFELTg3QkUtNDQwRjY1NUZGMDdE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTA4REYxRTktRjRCNS00MjdFLUE3MEYtRkI5NjlDNTZFMTA2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTlCNUJDMDAtMERBNy00NjY5LTk5QTItNTA3OTExRjkxRDZB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTRBQzZEQ0EtOEJFQy00QkM5LTgzMUEtOEQyQzQ3MDM5MzlG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QkFBOTg0MDEtNzAxQy00NDk5LUJCRTItRkI3QzBFOEI1RjFE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzZDQjg1MEYtQzg4NC00MzgzLUJCNUMtQjU2MkIxREI2RDZE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/REYyN0I4MjUtMThGQi00M0U0LUE2NTctREQ0QjMwOTFCQzQz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTYyNjA0RDctMzY3RC00MTc4LTg0NTctQ0IyMDNCOTZFMERE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RkE3MUVCQkMtMTlCMy00OUNGLTk4MEEtMTlCRTlBOUJDN0Qw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTFFMTA4QTItQTg4Qi00NkQyLTlFMjktRDZGOEI0MzEzMTIx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTMxMEEzQzItQkJBQy00NjQwLThGNkEtOUY0MzQwMENEMTRD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Mjc5MDE4NzEtRUE2Qy00NUI3LThEMzItNDRFQzVBM0Y4QTdC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzM2RTI0NEItNDcyMC00RkQzLTk4ODEtQTM5MzlFNzAzMkNE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OERFRkFCNjMtMTkyNC00MzdCLUJFQkMtOUREQTkwQzE5MDE3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUFDQjM4NUItQjlDRS00MUI1LThEN0ItMzdBNkZGN0IxRDc4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0NBNEIzQzUtMDVCNi00ODdDLTlEQzctMzRCNjZDQkRGREJE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0Q0NUE4MjgtMDRCRC00Nzg1LUJEN0QtRTdBNkJFNzY5NUU0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTRBRjM5QjktQzc3RS00RTdBLUIyOTQtMjE4OTg0NTU4MjQ2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTkyNzEwREYtRUNCOC00N0FDLTgyMEQtNDhEMThBQ0Q5QTE3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QUM0MURGMkEtODFCOC00OTYzLUJCMTktRjY3NjYzNkNDNDg3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QURGN0RGQUQtNDhBNS00QTQzLUFGMEItREUzNjczNzZFOUY4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjEyQjUzNDctNUU2RS00MTMwLThEN0MtREZGRUJCMTZEMEUy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzIxOURFQjctNUY0NC00MzBDLUE3OEQtMzc3QzBFRDQ2QUIw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDE0MTJENTEtODk4Ni00ODY5LUI1RTgtODNDMjlCNzkxMERF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTYyQzVGMDItNzQyRS00QTQ1LThBMjUtRUFENEYyRDJFNzEx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RUFGN0ZDNUMtMjUzMi00OEEyLThEQ0MtODU1QTM0NjIxNDFD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjRDRUFFNEYtMUQ0OS00M0Y1LTgzOEEtQUQ1Q0JCRTU4RDcz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjdBNjA3NTgtRjNFRC00RUFELUI3NkYtMEU3QjcwMkU3RDU3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjhFMzczNzYtQ0FGMC00Mjc5LUIyRDctQUE2RDY1QjMwMTk2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/M0YyQTI2Q0MtOUMwNy00NDkwLUEyNDYtN0Q4OTNDMzE4NkMw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTM1QjREMEQtOUJFNC00NDc0LUJDODgtQTIyRjU1NEU4M0I3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTQ1Q0I2MDktRTIwOC00RTU3LUE1OEEtOEFCRUQ2QjhCRTQx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjIzODhENTYtRDhENS00NUE5LTg4QTgtQzkwRDI5NjYwRkRD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MkE0QkU0RTAtQjNENC00ODY1LTgyQTYtNkNEQTMzRDdCQzE4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzkyOUFBOTUtNDc3NC00NjU1LUJFOTAtREY2RTdGOEM4OTIz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/N0U5MUFBNEItQTMxMi00QTNCLTlDNzMtOTFBNDBCNTU3NjU0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/N0ZBRTVBQUEtQUNDQS00ODY5LThCMzctNzEzQTg5QkRFMkQy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDNERUY2NDAtQjUwNS00MTExLUIyQkItM0ZCREYyRDAzNkZD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTAwQUQ3QzctOTZDMi00OTA5LUE4MzAtOTgzMDY3NEJBQ0E4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTc1RUFDOEQtRjUwNC00MUNBLUJFOTctQUQ1MjAxMzg0NTc0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzhGODRBODYtNDUxQS00NjZFLUJCRDQtNkYyODMxQzIwMURF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODYwNDkyMzctQkJDOC00QjlFLTlEODgtQzk5OERFQkVCQ0Yw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTA1MzRCOUQtODU2RC00MDdFLUJDOTYtN0RBMTEzRDEyQTBG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTUyNzcyN0MtRDdBQi00MTQ1LTk5NjAtQzlGQjY2NTMxMEEx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTlEQTM2REYtQkRCRi00OERDLUI3M0MtMDRFMkI4NkVFRUEw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RUFDNjZGNjMtOTQ1Mi00REE0LUFCQjMtQUU1ODZBOUFENEMy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RUZBN0YzNzQtOUY3NS00MzJGLTg0OTYtRkJGREVCMUNBODVB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RUZEMjc0NUMtMEEyMi00RTM3LUIzQkQtMkI4NzU4NTE3REE5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjkxMzNBOUEtNTQ0Mi00MjA0LUEzRUEtQjhFNUYwMTU5ODFF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDA5MUVGQTUtQkYzOS00OEY3LTk1OUEtOTM2QjJDOThDREQx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTFCRkVBRkMtNDA2Ny00MEMzLUExOEEtM0U3ODgxNTI3MzIy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzdFNjk4MTAtQjM3NS00MDU4LUJGMDAtQTkyM0Q5NTAwNzIw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/N0YwNEZEMDAtNzg1MS00RjUwLTk5QTAtMzFCMzMyODc0Qjg4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NEI5MzQ2NDYtN0FFMy00MjQxLUE5MjItNjUwNUQ5NzUwOTQy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTA3MDFCNzAtMjRDMy00RkQ3LUJEREItM0QxODFEQkQwNTZB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTI0Q0QyNzYtMzg4RS00MzY2LUE3M0QtNkJBNzM3OUUxQkVG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTZDNEIyOUEtMDk1Qi00OUQzLTlCQTgtNzUyNzc3QTM2Mzk0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTdEMjlGNzktMEMxMC00QTc0LUE0QTgtMTkyRDY4QjZGQjMw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTgwQjEyNTEtNzJGNy00MUNBLUIyNDEtRENCRUJFQzRBQkEx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzRGOTZFRUEtN0IwOS00NjIyLUJCNzQtNzdBQzIyNEU2MzE0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODJGQjE0NTQtMDY4Ni00MDg2LTlDNTYtRDhEMTUyOEY5QjNE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODU5MDlFNDEtQkNDQi00N0RBLTk0NjUtNjMyREVBRkJFMDEx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OEM3RTVBNTktNUIxMC00ODIxLTkwRkItRTkyOTk4QUY5Mjg2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0E1MjY5RDUtNzI3OS00NDI2LTlGRDItM0VEMkUzRTFBQjdG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjY4QjY5NTktRDFBQi00RjUyLTk2RkItMTk2MjJCQjZFOUQz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTIxNDM2N0YtOTQzMy00QjRCLTlCNzktODkxRDJGMDk5Qzgy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTk0RkVBNjItNTkwMC00NkZCLUFBNEQtRDY4NUM0OTExNzA3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RUQyNjFDQzYtQkI1RC00MUJCLUI4MUYtODk4NTBGM0YzOTkz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Rjc2MTZGOTItMDNFRS00QjlELUE4Q0ItN0IzMDI3RDJFNkEy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MUU3QjQ1RDItREQ1NC00RTY5LTk1QUItOTJFRUJFRDIxRUU4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjgzOUQyNEMtNkQ5NS00RjNBLUFFQjUtRjJEOEFGNEIyRDU3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzAwRkY5NzQtNkVEQS00MTFBLTkwMzktODYyREVBQzk5QzA0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NEE2NUNEMzMtM0Y1Ny00NEEzLTlGNDktNkY0NjkwQkIwMDY3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTA2MjQ0MzMtNzQ5NC00NUM2LUFBNUUtRUU4RUYzQjIwRjU2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NUI1RTYxRjItMTMzOC00MkI1LUI4NjQtNjMyNDM0RDQ5MTI5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjFEQkI4QUYtMzgxMi00NzgzLUJEM0ItMTA0NTIyQTNDNDA1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkY2NUJERkItMzFCQy00RTVCLUE1QjMtNzhGMEZCMzg1MjEy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzREMEIxNkItQTMwRi00Q0NGLUFDRjYtRUFDQUZBMTYxRkFC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTVFMzI0NjAtMjQzNC00NTFCLUI2MzgtRjgzNkUxQUFGMTU2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0VDNTA3MUQtMTczOC00MTc2LUI1MEQtRTVCQzVGNzBEQkQx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QUE3NkUxM0EtOUE1My00N0M5LTkwQTMtNjI3NUY5RUEyOEM2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QUY0NzNCRDctNTkxQS00NzhGLUEyQkMtQTk4MTA1NkZDREUy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QkExNkE4MDQtNEJCRC00QzlELUE5MEUtNDBBN0NGQUMyMUQ2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzJGMDgxOTktQUNCOC00QTkzLUFBQTQtMzBCQjA3N0VCQTIw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Qzk4MDNCODgtQjJENC00NDRFLUJGNEEtMzc5NjE3MDBFRjMx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTU2QTkxRTktODJGRS00RTk5LTg1NzEtNkE4NEE2RDM1MEIw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RUE2NDRGQUEtMTE2Qy00REYyLUE3NjQtNTE0QzQ1Nzk5NDRE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RkIzMzNDRkUtQjg0RS00RkFDLTlGN0MtOURGOTdERjYzQ0ZG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RkU1RDA5MDYtQjM4OC00RkE3LUIzMTEtRjAzOTA5RjFGRTFG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTY0NzM3OTMtOUU1Qy00OTM1LTlBNzQtM0YxMUUzN0RGM0E3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MUM2ODVDMUEtRjNCMS00Q0Y1LTk0MjAtMUQxMjlERkIxOEUy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjFBNjUxQjMtMjk4MS00QkYxLTg1QTQtREY1RjZFRTVFOEE5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDUzMEQ0NkUtOEIyNS00OTAwLUI4RjUtNjVGOUREQzg4N0JG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NThDNEQ5MzAtOERBMS00NDk1LTgxOTctOTE2MUUzRThGMUY3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NUQ3NDIwOUEtNkNGQS00NzQ3LTgyNkMtRDNBNUY1MThCN0Ew",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODc0QzM3MEMtRjI1Ny00NjY2LThDRTUtODM3RDk3RjVCMUZB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODlDNDEwOTgtQ0JFNy00OTQwLUI1QjYtRTQwMzE5NEE3QjZE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUM3NTMxQ0QtNDhEQS00RTA3LUEwRUEtNzg2RDY4MUVCRUY1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzI4MDY4MEMtRjE3QS00RjFGLTlCQ0YtRDkxQzI5OEMzQjFG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzcyMjg5M0EtRkU1Ny00NzkwLTk1RkMtNzFFMjMyMUZBNzE2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzdBMUJFNDEtNEQ0OC00QzgyLTkyMEYtNzRBREZCMTcwRjhC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RENGQjJDMkItNTlDMy00QjY5LTgzRjUtQ0E5RTMzMkJEQkVD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/REQyQkU5OTgtMTI0QS00REYzLThBQUUtRDNFMTMzNjA1MzZB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTY2MUY1OTctRDJBMy00QkQ3LThGN0EtRDA2OTgwOUMwQTIz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RUFGMzg1QzEtNjc3Ny00RjRCLUIyMEUtNEUwRjVFMEMzRTk2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RUNFQUUwNUUtMDlFNS00RkVELTkyRUYtOThEMTg5NDE5NzU5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RUQyMTMzNEEtMzQ5Qi00NjQ4LTkxNDgtMjY1MUI3RkYwNzlE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RkJBODE3NDctMTM0NS00NzA4LUJFQjYtNEE5NjE3REI0QTdG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RkJDMDlFMEMtRENENS00QjJBLThEN0UtNzhFMjI1Q0JERTM1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MEZGOTM3RjItRUZGMS00Njc3LTg4QzItQTY5RTM4Mzg1MEQ1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTlGNTM3MTUtN0Y2RS00MTlELUJCNjctMDk3RDY1NDkyN0ZE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjE2MTc4QzItM0ExRC00RjgzLTlGMzItRTg2MEZFQ0UyRjRE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzIxNzM5REUtMTUxRS00Mzc2LUJDMjYtMjZGRDYzRTM4NEMx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDFGNTcxRjItMjY2My00N0Q3LTk2QzQtNDE3OUE0NDVGQzMw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjZBRUEzMjEtOEYyNS00MjBELUI3MjktQTc0NTJBNjM5MTQ1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkM4RTNGRjAtMzA0My00ODNELUFBNDItRDM4MDI1RDc2QzM3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzAzRkNBMDYtQkE2MC00NzA0LUIwMjItMzY4M0E1QTZDODEz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzlEQkVFODgtQTE0RC00Q0UyLUJEN0UtNTgxMzVCMTk5QjdE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OEQ2QzM5QjQtMEUyMi00MkNBLUJGNkMtNEZBNzY3RUM5Nzk1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OEU5QTVDNTItOTIzMS00NUNCLTgyQkMtODc0QzM0NjA1NjA1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTQ5Q0QxNDMtM0RDOC00Njk2LTgyNUItQ0JCODc0NkYyMkEw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjI4MUNCQ0EtMzUwNy00REYyLThGNzctNENCMzkxNDExMjgy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjY0RTE1OEYtRERFMC00N0VBLUJENzEtMDUyNjgyQUMxODRE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDIwMzhBRTEtNTFFOC00REZGLThCQjgtOTRCQ0YzRDFGNjQz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDJGQzE2ODktREI1Ny00QjkzLTg3NTEtQzAwODZCREM4NDU1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDVDOTk2QjgtMjQ0Qy00RkEzLUFGNDMtNUYxOUZBRUFBRTg2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RENDMEY2MTYtQUJDMy00QTIxLTg2RDMtNjNBMTM4NEFBNDQy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RURFNkQ0QUMtMEE4Mi00RTdFLUExMTgtOEYzRkZENjYxODY3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjA1MUI2QkEtQjA3OC00NUQzLUIwM0ItRDY0NUE1QzY0M0ND",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MEJCNDE0NzctMDZCOS00NUIxLUFEQjUtQUU3ODZDQkVFM0Q0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzRGOTZEM0QtMzY4Qy00M0NFLUI1M0MtQjAzQzBGQTgxRDJB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/N0Q3QkYzRTMtMDFGQS00RDdFLUIxRTYtODI3RDg0RTgzMEQy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjRBOEYzQjctMDRDNy00NDgzLThCOEYtQzdCQjEyRkIyNEUw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjlEMUE2NjctQkY5Ri00QzNGLUFFQTQtNkQ0RkM1QzZDQjI1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzIwNDY5MEItREFENC00OEIyLTg3RTAtRDk0QkY2Njg5M0Ez",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODJDNTg5NkItMkNBQi00NTY5LUExMzYtNjU5RDUwRjEyMjkz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODQwNTk0QUEtMkUxQi00NEQ5LTgyMEYtQkIwMzRENEEzMUFC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OEVFOTVENDQtMzdFQi00ODY2LTk0QTItOTk5NDdCMEZEREM5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTQ0MTU1NEMtRTY5OS00RDA2LUFFQzMtOEI3Q0RBMjMxMThF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUQyOUYyOTItNDFFNC00RjlBLTlGMkItOEQ2OEUwNTA3RjdD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUY4NDRGOUUtNkNCMi00MDE1LTg0RUYtQ0M0MTI3RTRCRjQw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0VEMTFFMDEtMEQ1Mi00OTg0LUJENDEtRDE1NTQ0RDJBQURB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTQyNkNGMUEtRkU2Ri00QjRBLTk4RkItNENCRTk4MTkzMThE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjIxODhDOEUtOTkxQS00NTg4LTg3RjUtMEUyOTZDMUIxMDQ2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjU4OTY2MkEtMENCNi00RkE0LThEMTMtODBBRjNCNUNCNzI5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjY0NDlBMUQtM0E5QS00Mzg2LTk0QTYtQzdGN0QzRDhGNzU4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RENDNkU0QUItOEZBQi00RkFBLUEyRTEtMTc5MjYwMTM1NDQ0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RkQ5MDZEQjQtMjcxMS00M0NBLUE5NEItMEU1NkU4MkNERkI5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RkVGMEZBNjItOUE3Ni00OUE2LThERjctOEE1N0NCNUY1NkU2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjRCRERFRkMtRENBNi00NjJFLUE5MDUtQjE4M0VGMUMyOUMy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Njg4QzkwNkEtQzRBRS00ODM5LThFNDktOTlGMjk0NTg4NEE1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QkE4N0Y5NkItN0YzMS00RUI0LUFDQUEtNDg2Q0QwRDU2QjNB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzI0RkRBRDMtOUQ4Ny00Nzg2LTg2MkQtODVGQTA3NjhDRTFG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDc5RDJBMjUtMzkxMS00RTM5LUJCQTYtRDk5NDIzQ0EwNzVE"
       );
function bacaHTML($url)
{
    // inisialisasi CURL
    $data = curl_init();
    // setting CURL
    curl_setopt($data, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($data, CURLOPT_URL, $url);
    // menjalankan CURL untuk membaca isi file
    $hasil = curl_exec($data);
    curl_close($data);
    return $hasil;
}

echo "No : Nama PT : Alamat : Kota/Kabupaten : Kode Pos : Telepon : Faximile : Email<br>";

for($x=0; $x<=384; $x++)
{
    $kodeHTML = bacaHTML($html[$x]);

    $namaPTN = explode("<td class='tright'>Perguruan Tinggi</td>", $kodeHTML);
    $namaPTN1 = explode("<td class='tright'>Tanggal Berdiri</td>", $namaPTN[1]);

    $alamatPTN = explode("<td class='tright'>Alamat</td>",$kodeHTML);
    $alamatPTN1 = explode("<td class='tright'>Kota/Kabupaten</td>",$alamatPTN[1]);

    $kotaPTN = explode("<td class='tright'>Kota/Kabupaten</td>",$kodeHTML);
    $kotaPTN1 = explode("<td class='tright'>Kode Pos</td>",$kotaPTN[1]);

    $kodeposPTN = explode("<td class='tright'>Kode Pos</td>",$kodeHTML);
    $kodeposPTN1 = explode("<td class='tright'>Telepon</td>",$kodeposPTN[1]);

    $teleponPTN = explode("<td class='tright'>Telepon</td>",$kodeHTML);
    $teleponPTN1 = explode("<td class='tright'>Faximile</td>",$teleponPTN[1]);

    $faxPTN = explode("<td class='tright'>Faximile</td>",$kodeHTML);
    $faxPTN1 = explode("<td class='tright'>Email</td>",$faxPTN[1]);

    $emailPTN= explode("<td class='tright'>Email</td>",$kodeHTML);
    $emailPTN1= explode("<td class='tright'>Website</td>",$emailPTN[1]);

    echo $x+1;
    echo $namaPTN1[0];
    echo $alamatPTN1[0];
    echo $kotaPTN1[0];
    echo $kodeposPTN1[0];
    echo $teleponPTN1[0];
    echo $faxPTN1[0];
    echo $emailPTN1[0];
    echo "<br>";

}

?>
