<?php
$html= array(
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDFENjVBMzMtNjdFNS00RjQwLTgyNjgtMkZBMDczOEIxRjU3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTI5Qjc4NUEtQzk2Mi00Qjc5LUExRDMtRkEzOUQ0NEMxOTY1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MUE4RDNCNzItNjlDNC00MUMzLUFFN0QtRUE5QkFENkE4NjBD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjY1MDU1NEEtRTlFQy00QjVCLThCQ0YtRkFEQjdFMjhFNzVF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzgxNDg1MEEtNENCNi00RTc2LUIyNzktN0YyNTQ3NzUyRUND",
           "http://forlap.dikti.go.id/perguruantinggi/detail/N0M5MzM4RkQtQ0QyRi00QjgwLUIyRUUtMjQxMDYxNUExMzJB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NUZENDZDQzUtMjgyNi00MjNELTlBRDktOUU1RkU2ODJEOUMz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjBEQzRFNEMtRUQ5MC00REVDLUI2NTQtNTM3NDVGODYyOEEx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODZFRDIzREEtNDNCQi00NjI1LTk0OTQtQjJFMTNENDc4RTBC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTVBNzE5MzAtN0QzQy00RjY0LThERUEtMzYwQzZENTM5QjlF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTE2QUY4MkYtRDMyQy00ODVCLUJDODktOTgyQTc4ODlEMzM3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTQxQ0FFREMtOEI1QS00RjcyLUJFN0EtNzdCNzAyMzcxMjM2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTU3MUQyOTktNTJERC00N0E2LTk0RjAtNzA3OThGNkFFMTQ1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QkFEODA4MDEtOUNDMC00NUQ1LThGQjYtQUY0RTc1OTY2RjBB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDQzRTQ0N0ItM0I1Ri00QTE5LUI3RDItQkQyOTg1NTlERUYx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDZGM0Q5REUtODU3RS00RUZBLUIwN0EtNEIwNkNGODQwNjBE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTFEM0IxQjMtNUY1RC00MkVGLTlEQTEtRjg4MzNFNkE4RTFC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTMxNzJDMjEtMzlBMS00RUNELUI1Q0UtNDI2NTNGNkZGRkU0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjEwNUVDMzYtRTYwRi00NThDLTgxQTEtMTMzQzIyMkFFQjUz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RkM4NTk4NEQtNUU5NS00NzZELUEyM0UtOENCRUMyQzg5Njg1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/M0MxMDY3Q0MtMUZBOC00QTU5LTkzRjgtRDlGOEJDMjM0RUVC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTRFNkQzMDgtQURFNS00NTZCLUEyNEYtNkZCNjRERUFGMzI0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjNCNUJGRTEtOTlGQS00QTlELUFEMUUtRDIyREUyOUFCQjYw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDIwRDhFNzMtNjhGMC00MDQ0LTg2Q0YtNTEzOEQxNDE5QjIw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDM5REQ0QjAtNjQyRS00MjU2LUE5M0YtMDk3RjQwOTM0Rjc2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDgxMUFCNEUtMzhCOS00MkUxLUE4NTQtOTE0NUIyMEM3QTVB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjM5OUQ3N0QtOEM1NS00REZBLTgwRjgtNzAwMjc1MjMwOTlF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzBGNzY4QzUtMEJCNS00MEY1LTk3MzAtOUQ2QkU1MEVFQkRB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODRCMjU0NTUtNkVGQi00RjdDLUIxQjEtRTFEMUNBNEM2QUM4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTU2RDU1NEYtNEM5QS00MUVBLTgwRTktRTRGQTc1M0UwOEI2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTYxRkNFREUtN0ZGNC00RUUxLUJDNzUtOTgwQUUyMjZCODIx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUJFMERGNzAtODk3NC00Q0JBLUEwQzAtMEI3NjczQkE0MEU4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0U5QzcyRTktMTE5Qy00NUJELUI5MjgtNUNGMEU3NEE5MzIz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTgzQTBDRUEtREU5MC00MkY2LUE4OUUtNDg2RjdCNDNCRkZD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QkM1QzlDREMtN0MyMy00OENBLUI4QTItMUMyMUQxRTVBMzgw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzM0QThEQTYtMzEyOC00OEY2LTgzMTUtOERGNTJBMTM5MDhB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzVFQUU0MEUtQjVEMC00QzNBLUFFQzEtQTU4OTQzMTA5NzBB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDY3NkI1QTktNDQ1Qy00NTRBLUFDMDYtNjY5QkEzNDEyOEYw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjU1NzJFNDEtMTE0RS00QzBDLTkyNzEtNDk0RkU3QjI0RTYw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjVDODhGREUtRTlGRS00MTY2LTg2MjktOUFEREZFQUJEQzJF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDhEMjU3MDUtMzI5Ri00OTM3LUJCRDQtQzZBQjRFRjc5QzU5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTUwREEzRTUtOENENy00RTdELTlDQTUtRjdCNEVCQ0ZFQUMw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjM1RTMzQjAtRTY1Ny00OThCLUIwOTktRUNFRkYwQjQzRjk5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjlGRTA0MDYtRjI0My00OEIwLTkzQzAtM0EzMTRBRjg3MEJB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/N0ZCQzUyNjUtMTUwRC00MjlCLTgyMkUtMUI5Mzc0QTJEQUU0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NEREMTZGMTEtQTEwNC00MEY1LThFREQtOTMzNDQzQTczQjE0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTFEMTdCMEMtNzI3MS00RjM1LTg3Q0EtOUVBNDA1RDI2QjY2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTVGNDNBQ0ItNEU4MC00MjMyLTlFRDktMTA3NTE2MTY2MjYz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTczQTA0NzgtNTcyNi00Mjg0LTgxMEYtQTJDNTE1MURDNzhF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NUNFNEIwNjEtRUU2NC00MEE1LThFQzYtRTFBM0Y5RUFFNkQw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkNGNjlDRjQtMTQzRC00RUFBLUEzQjQtMjc2MDZGRDhBQUUz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzRBQ0ZBMjQtNzdEQi00MENCLTk5OUUtODI2MkY4QTQyREI5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODNBQjYxRDktNDU2Mi00NUM2LUEyODEtOEUyQjI2OERDRkIz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODhCQjNDODItMzk4Ri00OTE0LTg1RDItMjJCNzRBNDdBRjE0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTE1Mzk4QUYtREJGOS00MzEzLTkzRDQtQ0U0MTRCNUZGRjk4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0NEMEE5RjYtRDNCNy00QjM0LThCOTAtRDY1RUVEQkRGRjFE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/REJFNTRGNDctRURCNi00MjlGLUFGMkQtMjYwRjU3OERGMEFC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTVBNDg2ODQtQzY1RC00NjQ0LThBRDAtNENGNUJBOUZDMThE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTkwQjhEQTMtMENBNy00NUFBLUI1RTgtRDM0QTc5NjE3OTI2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RkJDRjJDMkItNjgyNS00MERCLUE4RjQtQUMyQTUyRDA0RDYz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MEY4OTNEQjQtQ0I2MC00ODhELTk2MjktNDA1QzcyOTA5NkFF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MkI1QzI4RUItOUI3NC00NUIyLUEyQjgtRDkyRjY1ODhCREVB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MkNERUU1QUUtMDJCQi00MzA2LUJBQTQtRUQyQTk0RTVBN0VG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/N0MyQTI2NzAtM0ExRi00RUYyLUI5QjEtNUMxOUEwOUQ0Q0E1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDQ4RkY0RDItMzYyMC00NDBDLThFQzMtNDFGN0VBRjM5OTE0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTYxMkU5RDktNkRGMy00QUMzLUEzOTItMEJDMUMwNjZFOTFF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjhGODA5NDItMkIzRC00MDRCLTk0QjktRDc3NjUxODJDQzlG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzBFNDg5RDgtRjdBMC00RDlBLUI2QkEtMjAxM0I5QTE2Mzk4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODVGRjQ4NTctM0NEMi00ODM3LUJBRDctNTRDOUE1Q0VBQzRF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTE4MzRFRkYtQzBDRC00MDRGLUE3QTQtQkEwRDNCNDExQUM1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTM4NTY2MEQtNENFRC00Q0E0LUJEOTQtNUYxRDk3MDc5OTk5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUIyMkZDMDctQUMwRS00RUQ5LUE2RUQtMDlEMEIwRTdFNjAx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUVFQ0M5OEUtODA2NC00MDRFLTg0MDYtRUI4QkY1MkUzNTYy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0YxRjBEMjItMDg5MS00QzM2LUJCNDUtRTMzRkU1RTM5NzU4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0ZCOTExNTItQjc2NS00MTczLThCMTAtMzQ1NjU2NEQ0RTIx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTM3QzhGNTktOTgxQS00OTM4LTg2NjctNDFFQjY4QkY2QTA0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Qjk0NTZGRkQtMUFBNi00MTgzLTgwOTUtRjg3MDZDRTVENTND",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDA4NjNGMTQtRUI0QS00QUIxLTk0RTgtQzRGNDlGNTI4RDdB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTlCRDNENjItMjM1NC00NEVGLUFDRjYtM0E3N0M1OEYxRDQ4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjVEOERCMTItQkIwMC00ODQ5LUE3NUUtMTI2ODQzQTdEQjM1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MEI5QTgxMjctQUY5NS00RkIzLThFNEItMTFCRDEwQTgxNjJD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTUxQjQwNTEtRDE1MS00NEQzLUEyQjctNTIwRTI0MjFBNEZC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzkyNUY3NkMtNTMxQy00MzZELThDMTEtMTcxREQzRDFFNEZB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NEZFM0VGQUMtOTE1Ny00ODQ0LThCMjgtNzlCQjgwQjkwNzAx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjJCOUQ4M0EtMEFDOS00MDJGLTlGNjMtMzMwQkRDNjNFMzE1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjUzRUI2QTItMEZFMS00Q0IxLUI3MjEtQkEwQ0QwNjkyOTUw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkVGMEY5MjQtMEVCMC00RURFLUFENzUtQjM5RjE0MjI0OUJE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzE1MjUzRDItQkFGQS00MjlBLTlGRjctQTg1QjM0RkY5NTVE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzNGQzhDOTUtODRDMS00MEFFLUE3MzgtREEzNjA0MzRCMEND",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzU4RDc2RTUtM0EwMy00OEU1LTlCMkQtMzA0OTJGQkJGNDBE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzkwNDYyRjUtQzhCOS00QzFELTgzRTctRkJFQ0VEQTUyNzBG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTNFRjBFRjgtN0UxOC00RERCLTg4RDMtMUUyNjE5MzQzQUVF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0MzNThBNjctODZDRi00MjUzLTg2ODQtOEFGQUNBN0IxMjU3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QURBNTFFOEItMjcyNC00RUM3LUE5N0UtRDY5OENDMDg4Nzg4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjQ5QTAxNDAtNzBGRS00MEMwLThGRjEtNjVGQTRGMEQ1RDlG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Qzc1MEQyQjAtMUQzNy00NzNBLUFEMDItNDBGNTNENEU5NDNF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzdGMzM1NkMtRDFDOS00REI0LTkwNzEtREE1MEZFN0VDMENB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDE2MTAzNkQtQ0Y4QS00MDhFLUIxNEYtRDlGNUI0QkE4RkIy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RUQyOTA3M0QtM0FDNC00NjI1LUI3NDktRkYyRjc4OUJFQzkz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjJCNjM5QzQtNDU2Mi00OUE4LTgyMUEtRUI3NEVBQ0NCNDgy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDc0QjdCODctODFGMi00QjA4LUJEQjUtOTQ1ODhGQjdENEYw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjFFODQwMTYtOTQyMy00N0Y1LUE5NDItNjgwMUMzQjM2MEFG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/N0NFQjVFMDktNzAzQS00MTUzLUE3MDEtMzYwQzczNzUyMzUz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTA2NkJCNEQtNzg2OC00NTBFLThDQkYtODhDQzk3RjZFOUQ4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODBEMDkzNTAtMDI2Mi00NUZDLTk3MTMtMEZFQkIwODQ4Nzg2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODZERDZGQTUtRDgwRS00ODE2LTlDQ0MtMTQ2MTM4OEQzODBG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUFGRkNDOTItRjQ0My00MTY3LUFGRkQtODc1QzMwM0YwOTU1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUZDN0M1NEMtQkY1QS00ODU0LUFFNDAtRkM0NDEzN0RDNDQy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0ZEQTgzOTEtM0Y4RC00NTU3LUJFNzUtQzU5RDk2QzA1NTE3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0ZGNjdENEQtNEFDNC00QTlBLTk3MTgtMEM3QUE5MDdCMEE3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTNCMkZBOTUtMjFBMS00MDI5LThGRDUtMkY2OUREQjEwQ0U4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTRCOUYyNTctRkYwNS00Rjc5LUFDNDEtOUEzM0I3Qjk2QjAw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTVCMzY2ODEtODI5MS00N0NDLTg0Q0QtQTdDQUE5NjUwNkVG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTdEN0QxNUEtN0Q3Qi00OTA4LUI5NjktRjU4Q0MzN0Q3ODAz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RUYwNzk0QjYtM0U4OC00NTAyLUJERUYtRjFFOTY0QTgzMkYz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RUZDRTgwNzMtMzBDQS00ODJCLTk2QjAtMDgwQUI2Q0YwOTQ0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjQzQUI0RTgtNzE5NS00N0UxLTg0MUYtMjNFMDE4MTA4NDJF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjYxMkNEQUItMjExRi00QzY2LTk2RTktMTZFRTlCNTUzQzI1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RkI4NDVDOTItNUVERS00NDFCLUI3QTYtN0E1MzM2NUY2RDdB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RkU3M0YzOEYtQ0FCRS00ODRGLUExREYtOEY0OEVFNjY4NUY3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MUI2QzU4MTAtMkZBMy00MUZBLTk4NTQtRTVCNzgzMjE4NUI5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MkI0RjMxN0ItRkVDNS00OUZELUFDOTctMDU5NUNGQ0M2RDdD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDEzQkQ5RDAtRDA2Ni00RUJFLUIzRkUtMTg1MzYyOUIxNEJF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDk1QTFCRTktMTdBQS00NzNDLTg0MDEtRkNFMzNBMDRBMTBG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NEU3MTAxOEQtM0I2OC00ODVBLUIwNEItNTRBMEFGRkYyRURD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTAxODQwMzctRTdDNC00N0FBLTlFMzEtQjVCM0U4QjdCQzVD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjRDRjVDQTAtNTU5RS00OTg4LUIxQTQtODhDQzkwMkE3RDdB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODVCRTMxNEEtMkYxRC00NzcyLTk0MzgtNDQ0RjY4RjhDNTcx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OThFNkYxNzEtOTIzMC00RkVCLUIwOTYtNDQ5NzA2N0Y4NTQx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUE2REQwQzYtMzA3RC00RDlDLTlBOUEtOTQ4MDQ0NDc1N0RB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUVEOTk0OEItRkEwNy00NjU4LUI4OTUtOUFBQTYzOUVFNUIw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTk5MkJENzMtQTRENC00REIwLUE0NUUtN0I5NDI5NkQ3Njg3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjA1MUJBQTktNUE3Ni00QTBBLUFCMzMtMEM4QTkzQjBBMTQ0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Qjk0OTM1MjgtREYwMC00MzQxLUJERDctNUQ2NjQwOEZERjlF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Qjk3MkExOUUtRjMxQy00ODQwLUEwREYtQjgzNUI3NUE3MDFF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QkYwNTZBM0EtQjExNS00QzQ2LTlEMEYtRDhDNjBERDg0NTNC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzQ0RThEM0QtMzA4OC00Mzk3LUIyNzEtREU3NTNBNjlFQzM0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTNERkFCNjMtRERCQy00QTU5LUJGNDQtM0MyMjlFRkEwM0My",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTk2RjJDNEMtMDBDMy00NkIzLThERjctM0RCMDAyQjRBOEFF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RUFFNERGRjQtNzMyNi00MzRFLTg3NjktRThCRjIxRDdBRjVG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDBCNjI0QkYtNjU3Ni00MjMyLUIxREUtNUE3MjdFNDhBMjE0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjdFMDJDREUtODdDQi00OUFELTgwRDYtMUIzNzJFNUJDOTZG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MkMzNzZCRjMtMEZBMy00NzRGLUExQkMtQzNGMDYwQzU3NzMx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzE3M0UyQzktNDBDNi00MDQ0LUJGMjEtQUI1MDAxNUQ3NDk2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzM1N0MwOEUtODJDMi00MUI0LTlGNkEtMzIzMkEwMzlCNkE1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzcwNUNBNzItMjZFMS00M0Y3LTkxNjMtNzA5M0VEREVCNTg1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTdGQzkxMUYtRUEwRS00MTdCLUI2NjYtNEJCMzNCRDYwMUJD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjU1MTM0MjItMEJFOS00QUNELUI1ODAtOTg0QzdGRTlBQTg4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Njk0MTFCNUMtN0JDNi00MjRFLUJFNDEtOEU0QTA4NkExMUNB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODg2RjE4NkUtQzcxOC00OTlGLTlCRUEtMTYwMDFDN0RFODM0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTQ4MDczMTYtQjY1OS00NjFELTkyMEUtOTY1RTlCQkQxREVF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTRDNjA3NzgtNTYzMC00RTc1LTgzNzctMjVBMDdCOEM1NThD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTZFODFGMkMtNjE0Qy00M0IyLUIzQ0EtMTI4NjQxREQ1QzdF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTdBOERFNjAtNkQ0My00NDI0LTlENkUtNjMxQTVBRjI3RkYx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Qjk2OUNFQTEtNUMyQi00NTEzLTlCMDMtQUMxNTBDMDE2QkFF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QkI1MzQxQ0MtMEI5Ni00NDYyLTg0QTEtRkU3QTkwNjdGNjBG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QkMxNjY4NjMtQjczQi00QzNBLTk5MDEtNjkwMUNBMEIxREM3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTczNTlGQTktQUUzNi00Q0RCLThDNzgtNzg5Mjk3NUE3OEFE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjBCMTQ1OTUtQjdCRS00MjlGLThCQzItNDQ2N0QyN0RCNUQx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjlFOUMwRjYtQ0Q5OS00REM1LTlCMUUtMkYyMzA1QzMyMkEz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDI1RDI1OEMtRDJGQS00QjcyLThBMEEtMUZCNkJBMTkzNzc4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDYxMTYyNUYtQjEzOC00RkMyLUJFMDMtQTI5NEFENDFBN0Ez",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDg2MjE0RjUtNjBBQi00NTU1LTkxQTItOTM2MURDQ0FFRDM3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTAxNTlCNjgtNzE3Ny00QUI0LUI4NkQtQjg1OTlFMEE4RTVG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MkMzNkQxMTYtNjNBQi00N0EzLThDN0ItNDA1RkI1MDQwNkE0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MkUyQThCQjItQURGMC00Qzk0LTg1NDItNTk0MkQ5NkM2REQy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzBFMUZFNzctRTI1RS00NTJELTg1RkUtMzRCQTkxMUZEQzM4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDA5MUNDODctMkZFNS00MTgyLUI4OEYtQUQ5MjQ0REU3MUEz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NUEwMEMwNTctMEFGQy00RTJBLTk0NkYtMkY4MkM5RTY0ODFB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OEMwQkY0Q0EtQTVEQS00MDYwLUI5MUYtOTdGNEEyMDI1QzNE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTRCRkJENDItQkM2Ni00REI1LTg1RkYtQUM2RTJDM0NFRTU4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUU0QkRDOTQtOEU4Qy00NzYyLTk5MDItQjc2QjIxMUYyMEQ3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUUxNTYzRjEtOTBBQi00NjM5LUFEOUItNEY5RkZDNkU0NkY2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTI0QUM1OTEtRUI4Mi00N0Y3LTg0QjItODEyNzlBMDFCNzJE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTkwMDYwN0UtMDQ0RS00ODNDLUI3MzctNzM1RjJENTQ2NjUy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzBBRTdCNjgtOUI3Qi00QkRDLUIzNjgtNUIyMjIxOUNBMUMz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDIyRkM0M0YtRUFBNC00MkM3LTlEM0UtNkZFOENBMDkwMDk3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTgzMTlGQ0YtQjlBQi00NDY3LUE3RjUtQzAxNDI0NEI3Qjcw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjFFQkNBMTktNEVEMC00NDQ5LTgwNUUtM0IyREJFMDJDQ0M1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjgyQUNCMUYtQ0ZERi00NjM5LTlDMkEtQUE1QThGMkYxQUNF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTBDQzMyMUYtMkNDQi00QTAxLTlBNjYtODc0QUQ4MDYyRUVE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTFGQTgxNkQtQTA4MS00NEE2LTgwODktN0Y1REE2MTlFOTFD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDJCODkzN0QtRTA3OS00QzgzLUIxMUEtQ0I4NzcxNTNBN0NC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NEFGMzI1MDItMzZBRS00OTRELUI1MDQtNDhFODcyM0M0OUFD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjBFQTAxNDctQkZGMS00QzE3LUE0NzMtRTM1MDgxNDlGMDlG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjEyNzgxM0MtNDhBNS00M0I0LUI2MjEtQUIxNjFFM0U3NTM4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTJDODBDMEMtMjBBMC00NUJDLTg5NjMtOTU1QjI0NzE4MDVG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUE2OUM0RkQtMzA0Ni00Qjc2LThBMDAtNUExQjYwMjg2NEIy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUIxQkQ0NDAtNTAwNS00MTgyLTlCOTYtM0FBREVGOEYyNkZC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0NCQTlDMEEtMDA1NS00Rjc5LTk1QjAtRDI3RjAxMjkwQURF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTQyMjNGMzEtQTE4QS00Mzg3LThGODMtRjQxQUY2MDA2N0M0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTY2OTc1ODYtMjM3Ny00MkMyLUE3M0EtMkI2RjdCMkIzMDE1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTY2QjA3MTktQjIzRC00RkVCLUJGQTUtMTkyQkI5ODA1MDVC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QUFDMkRDOTEtRUM3OC00QzZELUExMjMtNTM1QUIwMzY3MDI4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Qjc0OTA4QTMtMDIxRi00MkQ1LUFBQUUtMDZERDQ4NDBFMTNB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QkQyMDI5RkQtMTlCMy00MERCLUFCNTktMDRCOEQzNzgzNjhG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzdFRkU1ODEtNzhCQi00RDEyLTkyNDMtQjVDQjc2M0RERjk5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDczQzMxNUEtMDk0RC00MjhFLTg4MjctOTYxNTdDMTZFQjI4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDdGQzJDNEItNTNGMS00QzI5LUExMjUtMjU0MEI2NTFDN0JC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTMwM0UxNEMtNTkzRi00MzNFLUE3NTktRUNDRjAzMjQwN0Q4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDY2MzQ3NkUtMzkxRS00QTU0LUFBNjktRTUzNEZDNjhFRDNF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDk3NTUwRjMtRkU1Qy00QjBDLTlGQkMtNzA5RjRCRDNDODUz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTE4MjI5MkItRjZFQy00OEZBLTg2QjQtNjhDNkJDQzQ4MkRD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTFGRjRDQTYtMTdEOS00NTc4LUI0RkMtQzlERDI3MjYyQjM3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTMxMTc4ODMtNUU0MC00RDhCLTg0MTMtOTRFMTE5RDNDMEU3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTdFQ0U0ODMtQkM0OC00Q0YwLUFBRkYtMzAxNkU4Mjc3NkI4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MUQ0MDRGNDgtNUNDQy00OTY1LUE3QzQtMjA2RjBCMjgxNTNE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/N0ZERTU1RkUtRDUwNy00QTQxLTlDMTEtREM5OEM1NEU4NEIy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDg1RjE4MzktNTBEMi00RTQ2LUJGMDgtMEU1QjBDRDdERUQw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NUFBMTM0NDItMUQ3RC00QTlGLUFCQjItM0ZDQ0NFNTE1MTI0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NUZCMUFCRTQtMjZDMC00N0EwLThEMTMtNjFFNUY1QzBFQzEz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzMzRTEyNTctRjY1Qi00MzI2LThFM0MtNDY2QUJGQjc0QTUy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUQ0QzUxMDQtRTQwQi00OUY2LTk4OTQtNTlCMDc1Q0ZFRjgy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0NDMzFDMEQtRTM0QS00MjhGLUI5QTEtQ0YyNTRDM0EzREZB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QUI5QjgzRjctNDdDNS00ODY1LTg2QUUtNDdCMEJBMjE1NUY5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QUU5MDExMDEtNkUxQS00NDkwLUEwRTYtMEYzNURFMkM1REE2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjM1ODBGQjYtRTAxMC00MjFCLTlBNkMtNzk2MUMyRUNDRDM0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzcwODE4N0EtMzFBMi00ODhGLThDREUtNzRBMUM4RTk0RjZG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTQxOTVGQ0ItOTVEOC00MTNBLUE1ODAtOUQyRTUxMzc5NTZD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjM0ODc2MjItNjE4Qy00ODVELUEyNTktQUNFQ0I0Q0ZBQTAy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjBDOTNCQzgtMjVCQS00M0VGLTg5RUYtMDcyOTI1RjkwQTUz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/N0FERkFGNDUtQUQwNi00NzJBLTg3RTItRTRCOEMwNEU0RDUz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDQwNDhEM0QtQzM0Qi00MjEwLTlGMDEtRkU5MTY0QjU0RTg3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NEI1OTQ4MDQtOURGRS00QkM5LTlGNjUtMTc2NEJBRDZDMkFB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NEZCRUFBM0YtNEFGRS00QTVGLThCNDEtNUYzMkNCRTQ2Mjc3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NUI1NTc3NjMtNDYzNy00RjI0LUE0MDYtRTIyOUNBNTEzMEY3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTE2NDI2RTItMjA3NS00RTlBLUIyNjgtRTQxM0QwNTlFODM4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTEzOUUwNUEtRUMxQi00Q0MzLThFRjMtQjM4MjQ1MjUyM0JG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTMxMTk3NzktNzg5NS00QjNGLTkzMzgtQURDRUIxM0U5QjFC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTQxRkYyMUMtNkI2OS00MkFDLThDM0QtMzY5NUFBREY1Q0NG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUFDODlCMkUtQzAxQy00NTMxLUJEN0ItRjgzNTdGNDFGNzVC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUYyNzM3QkEtQUYyOC00QUNDLUIyNjQtQzc3MzkwMzhDREQ3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTMxMkM0MUEtQzE0OS00NkQ0LTlDRjItQzAwNEY3MzA0QTc2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTNCNDg2QzEtMkJDMi00NzY2LTkzMzQtRUU1QzZDNDI3RkE5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QUUyOTExQ0MtN0VCQy00RDY4LUE1NkEtQjQ2NTk3RDYxQ0VF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzE1MTE1RUQtRjcxNC00NjM2LUJGRkMtMUNGNzM1OTczNkU4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzhGNkM4NzgtRjYzOC00MjhELTgyMEMtNEY5MEMyMDdERjA0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTVENDNBMTMtQjk5QS00Q0ZGLTgzOEItOTY1MzQ3MEYyMUIz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RUNEQ0Y2OUUtREM3Ri00NjgxLUE4M0YtMTU0NUYxMDUzQzk5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RkY0RkY1NEEtRTEwQi00ODhBLTkzOTktRUM0NkFDMEE1N0M5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDVFNTNGQUUtNTVEMy00OUU1LTg3NjAtN0YwQUYxQUY0MEI5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDYyQUIwODktMjk0Mi00NjdDLThCRjgtQThDQzk4OEZBRkQx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTgzQjVDQTMtNEMwRS00OTlELTk4QTAtMEY0MzBCMzJDNDkz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MUI3MDRDM0ItQ0REQS00MDA4LUI0NkUtNDY2RjlENjNGNEMz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDhDMjQwQjAtQjc5MS00NUIwLThGMkMtMUFCMDlGODdBOEJG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTAzMzU1Q0EtMDUyQy00MzQ4LUI3OTEtRTVBNEQ5REM2RjVE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTYyMTc0RjYtNUJBRC00OEZELTg4QzYtNUFDNTUxMTk1RTZE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjVCQjczMTItRTAxQS00RjdCLThGMEQtNUM3Q0VGOUM3MTk1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkQ0QjlENDgtNzVENS00NEYxLTlCMDEtNTg3N0VDNzQyRjI2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTExMzNCQzEtM0MyQy00REIwLThDQ0UtNUNERkUyMzdGOTVG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUVEMTMwNjItQzc5QS00RDNGLTlBNzMtNDUzNEUyMTRDNTlC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0FERTAwODAtNTE3RS00RUM3LTk2NEQtREQ0QzcxNEZGMEQ3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0ZBNzUxMTAtMjY2Mi00RTQzLTk3QjItQ0Q0NkFBNEQ4MkRG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzAzNUM5QzktNkUxOS00REU2LUJFRjctRDA2OTlCREZCNUUz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDU2NzY2NEEtODdBRi00Njg2LUFBQjQtRDUwRkNGQTk1MDg1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDhGN0FFOEItMEZBMy00MUE4LUE0RTYtQUY5QkY4RjI1RTQ5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/REMzRDdCRUYtMkY5My00NDA3LTgzOTQtMjI4RjgzQ0ZBQTVC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/REVENDdFREUtMkNBRC00MzAwLUI2QzEtMkY1MTU5ODlGMkRC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTAwMUQyMEMtOUZDOC00RDlCLTk2RUMtMEQ3NDU5OTc3NTJG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTkyQkNBQjEtQURDQi00RTg5LUJGQzctMUUxNjUyNDU0Mzc4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDUxNDcyNzYtNDI1MC00RkJBLThDRUQtQkFBNDg3QUU4RDgz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MEE2MjAwM0YtN0E3RC00MEUwLThGNEUtQzQ1QUYzNEE4RkI3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MEZGOEZBNUItRURENy00QjU1LTg3MEQtRTk1NDlBNDY4QUM1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MUE5NUI5MTktMEU1OS00MjYwLTgzQTktOUNCQTc1MUIyOTUy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MkYxOTNDMkItMTQxQi00OTlGLUEzNjItQzNDRTAwNkVGOEFE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzFFMjkzQTUtRUI4NC00NDJDLUJENDYtMTZFMzMwRjQ3OTEw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzIyMDlEQUEtRjk2Ny00NEY1LTg4Q0EtQTM5MkUxOTY5NzRD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzM4RjJEN0EtRTNEQy00NDY3LTg2MEQtQTUzRDIzRDQ3NUY4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTQxQzNFRTktODMyOS00OENDLUE0RjgtNjJFRTRGQTY4RUE1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTk0QzFCRkUtMDIyMi00MTI5LUI5MzUtNjY1NjA5NDA0N0VG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjE2QkQ1QzgtMzVFOC00QjY0LUE4NzgtQjQ1Rjg5NTJDRTcz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzdFQUU5ODctOUU1NS00MjVBLTg3RDAtMjNBMUVERENENUE3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODM3QkZENzItRDA5Ni00NTUxLThEQzMtNTlBMzUxMkI3MDQy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTdCNjBGM0UtOTVFRi00NjI3LTk2RTUtMUY0QkJBQUQzRDJE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUEzRTZCNUYtMTc1Ni00MjU0LUE1NTUtMENCOEIxQTgwMkND",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QkI2OUVDQkUtQTBGNS00NUQxLUE4MjktQzFCRDQ1Q0VGOUY1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTM0MEI0NDItNDQ5NC00RjExLTgwQ0QtNTkyOUEwRTdCMUJG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTc2MTc5MTYtNzRBMi00ODFCLUE0RjItREE2OUZFRDJDRDI2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjQ3OUVCNEMtOTE0NS00MkVFLTkzQjctNERFN0I2RjlGQUZD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RkFGN0JFM0ItQzMyQi00MDkwLUIwMTUtMUU3MjY0RDlGQkQ5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDc5MkYyOEEtMjQ3Qi00OTc3LThCNUYtMEIxMUIwMzk3NTAy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Mjk5MTlDRjgtNkQ1Qy00RDg0LUFENzUtMjBBOUUwQzIzNkUy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDRCODhENEMtMTAyNS00QjZDLUJBRTUtQUIzQzk5NUZENkI5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDY0QURCOEQtRkE1MS00RjYwLThDMEMtNDc5NDVBMTUxNkRC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDdDN0ExNzUtMjNDMC00RjM1LThFMDgtMDc5NERCMzFDNDNB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NEFGNTM2MjEtNTI0Qi00MTNDLUFBNzItQzQ5MEE1RDJDQUIw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTgyRDkyMUEtNUYwRS00NTdDLUIwOTUtODkzQzkyQUFCM0JE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzFEOTEzMDMtREM3RS00QUNBLThGNDQtRjg5MzRGNjNFNTQ4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OEIwQkNEOEMtQ0VDQi00NTI2LTlGRTktRDEzNzQ1NjJCRTJG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OEZENEUwNzQtMzg3MS00MUJGLTlEOUItMjg1NzM3Qzk5RTQ0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QUE5MjY3NkEtNUMyNy00QjdFLThENTYtMkE5MjMxMjc1REJC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjU0MjAzQjYtNkQyMC00RTIzLTlGODEtNzEyQjFCRUVFOUND",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjU4MjZENjAtRUJBNS00Qzc4LTkxQzEtMjI0MkI3MkQ0N0Q3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjkwQ0VGODEtMUNFQy00QkM1LUIxMjYtQjlFNzRBQjhEM0Y4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QkU4OUQ3RDktNTc4Qy00RDk1LThGQUEtMEE3MDUwMzREODk0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzIzM0MwNTMtMkY2OS00NDZFLUE0NTMtQUE3M0YxMjU3RkI1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzlDRTdGMkUtNjgwRi00NTA0LUI4NTEtQjQ3RTMyQ0YyNUYw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDU2MzVGNzItMkQ3NS00MDZDLTk1MkQtNjREQzg4N0FCRkZE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjY4OUJEQzktMTg5Ni00QTUxLUE1RTgtRDIxQjFCMjY4OTU2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RkJGNUFGN0EtQTYzQy00MkI4LUFBMUEtMDZFNzNCRENFMEQ3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/M0RFNkQ5NjEtRkY4RS00M0FFLUJCOUEtMTVCMUI0QTU3RjUz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTJGRUI2QzUtMzIxOC00MkQ5LThGMkMtNkZGRTdDQzUzRTMw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTZBQkIyMTYtNzU2Ri00RDVDLUIyRjYtN0YyMDNDOTJGOUQ0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MUYwMTkwOEMtRjUwQy00RTdCLTlBMkMtNjY4ODcyNTIwOTFB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjNBMEM4MTItNTFCNi00NkVCLUFDQzEtQTUzNEI5NDM3RTg2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MkJGOUM3NTEtM0QzOC00M0MwLUE3QzUtOURGMTc4MThEQURG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MkQzM0E3RUYtRTJCNC00QkYxLTk1NkMtRTI2MTNGRTYwM0VC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzE5QzNCNzktQUQxQS00MzJELTkzQTgtMjNEQkJDRkFFQUNB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/N0MzMzgwQkEtOTI3NS00MEQ5LTk0NUItNTgyNDAwRTVFNzUx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDJFQkRFOTctQ0FCMy00QzgzLUEyNkItMUUzNkFGMjlEMTg4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTNFNTMyMzAtMTcwNC00ODY5LUE0REMtNDk2MjA0MkFCRjlD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTVERDQ5MUQtMDIwOC00M0RFLUEyRTMtQTRENDZEQkM2NTE2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkVFMDJDM0EtQThEOS00ODA2LTg5OEUtNDg4RTNFQ0I1QjA3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTI1ODQwRTktQTkzRS00MzE3LUJENzQtRkQzOUU4QzJFMkQ5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUFDOTgyNkQtQjFFNS00NzhDLUFBMTYtNDRCQzA0N0FBNENB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0MwMzU0NDktQzIyRi00QTRGLUJBMzgtODkwQTIzMENFNUQ5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Qjc2NTVBQTktN0ExQy00ODEyLTk0MTAtMzJCNjgyODc0Mzcz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QkE1MDk1NTctNUE4Qy00NzIxLUFBQzMtQjI0RDdDQTQ2QkIz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QkY3MTMzMkItQzk0My00MzMyLTlGOEYtMUQyNjJBQzI3OEE3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTcwRTVERUEtQ0NGQy00NUNGLTg4MkQtQzc4REQ1OTVFQkZG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDNCNTczNjktOTVEMC00Q0E3LTlGRjctM0M0MTkxNDczN0ZG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTVFRTI4OEUtQTZGNi00NEY0LTk5NTItMEE1NzZEMDk0RjY5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjJCQ0JFMUUtRUYyMi00MkQ5LTlEMUQtNTU2OEQ3OTc5NDZF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjNDNjFFN0MtMEFEQy00QTIzLUFBMTAtREY1NzU2QzVEMEM2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjUxNTQyMzYtRDhBOC00QzRBLUE5NjUtOEYwOTY2OUI3NjVG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDgzRjEwMEQtNUREOS00QjdFLTkxN0MtODI1OEUxNjExREJB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NEI5MDVCNEUtNEIwRC00NEUzLUFCMTMtMTI3MzZBMzJGNUUy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NEQxN0Q2REItODc5Mi00MDZELTg1QjEtRDlFMDYyNTJDNkQ1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTU5OTY0MkEtMEMyMS00MDQyLTg2Q0EtMTVBMEQ2RDg3Qjg4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NUE2QUQ3NjktNkY0Ri00MjdGLUI1Q0MtQjZDMEVCRUMzNkUz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkY1NzFCNzktMThGRi00QzJBLThDQUQtNUM2RTUzQjQ0QjRE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzI4NkU1QUYtODc0MC00OURFLTlENzktMEVENDhCNzYwQkRC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzY1RUJENjEtOTYwOS00MTIyLTk2QTQtNEI2RDgwOTlEODE1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzkwMjE0REMtOEY0NC00RENCLTk5REYtRjE1MkUzMkQ3QTU2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTdDMjkxQzAtMDQ2NC00NDJCLUI4RTItQzE1RkM1MkI4NkYz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0U2NTJBMzEtNzc3Ny00RjAzLThEMkItRDlGM0Q5NTE5NzI4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QUFFRTQ5OTMtMzUzQi00NTMwLTk4NjMtQUYyRUQzQTAyN0ZF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Qjk2QkE5RDAtRTBENy00M0Y2LUE4OTEtQTNBMjI4QjEwRjUz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTI0M0I1MzMtQjhCRi00QzgzLTlBMzUtOTJDREU3N0M3MUIz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTNFMDYxODYtQjdENC00QzJGLTkyOTQtRDlCM0NFMkNENUY5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDlFRjFCOUItNjlDQi00OTlGLUIwNjEtMTdBNjVGMjZCMDAz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MEVBOTM4NDktODI1NS00Q0JDLUIxRDgtNEJGMkU3QTUyMTJB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjRCRjREQjEtNERDRC00REY0LUEzNEYtRkYwOTEwMEVENTQz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Mjg5RDFGNDAtQzI2RC00QzU5LUE2RDgtNDFENjlEQUU4MjNG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MkQ5OUUzNjMtNjg5Ni00RkRBLTgzQUQtMkUwNTRBMDMyRjNE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDJCMUUzMzMtMTNENC00MDY2LTgxMTQtNEJDNTVCNTNBODgy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NEFGQzk0NDgtMUIzRS00RjhBLTkzMTUtRTY4RTI5NzA5NkMz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NThBMTlBREItQURERS00RjQxLUJDMTktMTEwNzVBMkVEQjMx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkIwNkJBQTEtRjhENi00RjUxLTlDNTQtM0JFQzIwRDM2ODNB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OEY1MjYzNzUtRjhDQS00MTU2LUJEQUQtOEVEOTA0MDdGOTYy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0Q0MUU0MzktMTQzOC00NEIxLTg4NzMtQTIyRTI2OEQ4RDMz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTQ2RTEwQkUtNDY0RC00RTQ0LThCNTctNURGRDU1NTg0ODRB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzA5NkJBM0QtOUZDNS00N0RFLTk1RDAtNDREN0ZFNzQ4OTE4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDI0ODUwODktMzYyMC00OUEzLUJCMDEtRUNGOUQ1NDE5RkYx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDZFNUJGMDYtQUVCMC00MThCLUJDRDctRDRBMDMxNzQwQzYx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/REMwQUMzMUItQzNDNi00NDRCLThGNTUtRTc2RDE1MjREMkYy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/REU5NUM1ODctNUMxOC00MUZDLTgwM0YtMDY3RTk0RTg1NTFD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjY2Q0U1QkUtMDQyRS00RjE1LTk4Q0YtRUQyRDJGOTZDMDM3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjczM0NEQzAtRkQ2My00MjAzLThENzMtODdFRjA1Mzg1REM4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RkNFN0ZCQkUtNjE0NS00MzIwLThCNjctNTZBNTNCNjFCNTlF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTgzQTZFMkYtMkNCOC00MkI2LUFDQzItM0M1OThCREUxMjUw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Mzc4MTQ4QzYtMDI3Qi00MTgyLUI0MzAtQUJDMDFBNUVEN0Yx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/N0YxNTQwNzctNDcxOC00RjRGLUIyMUEtMzQ0QTczRTU4QjVB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NEE5OUJGMTYtMUUzRS00NUUxLUFBQzgtODdFOTE2OTBERERC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTNCOUExM0YtRjI3Ny00MDEwLTgyNzAtNEQ3MTcwMDI4NThG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTg2NzdFN0UtMjU0MS00NjA5LUJBQ0MtM0U5QzhBOTU1NjY2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkZDMzY2NzctM0Y1QS00NTE3LUIwRDAtQTdDREMwMEZDQkI5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODUyMUY0RkEtQjMyQy00QUJELUE3NDgtNzc4NDRFRjY5RUJE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDBBMjFBQjctMUNCMC00MjJDLTk0RTgtNkZFRjU5ODU1RThD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTgwMzgyNTUtQ0Q3Ny00MzI3LUI5MjYtNkRFMkVGQjhFQjEx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RUJDQzk3NzAtNzA4RS00RjNFLTk5MDktREQxMkZGRDI3RTEw"
       );
function bacaHTML($url)
{
    // inisialisasi CURL
    $data = curl_init();
    // setting CURL
    curl_setopt($data, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($data, CURLOPT_URL, $url);
    // menjalankan CURL untuk membaca isi file
    $hasil = curl_exec($data);
    curl_close($data);
    return $hasil;
}

echo "No : Nama PT : Alamat : Kota/Kabupaten : Kode Pos : Telepon : Faximile : Email<br>";

for($x=0; $x<=370; $x++)
{
    $kodeHTML = bacaHTML($html[$x]);

    $namaPTN = explode("<td class='tright'>Perguruan Tinggi</td>", $kodeHTML);
    $namaPTN1 = explode("<td class='tright'>Tanggal Berdiri</td>", $namaPTN[1]);

    $alamatPTN = explode("<td class='tright'>Alamat</td>",$kodeHTML);
    $alamatPTN1 = explode("<td class='tright'>Kota/Kabupaten</td>",$alamatPTN[1]);

    $kotaPTN = explode("<td class='tright'>Kota/Kabupaten</td>",$kodeHTML);
    $kotaPTN1 = explode("<td class='tright'>Kode Pos</td>",$kotaPTN[1]);

    $kodeposPTN = explode("<td class='tright'>Kode Pos</td>",$kodeHTML);
    $kodeposPTN1 = explode("<td class='tright'>Telepon</td>",$kodeposPTN[1]);

    $teleponPTN = explode("<td class='tright'>Telepon</td>",$kodeHTML);
    $teleponPTN1 = explode("<td class='tright'>Faximile</td>",$teleponPTN[1]);

    $faxPTN = explode("<td class='tright'>Faximile</td>",$kodeHTML);
    $faxPTN1 = explode("<td class='tright'>Email</td>",$faxPTN[1]);

    $emailPTN= explode("<td class='tright'>Email</td>",$kodeHTML);
    $emailPTN1= explode("<td class='tright'>Website</td>",$emailPTN[1]);

    echo $x+1;
    echo $namaPTN1[0];
    echo $alamatPTN1[0];
    echo $kotaPTN1[0];
    echo $kodeposPTN1[0];
    echo $teleponPTN1[0];
    echo $faxPTN1[0];
    echo $emailPTN1[0];
    echo "<br>";

}

?>
