<?php
$html= array(
           "http://forlap.dikti.go.id/perguruantinggi/detail/M0QwNEYxMzQtQkVGNS00RUUxLUEzRkQtRUFCMUY1NTdDOTVE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDVFRkJFQkUtNzBCRS00MjlELUJGQTYtQzUyRTU0OUU4MkNF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTU4NENDMUYtNjUxMC00NEFDLUE1RjUtODg3MjgyRjg1QTAw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTlGOTM1MDMtNDI5OS00MzRDLTk4RkMtQ0ExM0U3M0MwQTA5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MkE1RDhGMDItMUE2Ri00ODJDLUIyOEItMjExQzgyQkFBMzEx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzRCQzUxRjYtMjVDNC00RkQ1LTg2ODgtMjYyNTBCNUQwRDQ4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/N0ZBMTRGMjAtQ0M3Qy00Q0ZFLTg5QzUtQTg1QkFCOTQzNjBF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDAzNERFM0ItRTcyRS00Nzk5LUFDODItRTA0QkZDRDM3MENG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDUxOUZFOTUtMTRDNy00OTJCLTgxOEYtRTk3NkI0RkY1QjhG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NEYwNkNCQ0EtOUVDMi00QjkwLTk5NDMtNUY1QzU5RTU1MDUw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NURCN0NCQTQtQ0E3OS00OEM5LTkwMzMtNjM4ODlEMjdENzU3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzNCRTlBNjEtRDFBMy00NkQ3LTg3NzQtRDgzQTMyQkRFOTQx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODUyMjM5N0EtOTIyMC00QzYwLUJGREEtMjM4RjExQTY4OEE2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODk4Q0M2MjItNzQyQS00QTYyLTg5MkYtREQ0QjhCRDE4OTU4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUI4MzQ1QTgtNzUwQy00MEFDLTk2QTMtNTA1RkI0MTBEOTg2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QkU3Rjg4NTYtRUYzRC00RjAxLTg1QjktQUEzMTg0QTY0RTQ5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzI4ODlEMTUtQzA0OC00RkU2LUFDNDYtODg3MTZDOTUwQTI4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/REQ4ODFFODYtOERBMi00RjM1LTlFNTUtODdGRkFBN0Q5N0NC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjI3QzExQjUtMUQ2NS00MjJDLTlCQ0YtREUyMkNFQTZDQkVG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RkQ4Q0ZBNTQtNTFFNy00REUxLUFCODUtNjE3M0YxNjg0OEYw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDA4QzFEMUQtNUY2MS00MjkxLTgyM0YtQkMzNzNCQ0U3RDUz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzJDRjc3NjYtMTVDNi00OThDLUI3MkUtOTNDRjBEQzk2NEYw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/N0Y4QzkwQTAtQjFDRS00NkNBLTlCRTQtRjY0ODQwNjVGMEE5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/N0ZGQjFFMDItRTg5Qy00MjBGLUE0QjItQjNGMTFFQ0I4NEUx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTNDNjY2NTUtNEYwMC00NDE2LUJBQTctNTk4MzRBMjVCN0RF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NUMzMTY3MjgtMkUyQS00NDIwLUIwMUQtQTVBRkVGODc3MUIw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODYwNzY1QkUtMEJDMi00MjJFLTgwM0MtMDUxQjNENTdERjk3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OENBQzQ5MzctQjdERS00MEE1LTg1MUEtNjU1NUFCM0I1NjAz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0NCQTY2RDYtOTkwRC00REQ2LTgyMDUtMDRFRTQ5RDFFOEYz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0U3ODNGQTctMDJERS00MTFCLUEyNTQtMEJCN0E2RUQwNDAy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjQ2OTU1ODgtRUUzMi00NERFLThEMzQtMzE1RkU3NzJERUY0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjdDRDdBQTItMDQxRC00NzZDLTgzOTItREZFRTM4M0E5Rjc2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjhGNkZBNjgtMkRCNC00MzdGLThGQjgtMEIzN0Q2QjYyN0M3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QkFBNUFFNTQtQzdFMi00M0MzLTg2RDUtMTQ3OEQ3NjI5RDNG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDNBM0M4QTUtN0FEMC00M0E4LUJBMUEtNEYxNUQyOEVEQzdC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/REZENUZERTktNkJGRi00QzY5LUFFOUEtQzIwQkE5NjNFMkEy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTQ0N0YzMDAtQkM4OS00NDI4LUE3MjEtOEEzNkRGRUFGNTRC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTdBMURBNzUtQjFBNS00OTI0LTlENEMtQjE2NkRDNzM0NzQ1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTg2NkVCMzktNkFENy00MUZBLUEyRDgtRkE2MjIwOTE5OUIw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjExNzMwNDAtQTc3QS00MjZFLUExNUItODkxN0NBQUQ1MTdD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/M0FDM0M4NTAtQTA4Qy00MEFGLUI4NTUtQThEQTFGRkY2NTM4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/M0IwODMzOUYtMkQ0MC00NTdCLThDQTMtQjNFMDE0OTdCRkQ5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/M0QwNTMyOTYtMkI3My00M0FGLTg0MEUtNjkyQTI2Q0MzRDg4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MkQ1NDkyMkItRjg4OS00QjNFLThCMzQtMjc1QTE4MkRGOTFE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzgwMTlGQkQtNUQ5Ri00QkNFLTk1OUUtRkU1RTdFQTA3MjVB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDVBNEM0NjQtNEQxRS00QTkxLUI4OUYtQ0Y1RDEzNTI5NUE3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDczOEY5RjgtREJENC00MzE5LTgxQTctRTNBRDc3RTQ0MzFC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjczRTQ1RUYtQjIxRC00MzRCLUFDQTMtOTg1MDFGQkIyOEYx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzIxMURFQTgtRTE5My00MzE3LTkzOUItRDM0MEQ0OTMwQkFC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODRCMDQ2QUMtMTgzMy00MjAwLThEQzgtREY4RENBNjkyQjAw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUM1MUNCNjItMkUwQS00NDE4LTgwMzctRTVFNzk4REI3NjlF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0Q5REMwMTEtRDkzMS00Nzc5LTkxQ0EtQTEyMzU3RjQ2MTdB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTY5Njc0NEYtNEM2Qi00QTVCLTk4QkQtNkQxOTFBOEQ3QTU3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QUFDMUYyQkQtRUQwNS00MDdBLUEyRTYtQ0M5QjIzM0E1RjIy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Qjg5QUMyMTMtNTBGMS00NUE1LTg0NjUtQUI4NUJFRTM4MTYx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzAxODRBNkItNjhGMC00RDg1LUI5RTMtNzQxNTlEMzc4MTg1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzcwRjI0NjMtRTg4RC00RjYxLUI5M0ItMjUxNkEzNkI4OTk4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDI0NkFBRTMtREYwQi00NTczLTlDRkQtOUMxREJERjhEQkEx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RUU3QjVDMzAtRjlDRC00NURFLUJGQUUtRERGNzFEOEZBQkYx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjM5NEU5QzgtOEY0Qi00MTRGLUEwOEMtQTAyRUQ2QjYwNjYy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MERCOTYzQUItRDE0Mi00OUMxLUE3NjktOUJEMjg3Qjg4REJC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzJENkNFM0ItOTU1MC00MUU3LUFBRDItMjkxMzM3Njk4NDAx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzVCQkRGNEItQzQxOS00QjUwLUJCRDgtMTlGQ0YyN0Q0RkIy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/N0FCOTM1OEQtOEQxNC00MzU0LUJBNUItMzc4RTFDQTAzNTc0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDVGMDlDMTItRkZDOS00NzYzLTkwOUItQTdCMTM5ODhCNjYx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NThBMEYzMjUtMEFGRC00MzA3LThGQ0UtRkQzOTZCQzEwNjc2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkRFREM2NUMtMTdFQy00MzQwLUI3QTAtMEJCQTU5RDVEN0ZB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODM5MUY3RTgtREU3QS00Q0E0LThDNkItMDQ3Rjk3N0E0MUI3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODY0NzcxRTgtMjk4OS00NDhGLUFCNDAtRDc2QkMzRTA1RUVE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODdBMzc5QkUtQ0FFMC00NkRELUI2OUEtMjA4RDQ3ODVBNTdD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTlBRTA2N0UtMzkxQS00M0VFLTgyNjMtMkE5NjQ3MUVDMzk1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUE2QTQ5RDgtMkYyQi00MzcwLUEzMEItNzczRDg2N0NFQkQy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0JCRTc4MDEtMUVCOS00MzAwLUI2QTktQkJFNDc0MTc5QTc2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTZDMkQ3QkUtNjg0MS00N0Y3LTg2NzgtRjQ1RTA1MkNERENB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QUNGQjlCMkEtRENBMi00QTM5LTk5RkEtNkUyN0JFNTRGMjgx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/REUzNUVFMDUtQTE2Mi00M0U5LTlCMUQtNDk1REUzRjlCMzE0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/REY5QjZGNEEtRjJBOC00Qzg2LTg2QkMtMjg3M0E3OUMwQ0M4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTE0MEE1MjAtNjA2OC00MjY4LTgzMTAtMkM0RjgwQkM5QTZG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RUNFMkRGNDYtNDk0OC00RkQzLThFMkYtRkJGNDkwOTg5MjEw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjkyNzNFMDUtOTJGMS00REQ1LTlBMkMtMUVFQUMyQzQ1ODZC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDEzQzQ5NjgtRDg4Ny00ODlELTgzQzYtQkQ4MkZERkEwQzZD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDFCMUMzRUMtNTYxMS00QjhFLTg4MUMtMEI3QUNBOEZBQjZD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDZFQjI1M0YtMkNBRS00MEQ1LUJFMDYtRkY3NTU4Q0VEOTg3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDlGQ0VCOTktRUI3Ny00QTFELUFFRDUtMEMzRkIxRTI0NkI3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MkM5MDY2M0QtNjNCMy00RTY2LTg2MjItQjZEQ0E0MzdFRTk5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzA2MENFMTktMUIwNS00ODU4LUEwRUYtRDIyMzc4MUE1NTQy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzdGMzI4NEEtRENEQy00NDUxLTk4N0QtQTYzQjc1Mzc4Mjk4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NEFGRUQ3MUEtQTVDRS00MTM1LUEyQkUtRjk5NjhDM0M3NjBE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTVFMjdDQUYtQzhCRC00MUZGLUJBQzktMDA5MEU1MkNDOEQ3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzExMzNEMzQtMjMxOS00QjAyLUE0QTQtRjYxQkZGNzgxODEy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzQzNUMxQkQtRjU4Ny00NUE5LUI1NzItQjQ1QzQxN0M4MTZF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODlERDNFQjAtOTFGNC00NDUzLUI0MUItNjE2RUM1NjNCQ0FG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUVCRjVGMDItNjlENC00OERELTgzQkItMDk2RjRDODA1QUMz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjlCQTkxNDAtN0E0Ri00ODhDLTk4NjAtMzlENTc1RDBFRkVG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/REFEOTE0QjUtMDA0Qi00NjlBLUI5MjAtMkUwNTBFN0NCRDMz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/REREMjMyNjMtNzk5Ny00NDY5LUFBMTMtQjM5QTQ4NzAwMkM2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RUM0RThBQkItMTMwQy00QUE5LTkyMjQtNjYxQTYwN0NGQzY1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjU5N0UxQzctNjY4Ri00NDY1LTk3MjctNUI1NzgzRkQ4OTg0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjdBMDMxRDUtMjFBMS00RkZGLTk0MkQtQTg2REMwRkI1MTY5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjhGRTczN0QtQ0EyQi00NTY3LUJFNTgtNkVCMkUyOTk4MzlC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/M0UzRUFFMTctQTEzNi00MjdGLTlCMjAtMkM5NDQwRDA3Nzk2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDIxMjIxQzMtMEJBNC00OUI2LUEwNzUtQTVBQTZGMEJFOTNF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MUI4OTQ5ODYtMjIxRC00RUZCLUJBMDItNDBCMUEyMkZCQ0Y4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjM1NUM2NjUtODMyMC00QTgxLUJGMUMtRjVFMjdDNURFMEI4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjY3QjQxNzQtQzdDNC00QTdFLUE5QzItQjNDMjgwMDIyMURB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDk0MUEzQUItQjE0NC00M0Q3LTk3ODktOTk4MjE3MzhBMzE0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTM0NjlFQTgtRTVFRC00RkQyLUIwNjUtODlFMEI4RTExOTAz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjAyRjM4MTAtODZGQi00NUNCLThEREQtQjZDRENEMDE1OEND",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Njg3QkU1N0ItQTY4RS00MTZCLUJBNEUtMzU5QTdGQ0U1Qzk1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzQwMkU4MDQtMzJGOS00NEI5LTk3OUQtOUNGNjg2OTg5NkI0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODE3QkQxMjktQUNBQS00NkNFLUFBNDUtOTI2RTdFNUU3Nzgx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODNDRkY5RTMtM0Y1Qy00QjhFLUE5N0UtNDUwRThEMzhBMzc2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTA1Nzg4OEYtM0NENS00OTQ0LTlCRjEtNTNFMjAzNTIxQTI4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUQ3MENGMEMtNzQ5RS00NDQ2LTkzNzUtMzM3NUIxRkEwQTM0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjZEREUzREUtRDg2NC00MkJELUE5RUEtRDhFQkI3RDc2NTcx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzVBOThGQTYtQjA5OS00MzhFLThDNzktNjlEMDQxNkFCOUJB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/REM1OEE1MTYtQUU0Ri00MUEwLUEzNjYtMjEwMzA4QjIzQUIz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RUE2MTE1RjEtOEY4OC00NTMwLTkxNDktMEYzREY4NTk0NkU4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjRCMjkwRUEtQzQ2NS00NkM4LTkyODQtMzU2MTcyRUJFRjAz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjUwRjkzRkEtQzAyRS00MTcxLUFFNTUtMzVGRjlGMDYxMDRE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDc4Q0M5NzgtRkIzNi00RUMxLUE2RkQtRTcwRjU2QzM1QTg0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MkJCRUEyRTQtOEU5My00QjZGLTlCQjQtQTQyNDU3MkI0Q0M4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MkVBMjE3OEYtMjEyRi00QTg1LThEMkMtRjE1RTQxMkY1QjIy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Mzk5NzNEODItNzY3Ny00M0QyLTk1MzctQkQ5MTdFM0U2Qjgw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NENDQzA3Q0QtRTUyQi00NDUxLTg5RkEtM0UwNzdGNTM2QzE1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NUI2QjdDRkYtRUI0QS00N0RGLUFGQTktQ0ZFMkFCNEFGNTFC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NUMxNTIyQUEtNEU5Qy00QTAzLTgyMDctMDE0RUIwQTUwMTE5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Njg2MjJDMzEtRUMwQy00QzlFLUE3QzYtNUI3NjEwMzAyRTRD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkY5RERDRkYtMjY3Ny00ODNFLTg3RkYtQTdGQjVGMDg3QUUy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzdBOUJDNTctNTEwRC00REE3LUJGMUUtQTUzMTRCQjVBQzRD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODZDNjAwQzMtRDZBQy00OTEyLTk0MUUtNTA3NTBCMkRGRkZD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTZENjRBNzUtN0Q2OC00MDkwLTlCNzgtMUY5MkQ0N0UxNTVB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjA4RDZCOTktNDdFMy00RjhELTkwQTItNjIzM0E5QkREQzMx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjVGMkI4OUQtOTMyNS00RTlBLUI3MkItRDM2QzkyQUIyRTdF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDBGNUFERTEtQTAyRS00NTQ1LTkwNDUtRTk2QjIwQTM0MzA0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDMzQjcxNDgtMzY0RS00NEJDLUE1QjAtQzUyMDZFNkU4NjU2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/REZCODBEQzEtMThBNC00MEVDLUE2OTItQjA5M0ZERjE1NEFE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RUYxNjY0NTMtRjI5MC00Qzk0LTgzNkQtRTJFQ0NERDREODM3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjJGQzYwODItREJFRi00RkY3LUJGNjItNTFEQkEwMDQ0OTk0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RkVENzAwQTctNUVBOC00Rjc5LUFENTQtMzJBREM0MTA3MjU3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjAyRTk4MzktQkY0OS00OTEyLTlGNzgtNjgxMkE4Q0QwODdB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjkxQjM0NDUtRjcyOS00RTVCLThDNjMtRTMyNkJGMEU4RjNE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MkFEMEM2REItNjZFNS00Q0VDLTk2RjAtNzc4MDEyQ0NGRDlD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MkVFNDM4N0UtNjVDQS00QjQzLUI5OUUtRERGRUUxMkE5OEFD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzU2QjZGMkMtQjdFRS00Q0JCLTg2MDgtQjNEMEM1NjIwQUE0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzcyNzU4NEYtMTZCQS00MUU1LUI3QTQtM0Q2MEY2MzhBNzZG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDQ5MEE4NTMtMjYzOS00RkUwLUJERkEtN0Q1N0NDNUFGQkJF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDk1NEFEQkUtOURGMi00NzMyLUIwMEItMzBDRjI4NzNBQjg2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkJGNDIwRTctM0Q4NS00MTNFLUEwOTEtMkM1NTJCOEE5QkUy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODFGRjlFRTQtM0NCRi00NjUwLTgxNEItRjgzM0MxQkFDMDdD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODM2ODRCODktMzQ5QS00MEM3LTgwOEQtNDVBMzQ0RjM1QjY0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTQ3MTUyRTAtREVENC00RjMxLUJBNEYtMjhFMURBQTA0NEVG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTU4MjE5QjgtMDIwQi00OEY4LTg3QzUtMzc2OUI1ODQ5NEUx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/REU2OUY2ODktNUMzOC00M0QxLTkwOUEtMENGMzY1OThDRTA2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/REVENDU2NjUtRDgxMC00QTg4LTk3NTEtQTYzRjc4MEZFMjNC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/REVEQkE1NEUtMkVCOC00NjE5LUI0ODktRkE0NjIyMTMyNjIz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTIwMTJGNkQtRjE3OC00MzM3LTg2QUUtREVFOTY3NDAzNjc2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTQxNjJGMUEtQTMzNi00NjVBLTgyRTQtRkY1NkE2RTc5NjND",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RkY2RjU0MzEtQThDMi00MTVDLTk4MzEtMkMxNDJCRDBCODYy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RkY4Q0YyRDctRTdBQS00NkQ4LUFEQjAtNUFDOEMyRTQzMDM0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDg4ODFBRUEtMzEyOS00RjgxLThGMDUtRDAzQkEwQTZDNUUx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTI4QkZFQjUtREU4RC00MUVDLTlDQjMtMDM5OUNDMzI1OEI5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTdGREEzNTEtRTYwMi00RkE4LUJGMzktRkM0MjE0MEVEOThB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Mzc3NzdENkUtOTk0OC00QkU1LUE3Q0MtMkUzRTFCQjhFNTEz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzcyMTdBRDQtMTYzNS00RUE5LUIxMjUtMjgzRTAxRDc5MzE3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDMzMDgwNzQtMkMxQy00QjI5LUFCQTAtMDUxRjdEQTVEOTM1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDZBQ0REMDItODcyMC00M0E3LUJEQjctRjUyQkU2NkZEQkU2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDdGMzhFREMtRDgxNC00QzE5LUE1RTctNDhBMzdCMzY0RUJF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NEE2NUI3MUYtNTQ3Ny00MkJGLTgyQjgtODQzMkNBM0ZBODNE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NUVCRTE4MEItQTYyMS00MzRFLUE5MkUtMzhFREVBNUE0Nzkw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjU1NUIyNzQtQzk4Ri00MEE3LUIxMjMtNkRGODkyQ0VENDlE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzlDNzc1QjgtNjk4RS00MjAwLUI2NUItRTIwMzQ2M0ZFNUQ0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTczRTQ2MjMtODQyRi00OTlCLThBNzQtNkU1OEM5NzM2QjlD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QUFBRDBCMkUtM0VDOS00MDEyLTk2ODAtMjJGRDRCQjBEMzY4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjdGNTM3QzMtOEIzRi00QTIxLUEzQUUtMDgxRUYxNkMxRkQ1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzJBOUZDQUUtQzYyRi00MjkwLThBREUtNEJGODA1MDcyNUQ5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/REM2MzRFNjItRTI4MC00RDJGLUE4OUEtNzNFNkFEQzAxMjA5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjAwOTUzRTctMjc4NS00QzRELUFGRjEtMEQ0MzY5OEJFN0Qw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RkE5OERDNkYtMkI0Ri00NDAxLUExRDQtNkVDMzM2N0Y0Mjg0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RkQzRkIzNjctOTU4Qi00NzVCLUFDRkUtNzBGRjM5OEQ1Mjk0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTdEOEQ4NEEtNEYzQy00M0EwLUI3MjItRDRCRTg0ODkwRTdF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjBERjFGOEQtNDI0QS00OERGLUFGMzItRkU5RjIwQjM1Qjc5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjE2NzVDMDYtMThFRC00Mjg0LUI4RkYtNzkzNEM1NjM4MzNF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjUxRDIzMzMtOUVEMC00OTlFLUFBMzgtQ0YyNDQxNkY5QzU3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzgyOTdEQzgtMzIxRC00QjAxLUI5NTUtNUIwM0QxRTRFRTE2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/N0U1ODVGNjUtREQ1RC00NTNBLUJBMzMtRjUwRjk0RkUyMDFB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDQ3Nzc2NEEtMzAzMy00OTFBLUJDODctNUU2MTlERDhDNjU2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDkxNEYzN0MtNkYzOS00NThGLUI3QTItQTFFQjcyRkNCNUUy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjU1MjI5ODItNTUxMy00OTRCLTlBOEYtRkMzNDQ4NDMwMjhG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODM2REVFRjAtOUVCQS00MTVELUIzNjYtOEJCOEM5NzI2RDI5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTg0RDZDOTUtMDU5RS00OEYxLUI5REUtM0MwRTQ4OEM3NkE2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTk1NjhEMzgtNTFDMy00M0NFLThCMjMtQ0EwREI4OEUyOEFC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTk5MTYxNUYtQjYwNC00MjE1LUE4NDEtRUI4QjkzNjQwOTQ3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QUY3MjBDRDMtREZBNi00MTJDLUJGMkYtMkQ3RDA5NzNCMzk1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjAwNDgzMjYtRENBQS00OUMxLUJFNjUtQ0U0MkFFRjk3MDc5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjhBRDBGRDAtMkVFQy00RjU1LTlGMDktQTRFOUM3NzZCMEY4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzNBNTkxREEtQTM1My00OUM2LUJDNDctQ0E0NkZDMDcxNkI4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzQwMDAwMzEtMzU4OC00QTNGLUE4MDQtNUJCQjFGQzBDQjRE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDNGNDJFRkQtNUY4Ni00REI2LUI2MTUtMjJBOEMyMTc2MDkx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTZCRjVGRjMtMTk3NC00MENBLTgwNDYtOTczQTRFRTZDN0U5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDIyMTgxN0ItREUyNC00OUNGLTgxOEYtMzQ4MUUxQzlEMTRG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MEIzQjQxQzctOTgwQi00NzEyLTk5MTYtQUM4QTE3M0U2RDE3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MUVDNDE3MjgtMzNDNy00NTczLUIzMUMtM0U2OTc2MDEzNzc0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjYwMTJCOTktMUY5Ni00NzE2LTg1RDEtNzdERDkxRjVGMEIz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzU1RUEwMjUtOTFGQi00NTRGLUEzODktRjYwRkE4MzA3QzhG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NEU2REEwRUQtNTdDOS00NjZDLTk5NzMtRTFGMTg2MTU1OURD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTIwMURDOTMtNTA1Ni00M0FCLTg0MjQtMjVFMkI1MkYxNjI2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NUFBRTMxRDgtREQ2OS00RTVBLTkwRDYtQzUzQUFBNjBBMUQ1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjBERjI5RUUtNkFFRS00NzM1LUIxQ0MtNTU2MjY5N0U3MTJB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkEyNEVBRUUtMDM3NS00Njg4LUFGQUEtM0U3NjQzNTFGRTdD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkQ3MjRCODQtRjhFRS00NDk5LTlBNkUtNEE2MEYwNzZBOTk4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODQzMzM1N0QtQzkxNS00OTExLTk1QkMtNThDMjI0MkQ4NzAw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUQ3ODc4OTItQTY0RC00OUQzLUI2MjctRkQ1MTdEQTQxRTEx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0FBREFFOTUtQUU5QS00M0VELUE3RDItREJEMjIwMDQxMTND",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjA5MEZBMTAtNThFMy00QzhDLTk0QzEtMUI4MzFDMTVGOTdE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RThCMzBCMzktQzc4Ny00OTVGLUE2MzEtQzgyRUI4RTI5MDE3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjEyODlFREItNTE5MS00RDdDLUI5NTgtNDYxNEQxODFERjkz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjFEOUM4MjItMjlEMC00QTQ3LUEwMzItMjBCNDNGNzgyNjg5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjFFQjJBMkEtMjFDNS00NjczLUI5QUQtNzM5QzhDQ0VDMTY2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RkIyMDRFMTQtQjk4NS00RkY3LTk0NkUtREY0RjgwNzlBRUU5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDc5MTU4RjgtMjM5NC00MjJELUIyRDktRjhEMzQ1QUJENDYw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDkzOUJDNjItODU5Ny00NjBFLTkxRjAtQzRFRjY4NzkyRTI1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MEM2RjI4ODAtRTI1Ri00RUMyLUI1OTEtODdERUI5MTE4QzE4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTE0OTI1ODgtOEExMS00NzJBLUE2RDktOERCMTg2NzIwRjNC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTFDRjdCNzktRTkzQS00NkFCLUJCMzItMkQzMkUzQzBERkRD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjIwRkE0RTItQkRENS00OUMxLTlDRDItODNFQzlFMUM3ODBB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MkQ3NTdCN0MtMjYxMy00RDA0LTg5RkYtMEM0OUQzNzgyRDk0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NUU3MzI1NDgtQzBCNC00QkIyLTg0RkUtRkQwRTkwMTQxM0U3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODAwRUNBNjAtMzNDOS00MTkzLThCMzEtNzk2NEI5QTIwMzg0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OEFCNDg2QUQtNTI3Qy00M0YxLThGN0QtRTkxQzgzNjJCOTc5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTZDNzU0NTgtNDJFNi00MkFFLThENUMtNjJFQ0YyMEIwOTlD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QUQ5NUYxOUItM0ExMy00Q0ZBLUJBRTgtRDVDQzhGNzdENEQ4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjAwQzY4NzQtREExNC00N0ZGLUFBODItQzgxRTNCMzhGMzky",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjdFQzZGMDAtQkNGNy00QTJGLThGMjYtMTFFMzlGMDNCRDAz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Qzg2Mjk1MEMtQTVDQi00ODlCLUIwMDYtM0YwRUREREY3MkVB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Qzk4NzZBQ0MtMkQ0MS00NzYwLUJCRjEtQkRFREVDOEI5OTQ1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzlDOEEyNjYtOERDRC00RDU4LThEQjAtNDFBOTBGOTJFMDIy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDA1MUQ1NzYtMjNBQi00MDE0LUFDODEtRkRBNDAzNjU5RTQ0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/REE2MjEwNjMtQzYwRi00N0E4LThBQzktQ0FCQzZBQ0REQUY2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/REI0N0M3QzYtODY0MS00Q0M3LUFCN0QtMEU5OTdGODk5RUE1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/M0QxRTZFNkYtRUJEOC00NEZBLTkxREQtQzJGMTg2RkQ5N0ZG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MEQwQTg3OEItOUUzMi00QjZDLTg2MTgtM0MzOEZCQzRCMTNE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MUI1N0VENjgtOTNBNS00MEUyLUI5N0ItMjM5RjY1REJBOUQz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MUVGQzFBRkQtRkU0Mi00NDc3LTlFOUYtRjQxQTA2OTY2QkIx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjE4MjlBRjgtRUVCRS00M0QwLUFFNDMtRTI3OTQyQTgyMDg3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/N0FCRTk0MzEtNjczQS00QzhGLTlBMzItNTgxMjBCNjlEMjA3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTA0Q0Y1NzYtNkFENS00REY2LUEyOUUtQjgyQzk0MDg0MEIy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjM3M0Y0NzMtNDI3NS00NkNBLTgyMjctMTUzNEY5QzI1REQx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkJCNkQzRjEtRjdEOC00NzE5LTk0MkQtMjlFN0JBOEI3RDE0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkQ5QkJBOEEtMjBBOS00NzM4LTgwRTItRkZDMDk0NUVGQUYy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODI2OTVCOTAtMDcwMC00MjY3LTlEOUQtRTc3QTQzMzZGMzM1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODlFREQwMzItMEU2NC00NEY0LTkzNDctNUREMzYyQ0IyRjM2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTMwRTIwQzAtQUIxQi00QjAwLUFDMTEtMjQzMDFDOTI3NERG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTk2NkU1NkQtQjk4RC00QTE1LUEyRjEtQzkxOUI3MUI3NDM5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0U3NEMxQUItNEQzMS00NzRDLUIxQzQtRUVBNDBBMzU3M0I2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/REUzNUQwQTQtQTcwMC00MzJBLUFENTgtRkMwRkEwNjZDODlC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTI3QUVDM0UtNURFRi00NjNELTlFN0QtMDJGNzVGMzYzNTM0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTVDQzExRDktQkU2MS00Mzc0LThBRTctODFEMjA3MDc4QUFG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTZEQTcxQzUtQjhDOS00OUIzLTlGMTQtNDE4MjgwNjc2MDc4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RkQ1OTYwQTctMDlDRS00RUQ4LThDMEUtQzhGMDQwMjQzRTg5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/M0I0RUE2QjktMzgxQS00M0RDLUJDMDAtMzMwRUIwNzZGQUYz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDY4NEU1OTgtREQwNy00MUNFLUI4QzAtOEFGQTkwODc3MDIx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MUQxRDcyQkUtODVGNS00REE2LUIxOTItQjFBNTZDRjdFRDhG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjQwNEQ2OTgtRjQ3RC00RjExLUI0MDctOEFGMTk1MTE3MDUz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Mjc1QjQ5OTctNUQ5NC00OUZDLThFQTEtRjhCQzNCQjAzODBB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzBFNUZDRjQtRjFERC00RTZELUEwNkEtQ0ZCOTZBQTgzODc0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzY1MEU2MDktMURDRi00NTYzLUJDMTQtRTQ4NUI2MzFFOUQ4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NDcwRDE3RTQtNUJEOS00NTAxLUJEMzQtMEQxQjlCMDFCOTg2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NEEwODJENjUtMUZCRi00MjZBLTlBOEUtQURCNzQ1QTk2MjdB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTRGMzFEQTMtRjRDMy00MDMzLUEzOTQtQjZGQUJCMzg5NEUz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjFGMTRGMjQtMzM4Qi00QkJELTg3NjAtQTg1MzkxOEREQjBB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkM2M0E0N0YtNUNGQy00QTQ3LUE3QkUtNjZCNTFDQzAxMUI4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkMyNTVGOTctNjA5MC00OTU4LUFBOEMtRTkzRDg1NDBEN0My",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkUxODY3ODEtNkMzNS00MTc5LTk5M0MtNTkyNTFFQzU4MTMy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTcxM0UzNzctMjBBRS00RjEyLUExN0YtMEZBRkE2Mjk0MEIy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0RENDExNjEtMTlCQS00REIxLUFCRjQtRjRGQkE1NTIxNDRG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTdBQUQyMTUtMzkyQS00RThFLUE4MTUtRTQwQ0NGNjk0NkI0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDBENzMzQjEtNDRBNi00MkY0LThEQjYtNzdFQTA4OERFODc1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTQ0NTZCNjItNzNERC00QjhGLUJGNDAtMjIxMzJDNjUzMjk5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjlEN0ZDMTYtRDE4Qy00Q0M3LUI5RjgtOUQyOEY2NDIzMDQw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/M0NDOUE2MkYtQ0JEOC00QzI1LTk1QjgtRTJGMUI3RDdGQzgw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDU5N0Q1RTMtRjM3OC00Njc3LUI4MTItNEE0MzExODREMDVG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MDk5MkFBMjAtMzFDRS00OTNELTkxQ0YtRjQ3RjE5QTkwMjJD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MkIzRjRCOEQtNUY2RC00MUQ0LUI0NDktNEVBN0M1RTA0NkI1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzFBMDY0NDgtRjJGQi00MUUyLTk4MTgtQkQzQzM4MjU3MkE4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/N0QzQUNEODItQjRENi00RUQ3LUI5MzAtRDk4NkQwODkyMjMw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTU4RkREN0UtODUxQi00M0ZBLThFQTUtMTREQzI1RTFFMjhE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjdBQjRDOTQtNjM5Qi00QTk1LUJBODMtRDVDNUI5QjE5MThG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjhDN0E1RTktRTdEOC00RjAxLTg4NUYtMDM2MzBDMTMxQjdB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzFFMjQ1RDAtQzdBNS00QjlDLUFCMUItOUVBREE4OTQyQTY2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODA1NjM5NjctQjNCRS00QzExLTk3RjAtODJGQ0Y2QUNEMTcx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTk4MTQ3MzEtN0Y3QS00MkRELTkyODgtREIxMUVFNjhBODNF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUZEN0JCNDAtOTkxMC00NDlGLTg2QTItMDc3NzE4OEQ1REYz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0NGMjdDNjctMUU3RS00QTE2LUE3NEQtQUQwRkMwQzEzNkJF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTFDN0JDOUUtQjUxQy00REI5LUEyQTAtMDBGMzc0MkI2MUE0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTg4M0EwRTYtQjNDMC00OEMyLUEzOUQtNDIzNEJFMkQxQkM4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDI0N0NGQkItMTBFMi00RjFBLTgwM0UtMzgyRURBODVEN0M0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/REI1QjZCMDgtMkY1My00MjZBLTk4NUYtMzEwQTU1MjY5QTY5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTlGQjA1MTAtMzcyOC00RkZELUI5QzMtNjUwMTVBNUEwNTVF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RUZDNUQzODgtOTc5Qy00NjdFLUJDQTAtQjg5MEQwNTI0NUE3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MEU5OUU4RDAtOEE4MC00NENFLUE4NUEtNjRDRjJFREU0MEM3",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTM2QzY4OTgtQ0IyQi00NDY4LUEwQzgtNzk4MDI1QzUwRUJF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MURCN0VEOTEtMTVBNS00MzVGLUFBNzktQTdCNENDMEUzNUM4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjNBOTBBOUQtNEYxRi00MDk0LTlBRjItMDk3Q0E5NTYzRTcz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Mjk1MzYzMDAtQTRBMi00NkU1LUIwMTEtRTMzODA0OTA0RTFE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzUxMUU0M0ItQ0ExRS00NkVCLUE2QjItMUYxRkE3RjE5MTk0",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTUxMjMxOTYtNzA0Qi00NDYzLUIyQjUtODFBMkUzMEQyMUU1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NUE2Mjc1QkUtNjdGRS00Q0Y1LTk5NkItNThBQURGQUJFNTU4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjQ1NDRCMDMtQ0Y4OC00NzlDLUE4MUMtOTkwMzUxQzMyRDRD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjQ4NEY2Q0ItODUzMC00MTY0LTg5NDktNjkyRjE2OTI4ODZD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Njc1MDc4MEUtRTk5Ri00MEExLUI2MzEtMTQ4MDE4QTc2OUU5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTEzRjk0MzctODM5Mi00MzEzLTk0MjctQTQ0OTkyQjZBRjI1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUREMUYyOUYtMzEwNi00ODQzLUEwRTUtOUYwNjEwQzE3MkVC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzBENDE5RTQtMjQ0OS00RjhCLTlFNzctREZDMzM5RjgyNERF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/REIxMTZFRjItMUE4Ri00MThDLUFERkYtRTFFNDM4QTUzMzg2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTU1OTM1RDMtRTYyOC00Q0Y4LUE5OTAtRUM3MTlBQTk4OUVD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RUNENTEwODQtQjQ2NS00NTAyLUFFNDAtNUU5NzQzQzQ3NkFE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RUY1RDY3OUEtNzQ4OS00Q0YxLUJCNTQtRDA3MTFFOTVBNjA4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjE3RDA1NDEtRjBGNi00RDhFLUI1MTEtQTg3NjcwNjQzRkFG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjVDODQ4QjktNDZDMy00MjExLUE3QzQtQTMxNjkyNDU4OUNF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/M0ZBNUJFMzUtMDVCRS00RDRFLTg3QjUtNDEwNDI2MDRDQjAx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTFDREZDRDYtMjJGNi00M0FCLUEyQ0ItMTFENEI1NUVFRDE5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MjVEQkU5NTItODI2Qi00RTVDLTkzMkMtNDI0QTExOERGMTIw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NUNEMkMwOEYtQkUwQy00QzExLTlBQjMtRTRBODIwQjVDNTgx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjA0QUZERDEtRThFQi00MkQ4LTg5NjEtMUMxM0NFREVCODlB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjRBMjc4MDktRjRFMi00NUMwLThBNzMtNjVDNzU4OEVDQjk5",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjRFOUJGRTUtNjk0MS00OEY0LThBRTAtQTlEQ0Y4ODE2REJF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkU1QkZDRDgtQkE3OS00NzM5LTk4MkItRTU0MEQwMTM4NENE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NzA3RTc2OTQtRTcyNi00MzExLUE0QjktN0QyRUI2NEU3MUZC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OEI4MUIwNEQtM0U2Qy00NTMwLUFBNkItNkQ1MzBFODNDMkQ4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/Q0YxOTgxMjgtRDA4Mi00QzdELUEzRTAtRDAyMEQ0RjYxRkMx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QUM1OEUyQjItMTFCNS00QzQ2LTkxQkYtNTIwREIwOTgzOTQ4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QkU1MTA0REUtQUJDQy00Njk4LTg2M0ItRkIzMDdBRDQ3OENG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzJGRTc1NDYtMTBBMS00M0YyLUEzOEEtMDAyQ0QxN0IwNkZF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzY3MTIxRUYtQkNBNC00RjQxLUI3MzMtNjRBNkQzNDlEQzZF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzgzNkUxRUMtRTk1Mi00NzFBLTgxOTUtMENCRjU4ODcxNURG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDJCQURGQTQtOUI0Ni00RUFCLTg3MUItNjlFNzY5REI1MDBG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDM5RTVBNUItQkREMC00MkIxLUJGMDctNzdGRTA0OTZCQTYx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RTNGNzc3NUQtRjNCMS00NjY4LTlFRjItNkFGMjlGMzgxRTMz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RkYxMDlDMTQtOEVBMy00OTU0LUFDQzAtOTc3RDBFOTYxMTQz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTQ2MTNDRTYtNTVBMy00RjJELUE0NjUtODRGQUI4RUZERDQz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MTdCRjAzQjUtMDZCRS00OTE3LTg4NEQtRjM1QUZGMUE4QzdF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MUVFQ0Y1NzctMTI0MC00RjEzLTg0NTUtQjc2MThGMTNCNEYx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/MzM2RDY3MjMtOThFMC00QjU3LThGNzAtNUZCNDA5Q0I2Qjkz",
           "http://forlap.dikti.go.id/perguruantinggi/detail/N0NCOTY0NjEtRUREQy00OUNDLTg2OTktQTEwMTkyMzExRTkw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NEE4RUY0QzEtODkxQS00MkQxLUFFRjEtRTlDMkFGQjc4OUI2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NTM2NjYyMDAtQ0ZDMi00MkVDLTgzQTgtNjc4MDI5NDNBMURG",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NUJEMTQwREYtMEE0Ny00Q0Y3LUI1QUItMjdGNTU4QUNFMERC",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NjE4RTBERUItRUYzQy00RUE5LUJCREYtMjdGQUIyMjQ0QjVB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODdBNTE0ODgtQzBDNC00Qzk4LTgxODItQTlBNjdDNkNBRDAw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODg0QkFDMzMtQ0UxMi00REUzLUIzNEMtMzExRkQwRjdFMjE2",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OTZBNTQwRTgtQjBDMy00NEE1LUE1MEItRkUyNzE4Qjg3MUE1",
           "http://forlap.dikti.go.id/perguruantinggi/detail/OUYxQTNDMkEtRkI1MC00QTlGLTk0N0YtRjY2QTU3NDRDNkZD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QTg1M0RCNTktRTFGOS00RTVGLThCNzUtOEFDRUNDMTRENTZD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzQzRDU5MTctOUZDNy00NzA4LUJCQjgtMkUzMkIyMDNEMEFE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QzUxRjE2NkQtMDU1Mi00MjE0LTgxRkUtQjFBQjc1MzVDNjBD",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDBERDQ4RjAtMzdBNi00MTc3LThGMEItRERDQjFFNzVBQzQy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDZBNEU4QzUtOURBMy00RTcwLUIwNUQtOUMyMzE2MDUzMTIy",
           "http://forlap.dikti.go.id/perguruantinggi/detail/REMzNURFNkQtQTZCQy00QTQyLUFEMDktRDdFOEI4QTA0NzMx",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjRERTgyNTctODAxNi00RDA0LUFDNjYtMTgyNEYxMzE0MUE4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/N0Q2QzJGQzItRjNBNC00NDk4LTlCMjUtRDg3QkJDQjI3MkVF",
           "http://forlap.dikti.go.id/perguruantinggi/detail/NkYzRkFBODEtMTg1MS00QkFGLUEwQzMtNTJFOEE1MERCRkNE",
           "http://forlap.dikti.go.id/perguruantinggi/detail/ODc2MjQ4OUUtOTlFOS00REZFLUE5NEQtMTMyNjZDMjcwQjdB",
           "http://forlap.dikti.go.id/perguruantinggi/detail/QjhCMEU5Q0MtMEE0Ni00RDY5LUE0OTctQzc2MjNDOTI3MDM4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDM1MjFFMTgtM0QxQy00RTdBLTlGMDEtMjBFNTM5MDBDREQw",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RDUxMDVEQzItQjVGRC00NTNBLUI3ODQtNzI1QzE3RkRFQTg4",
           "http://forlap.dikti.go.id/perguruantinggi/detail/RjZEQUUzQUEtMEY1QS00RjY1LUEzOTctOTBGQUFFQUZBODBC"
       );
function bacaHTML($url)
{
    // inisialisasi CURL
    $data = curl_init();
    // setting CURL
    curl_setopt($data, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($data, CURLOPT_URL, $url);
    // menjalankan CURL untuk membaca isi file
    $hasil = curl_exec($data);
    curl_close($data);
    return $hasil;
}

echo "No : Nama PT : Alamat : Kota/Kabupaten : Kode Pos : Telepon : Faximile : Email<br>";

for($x=0; $x<=366; $x++)
{
    $kodeHTML = bacaHTML($html[$x]);

    $namaPTN = explode("<td class='tright'>Perguruan Tinggi</td>", $kodeHTML);
    $namaPTN1 = explode("<td class='tright'>Tanggal Berdiri</td>", $namaPTN[1]);

    $alamatPTN = explode("<td class='tright'>Alamat</td>",$kodeHTML);
    $alamatPTN1 = explode("<td class='tright'>Kota/Kabupaten</td>",$alamatPTN[1]);

    $kotaPTN = explode("<td class='tright'>Kota/Kabupaten</td>",$kodeHTML);
    $kotaPTN1 = explode("<td class='tright'>Kode Pos</td>",$kotaPTN[1]);

    $kodeposPTN = explode("<td class='tright'>Kode Pos</td>",$kodeHTML);
    $kodeposPTN1 = explode("<td class='tright'>Telepon</td>",$kodeposPTN[1]);

    $teleponPTN = explode("<td class='tright'>Telepon</td>",$kodeHTML);
    $teleponPTN1 = explode("<td class='tright'>Faximile</td>",$teleponPTN[1]);

    $faxPTN = explode("<td class='tright'>Faximile</td>",$kodeHTML);
    $faxPTN1 = explode("<td class='tright'>Email</td>",$faxPTN[1]);

    $emailPTN= explode("<td class='tright'>Email</td>",$kodeHTML);
    $emailPTN1= explode("<td class='tright'>Website</td>",$emailPTN[1]);

    echo $x+1;
    echo $namaPTN1[0];
    echo $alamatPTN1[0];
    echo $kotaPTN1[0];
    echo $kodeposPTN1[0];
    echo $teleponPTN1[0];
    echo $faxPTN1[0];
    echo $emailPTN1[0];
    echo "<br>";

}

?>
