<?php
$prodi = array(
			"http://forlap.dikti.go.id/perguruantinggi/detail/M0RFNzMxNjYtQjlFRS00NkI5LThCNDMtNEVBMEM1MDVGMzgy",
"http://forlap.dikti.go.id/perguruantinggi/detail/MDI1RUZDQTgtMEYzMS00RDY2LTgxMkEtMUZCREMzRDIyNkRB",
"http://forlap.dikti.go.id/perguruantinggi/detail/MEEwOEU2QkYtODhCRi00RDlFLTk2NDItNkI4NDdEMzhCNTBG",
"http://forlap.dikti.go.id/perguruantinggi/detail/MTM1M0MzOTEtMENBRS00MkIwLTlERkMtRjlDQzBENTExRkRE",
"http://forlap.dikti.go.id/perguruantinggi/detail/MjgzREYyNjUtODU0MS00ODI1LThERjMtNDBENEI1MUQ1MkE3",
"http://forlap.dikti.go.id/perguruantinggi/detail/NDg2QTU2OTUtQ0UxRS00NTZCLUE5RUMtM0QyOEVFMDdBQTY0",
"http://forlap.dikti.go.id/perguruantinggi/detail/NEFFNDYzQUQtQzE5Qy00RTg3LThGMTktMkI1RUE1NUNENTYx",
"http://forlap.dikti.go.id/perguruantinggi/detail/NERERThDMTYtMEU2My00NjIwLTlERTgtRDZERTc0RkMwNDdE",
"http://forlap.dikti.go.id/perguruantinggi/detail/NkRFOEI0OTgtNUQyQS00RTY1LTlCODItQThEOUMzMzU2OUUy",
"http://forlap.dikti.go.id/perguruantinggi/detail/NzIxQ0I4NzctNTg0QS00ODg4LUEwRUEtQzI4MzEwQ0M0QzNE",
"http://forlap.dikti.go.id/perguruantinggi/detail/ODIwMEFEQUYtMzFCMy00RTAxLThGMUQtNzE3MDE0RTcwNkFC",
"http://forlap.dikti.go.id/perguruantinggi/detail/ODQ0Qjk1NkQtMDIwQy00ODA3LTlDMkItQkI2RkE3MTQzMTg4",
"http://forlap.dikti.go.id/perguruantinggi/detail/OTY5MUM5Q0QtOUQ3Mi00NEFDLUJGNEQtRkUyMTRCQzk4QTUy",
"http://forlap.dikti.go.id/perguruantinggi/detail/QjNFODI3MDAtMTU3QS00RkExLUE0M0QtNkFENkE1RTBDRjlB",
"http://forlap.dikti.go.id/perguruantinggi/detail/QkEyNTFBQzQtNjlDMi00MEVFLTgwQkUtRTBGMjkyM0JBN0I2",
"http://forlap.dikti.go.id/perguruantinggi/detail/QzRDRjgyQjQtODk0MS00MDRDLUFERDgtMDdEODZDMTIxMkJF",
"http://forlap.dikti.go.id/perguruantinggi/detail/QzVBRTBDOUItRTBBRS00QTRDLTk3QzItQzA2RDEzQTg3MkVG",
"http://forlap.dikti.go.id/perguruantinggi/detail/RDFCOThDRTMtNUZGOC00NzVCLTgxRTgtRDY5MjJCN0MyQTY3",
"http://forlap.dikti.go.id/perguruantinggi/detail/RTQ4MThFQ0MtMDYyNi00OUI5LTk5RUYtNzVFNjMyQzg1RTc2",
"http://forlap.dikti.go.id/perguruantinggi/detail/RkUxMjc3RTUtRjVBRC00NTFGLUI3RjUtNTNDNjVERjFBQThE",
"http://forlap.dikti.go.id/perguruantinggi/detail/MDYxRTdFQ0UtNDVGNy00QzY3LTg3RUYtRkM0NjdGQzE3MDE0",
"http://forlap.dikti.go.id/perguruantinggi/detail/MDcxRkQ3NjktQTQ1NC00MEJBLUE4MjAtNTI4NzkyMzRGRTBB",
"http://forlap.dikti.go.id/perguruantinggi/detail/MTkyMzI0RDItMDU4OC00NkVDLUJDRjMtMEUwRkMzNDhGRDk1",
"http://forlap.dikti.go.id/perguruantinggi/detail/MUZERTM0MDQtQTcwRS00MzY0LUJGNzQtNjFGNURFMDdDMUFF",
"http://forlap.dikti.go.id/perguruantinggi/detail/MkJGMjE2MkEtRkQ1My00OTEwLUIwRTAtQTBGRjVGRkMyQ0U5",
"http://forlap.dikti.go.id/perguruantinggi/detail/NDk3OUU5RTYtOTk1Qi00NDA5LTk2OTEtNEJBREI0NUNBNUZB",
"http://forlap.dikti.go.id/perguruantinggi/detail/NTU0OEYwQjItNkNFNC00RDcwLUFEQzMtRDlGRjkzNDdFRjlG",
"http://forlap.dikti.go.id/perguruantinggi/detail/NkQ1NDIxOUEtRjQ2OC00RkU5LTlCOTktRTI0Rjc5QkVGMDk2",
"http://forlap.dikti.go.id/perguruantinggi/detail/NzE0QjFBNUYtMUQ2QS00OUIyLUE1NzctNjQ3MzJBOTQ5RDFD",
"http://forlap.dikti.go.id/perguruantinggi/detail/Nzk4NjI4QzAtMDZCOS00NDkwLTg4MjQtOTNDN0ZFNzE2MzY2",
"http://forlap.dikti.go.id/perguruantinggi/detail/OEE4OEFCMjctNDY0MS00MjM5LUE5RUUtQTQ4RjkyMjQ1REYx",
"http://forlap.dikti.go.id/perguruantinggi/detail/OTQ1MjQzOEEtQjM1My00NjlDLTkyNzEtQzM3OTgzNDUxRjQx",
"http://forlap.dikti.go.id/perguruantinggi/detail/OTlFOTI2QjItMzQyMi00REFCLUE5RjYtNTQwODQzMDk3Mzg1",
"http://forlap.dikti.go.id/perguruantinggi/detail/Q0M4QTBCQ0UtMUIwMC00Q0E2LTlCOUItMUY0MUM3MDA3RTkw",
"http://forlap.dikti.go.id/perguruantinggi/detail/QzJFNDJGRDQtNDExQy00MjQ4LTlFOUYtNDJFMjFEN0M4MUZE",
"http://forlap.dikti.go.id/perguruantinggi/detail/RDYwMTU3RjgtMTAzQy00MTkyLUJGRjktMjAzODNGNzc5MzRB",
"http://forlap.dikti.go.id/perguruantinggi/detail/REE5MjlDOTktMjBEQi00OUIwLUFFMUMtMTNDMTNCRkFBMjdE",
"http://forlap.dikti.go.id/perguruantinggi/detail/RTk0RTA4QzgtOUNDRS00MkI1LTk3ODUtQzY4MjBENTU3RTU0",
"http://forlap.dikti.go.id/perguruantinggi/detail/RUQ5QzdDNTItNTM4MS00QUVCLTlFNTUtNUZDQkEyQzk2QTIx",
"http://forlap.dikti.go.id/perguruantinggi/detail/RjZDQURCOEYtMTA0Ny00MDYzLUJCMTUtOEIxN0MxQTREQTky",
"http://forlap.dikti.go.id/perguruantinggi/detail/MDQxQkU5MEItQUVDOS00NkZDLTk3QUMtQTE0MzZFOTJBNUND",
"http://forlap.dikti.go.id/perguruantinggi/detail/MTVGQzMyNDYtMzFFOS00NTIwLUIwMDEtQTRDM0UwRjhBNkNE",
"http://forlap.dikti.go.id/perguruantinggi/detail/MTk2MThFRTMtOEU1Ni00NDRELUI2QjMtQjY0RUIxOTNEMUYw",
"http://forlap.dikti.go.id/perguruantinggi/detail/MUZERkMzNjAtMDk2Ri00Q0M2LTk1MTYtNDJCMzE3RTFGQzJB",
"http://forlap.dikti.go.id/perguruantinggi/detail/MjBGRTRFRDItMjUyQi00QTU2LUE5MDctQzk2RkJDRUM5NjJB",
"http://forlap.dikti.go.id/perguruantinggi/detail/N0ZGRjRDMTktM0UyMS00MTA1LUE3MTYtRDc3OTc2Q0NGMzNG",
"http://forlap.dikti.go.id/perguruantinggi/detail/NDE0OUI4MkUtNkY4NC00MDNCLUI2NjYtQjM5OEQ4QjE4MTk4",
"http://forlap.dikti.go.id/perguruantinggi/detail/NDdEOThGRTYtNTg5Ri00QTA2LTkyQzEtNUNGMkIxQUE3NTA4",
"http://forlap.dikti.go.id/perguruantinggi/detail/NDk5N0MwQTAtMDgzQy00QkVBLTk3NkEtQjkwNEE2MDg5NkJC",
"http://forlap.dikti.go.id/perguruantinggi/detail/NTIyRjU2QjUtOUY4Mi00NzlGLTlFMDctMjVBREQ1NDY4NzQ2",
"http://forlap.dikti.go.id/perguruantinggi/detail/NTlGNTFBMzQtRTAzQS00NTc2LTgxMEEtNUQ4NkQzNTlDQjVD",
"http://forlap.dikti.go.id/perguruantinggi/detail/Njg4Q0EwNDMtMjc1RS00M0VGLTk2MjEtQUEzQjNGMzNFNDlB",
"http://forlap.dikti.go.id/perguruantinggi/detail/NzFFQjhGNDAtNzM0My00QkE2LTk0QUQtODVFMkM2MkZERjAw",
"http://forlap.dikti.go.id/perguruantinggi/detail/ODQ2QjNGQkUtMzc0Qy00QjlDLUIyRjUtNERCRTRBQTgxMERB",
"http://forlap.dikti.go.id/perguruantinggi/detail/ODRDOERDQUQtMEE0RS00M0E2LTgxRkEtMjc5MUI3MjU0NjYw",
"http://forlap.dikti.go.id/perguruantinggi/detail/ODVBNjc4NTktNUVGNy00NzhCLUJDMzktODAwMDI0QzhCRjVC",
"http://forlap.dikti.go.id/perguruantinggi/detail/QTNFOEM5QTItNzZDOC00RjRELTg5MDUtREZERTY0QTdBMTA0",
"http://forlap.dikti.go.id/perguruantinggi/detail/QTNGOTU2Q0QtQjkyMS00MjY2LUI3QkItNjg1RjQ2NDAwMUE2",
"http://forlap.dikti.go.id/perguruantinggi/detail/QjVFRDBFQjEtQjgyNS00RURBLUI0RTQtRUExOEQzQTA2MDcy",
"http://forlap.dikti.go.id/perguruantinggi/detail/QkRFNkU5NDctNDhGMS00NjAyLTk3RDYtOURFNzFBQUMwQjc5",
"http://forlap.dikti.go.id/perguruantinggi/detail/MDExODY4NUYtOEI3MS00MTNELUExNzQtOEU0MUMzQjk1MjA0",
"http://forlap.dikti.go.id/perguruantinggi/detail/MTVDMDVCOTYtQzQ5QS00M0NBLThDNkQtMUYyN0M4OTJERkEy",
"http://forlap.dikti.go.id/perguruantinggi/detail/MTdCRDMxOTAtMDM5Ny00OTU2LUFCMUYtRUY3QkJBREE2M0JD",
"http://forlap.dikti.go.id/perguruantinggi/detail/MkJDRDZBRTgtODlBOS00M0M4LTg4NjgtRjIyM0QzM0JGNDA2",
"http://forlap.dikti.go.id/perguruantinggi/detail/MzU2OTVBQzAtMzBBMC00QTk4LUI5OTUtMUIxRDc3RjlDQzBC",
"http://forlap.dikti.go.id/perguruantinggi/detail/NDhERDQyRkItQ0NFMy00MDYzLTgwOUItRkMyNUQ1RjI5NjhE",
"http://forlap.dikti.go.id/perguruantinggi/detail/NTU0M0NEMjUtRkU2RC00NjRELThGMDktNkY0Q0RDMjZCREJD",
"http://forlap.dikti.go.id/perguruantinggi/detail/NTZFRDI0MjItOTBBOC00M0M3LUFDRjgtMzgwRjlBNkFERTAx",
"http://forlap.dikti.go.id/perguruantinggi/detail/ODNGRDFBQkEtNjM2Mi00Qzc4LTkyRTAtN0JENDgxRTBBNUJG",
"http://forlap.dikti.go.id/perguruantinggi/detail/OTBDQjUwODYtRUU0RS00RkVDLTk5RjMtMDc0Q0VFQTBEMjdC",
"http://forlap.dikti.go.id/perguruantinggi/detail/OTcwMDdENjEtNDZEOS00QkY0LTk2RTAtQ0M5RDQ4OTlCOTQ0",
"http://forlap.dikti.go.id/perguruantinggi/detail/Q0ZCNUIwRjctNDAwMC00MDhCLUFFRUQtOEUyRUMyNDkwRDk3",
"http://forlap.dikti.go.id/perguruantinggi/detail/QTRDMTAwRjUtNEI1Qy00ODdFLUJGOTUtMTMyMUQzQ0ZDRTc2",
"http://forlap.dikti.go.id/perguruantinggi/detail/QjU3OEU0N0UtNTg1OC00QkM2LThCOTktOEJGM0UxMUJDMjk4",
"http://forlap.dikti.go.id/perguruantinggi/detail/QjUyQUIzMjgtRTM5Ny00OTFELTkzMzEtNzlCQkU3OTM3NTU3",
"http://forlap.dikti.go.id/perguruantinggi/detail/QzQyQ0M4MEUtM0ZEMS00QzNGLUI2RTktRjlGQzg0RDZFNkU1",
"http://forlap.dikti.go.id/perguruantinggi/detail/RDgzRTQxMTktQUI0NC00OEIxLUIxRjgtMUZDMUQyMTRFMUI1",
"http://forlap.dikti.go.id/perguruantinggi/detail/REUwRTc4NkItQjI1Qi00NEUzLThGNEQtNDM1NTgyRTREOUI0",
"http://forlap.dikti.go.id/perguruantinggi/detail/RTA4QzZGMDUtMkREMS00NzY2LUIwMTQtMDc2RUU2MTg2MDg4",
"http://forlap.dikti.go.id/perguruantinggi/detail/RTdCNkU5MEEtRjEwQS00RkUyLUJGM0ItNENFNDA0QTRDNkE5",
"http://forlap.dikti.go.id/perguruantinggi/detail/M0JDRDE0MUQtQkM2Qi00QkMxLTg2MjktREVCQjU5RTVGRDJC",
"http://forlap.dikti.go.id/perguruantinggi/detail/M0MwRDg3MjAtM0UyQi00MTExLUFDNDctMzg3RTczMDU2NjVE",
"http://forlap.dikti.go.id/perguruantinggi/detail/MEEzNTREQjctRDdCRi00NTdELUJDOEItOTk0OTM5QkExRjY2",
"http://forlap.dikti.go.id/perguruantinggi/detail/MjQ1ODI2OTAtQTQxMC00Mzk2LTlEMkItREMxQjUyMzZFMzgx",
"http://forlap.dikti.go.id/perguruantinggi/detail/MzBBMTI0Q0ItNEMzQS00MTAxLTg3QkQtQjA1NUI3MTAzN0RE",
"http://forlap.dikti.go.id/perguruantinggi/detail/MzMxQURFODEtRDUwNS00MTNCLUE3QkMtNEYzREI2MjFDODBF",
"http://forlap.dikti.go.id/perguruantinggi/detail/MzQ5QTRFRDQtQjZFOS00NUI0LTkzNzItQTJGRDdDREIzRTg0",
"http://forlap.dikti.go.id/perguruantinggi/detail/NDk5MUMwMkYtQjgyOC00ODA5LTgyNjQtMUZBNkUwMjUyQjU1",
"http://forlap.dikti.go.id/perguruantinggi/detail/NjAwQTZBNTItRjY2Ni00NkUxLThCRkYtMjg2RDE0QkIyQzkx",
"http://forlap.dikti.go.id/perguruantinggi/detail/NkRCODQyMkYtMTI2RS00MkZFLUFFQkQtN0JDMTU1QkQyREZC",
"http://forlap.dikti.go.id/perguruantinggi/detail/NzQ0RkRFNEItQjY3My00MDZELTg3ODMtQzc1QkE0QUY5MjBG",
"http://forlap.dikti.go.id/perguruantinggi/detail/OTkwOTE0MEItQkNDMC00NkIxLTlGNTItMjBGQjEwRTVDNkFD",
"http://forlap.dikti.go.id/perguruantinggi/detail/OUFDMUJGMDQtODk2OS00MDVELTlBRDYtN0QxMDI2NUQ5NkM2",
"http://forlap.dikti.go.id/perguruantinggi/detail/QTg2NUJFODItMzg0Ni00MDNBLUJCQTMtMEU1QjhERjAwQzc3",
"http://forlap.dikti.go.id/perguruantinggi/detail/QUU2NTlDMDMtREJFNC00NUQ0LTgzRjAtNTExQTQ0QTg0QkU2",
"http://forlap.dikti.go.id/perguruantinggi/detail/QUZBNUUyMDctQUFEQi00QjIxLThBREItNEZCNTU2N0RDMjk2",
"http://forlap.dikti.go.id/perguruantinggi/detail/QzE2NDI3MUEtMDEwRS00RTAzLTg3Q0EtRjM5NjA0OTlBOEI2",
"http://forlap.dikti.go.id/perguruantinggi/detail/QzdFMEYyMkMtQzcyRS00OTVCLTg4QjMtNUNFNzk5MUM4OTUw",
"http://forlap.dikti.go.id/perguruantinggi/detail/RDIxOUEwRDgtNzVENi00MEZBLUEwQkQtMDYyOUQxQUU1NzMy",
"http://forlap.dikti.go.id/perguruantinggi/detail/REVBOTY1MjYtMzVDRC00RTUzLUI1N0ItMzI4MjI3QjRCRDI5",
"http://forlap.dikti.go.id/perguruantinggi/detail/MDQ0NjVDRDUtQTMyNy00RDQ4LTk2MkItMzYwQzc1NzBCNkE1",
"http://forlap.dikti.go.id/perguruantinggi/detail/MzIxNzJDNTQtREQ0Ny00NkZGLUJCMjYtMkNBRkJGN0VBQUIx",
"http://forlap.dikti.go.id/perguruantinggi/detail/MzQyMDlCNjQtMDNFMi00QUEwLTkxNjEtMDdBQkNEQjRCNjlD",
"http://forlap.dikti.go.id/perguruantinggi/detail/N0IzRDQ4OUQtQjcwOC00QkFGLUIyODYtRjAwMzcxQjVEMTU0",
"http://forlap.dikti.go.id/perguruantinggi/detail/NDBERTIyMDUtNTc0Ni00NDQyLTgzM0EtNUMwOTdFQUZFRDQ4",
"http://forlap.dikti.go.id/perguruantinggi/detail/NTdBODUzQUQtNzQzMy00QjQzLUE2MUEtMTI0QzkzOEY3OTkz",
"http://forlap.dikti.go.id/perguruantinggi/detail/NjZFQTQ0RTQtOTFGMS00RjdBLTgxNzUtMjFEQzc5QTlGQ0JE",
"http://forlap.dikti.go.id/perguruantinggi/detail/NkU2RjdBM0UtQTUzRC00QkM4LUIwQTMtMTg1QTZBRkY5QTAz",
"http://forlap.dikti.go.id/perguruantinggi/detail/OEFCRjUyMDgtOTIyRS00MkVGLUI1MTktMkFBN0M1RDU5MEFF",
"http://forlap.dikti.go.id/perguruantinggi/detail/OTMzQzc3MzAtNzg5QS00MDIwLThDMjMtQzk0MjhBMjU4NTU3",
"http://forlap.dikti.go.id/perguruantinggi/detail/OTVCQzRFNjAtRDk2OS00NUQ4LUE4NjYtNkMyNDRCNzE3NDhC",
"http://forlap.dikti.go.id/perguruantinggi/detail/QjBERDgwMEItMEQyRS00RDlELThENkEtMjU0QURDRDczMkMz",
"http://forlap.dikti.go.id/perguruantinggi/detail/QkY1RjBBNTEtQjMxMy00QkNDLUE4OTctRjk2NkRCQ0VDNTQ5",
"http://forlap.dikti.go.id/perguruantinggi/detail/QkY3NTY3MEUtQjk2RC00QTQ3LTk0QjAtRDdBOTAwMjgwM0JG",
"http://forlap.dikti.go.id/perguruantinggi/detail/RDBFOUU2NDQtMkZFQi00MTEyLTgxOUItRjU3REQ3MDhFQTRC",
"http://forlap.dikti.go.id/perguruantinggi/detail/RDIwM0NEMkMtNDI1Qi00RERBLTk4RTktQkVENjgyQ0UxMDcw",
"http://forlap.dikti.go.id/perguruantinggi/detail/REZDMjgwRkQtODM1NC00MkQ3LUI3MUQtMzY3MkVBNkQyMUFC",
"http://forlap.dikti.go.id/perguruantinggi/detail/RjBCREM4NEEtMkU5NC00QjU5LTk4MjEtRTUwNTBBNzY1RTJC",
"http://forlap.dikti.go.id/perguruantinggi/detail/RjMzQjFERjctRTIxMi00MkFDLUI2ODEtNEYzN0U1MTUxOTBB",
"http://forlap.dikti.go.id/perguruantinggi/detail/RkExQTkzQTEtRkFGNi00RTI1LUEyMTAtNjc0QTdCOTE4MjE3",
"http://forlap.dikti.go.id/perguruantinggi/detail/MDUwNTJBMzAtNTFCNS00NTExLUExMkMtRjJEREIwQzg0MDQ1",
"http://forlap.dikti.go.id/perguruantinggi/detail/MUE3M0QyREUtQkRERS00MUFELUJBNTAtQUMzRTlGMjk4QjIz",
"http://forlap.dikti.go.id/perguruantinggi/detail/MUVENzA3OUEtNzY3MS00MEM3LUEyOTAtQTEzODhCQzJBRTZF",
"http://forlap.dikti.go.id/perguruantinggi/detail/MjIwNDgyNUQtNTFBMS00N0ZCLThCRkYtODEzRjQ0MDY2QzVC",
"http://forlap.dikti.go.id/perguruantinggi/detail/NDY1N0JEQjQtNTA5Qi00OTQ4LUEzRjMtQ0YyMUVBNTRFNTQy",
"http://forlap.dikti.go.id/perguruantinggi/detail/NjQzNjM4MzctQzA5My00NUVELTkzNkUtNDZGRjg5MTVBNkRB",
"http://forlap.dikti.go.id/perguruantinggi/detail/NkMzQzA0MjgtMzFEQy00NjM0LUE5RDgtNUNBNkExMTMzNkEz",
"http://forlap.dikti.go.id/perguruantinggi/detail/NzAxQTA4NDktNTI4Qy00MDVFLTg0OTgtQUEyMDkwQjAxMjhB",
"http://forlap.dikti.go.id/perguruantinggi/detail/NzhDMjBEMDQtMEJFOS00MThDLTlGN0UtM0I3RjVERkJDQzA0",
"http://forlap.dikti.go.id/perguruantinggi/detail/ODcwRURERDEtOEY5OS00NkRDLUE3MzgtRjMwQkYxMkVEMUU1",
"http://forlap.dikti.go.id/perguruantinggi/detail/QUI2MkQ1NjEtMjYyRS00NzZDLUI1NTMtOTVGODk3RjEzMUM5",
"http://forlap.dikti.go.id/perguruantinggi/detail/QkE1NjFCMEQtOUI3Qy00OTExLUI4NUItQjVCNTMwMTkxQTk0",
"http://forlap.dikti.go.id/perguruantinggi/detail/QzdBRDVGNTEtNThEOS00NUYxLUE1RTctMTA5MTNEMzBBODJD",
"http://forlap.dikti.go.id/perguruantinggi/detail/RDdDNkZBRUUtRDdCQS00Nzc5LUFDMTMtNjFCRERFQkY4MzVD",
"http://forlap.dikti.go.id/perguruantinggi/detail/REI5MzFBQjItNjZFRS00NkRCLTk3NUUtOUU2NEQzQTZCMjI4",
"http://forlap.dikti.go.id/perguruantinggi/detail/REVDQTE1MjEtMEEyRS00QzQyLUEwNkYtN0ZFQTVGRkRDNUEy",
"http://forlap.dikti.go.id/perguruantinggi/detail/RTYxRTU3NDgtRTEzNC00MkY3LUIxMDItNDAyNTEyNjI4NzRG",
"http://forlap.dikti.go.id/perguruantinggi/detail/RjczOUY4MzAtQTExNC00MTVCLTg0MjUtQjY5MDVDQTZDRkZF",
"http://forlap.dikti.go.id/perguruantinggi/detail/Rjg0RDAzMTgtOUQxMi00OTY0LTk5OUUtMjgxOEQ0NDU1MTJF",
"http://forlap.dikti.go.id/perguruantinggi/detail/RjkyRkFBQjMtOUYzQS00MEVBLUIxQzQtRDhBNzBGQThFMzhF",
"http://forlap.dikti.go.id/perguruantinggi/detail/M0VDNjFBMTQtNjk2Mi00OEVCLUE5OTgtRDFDRjVCRDQ2MUJG",
"http://forlap.dikti.go.id/perguruantinggi/detail/MDZFMEUyRjItNUU3Ni00RjdDLTgxOTQtNDhFRTE2MUFCQTRD",
"http://forlap.dikti.go.id/perguruantinggi/detail/MDhBMzYzRTYtMTk3Ny00QTU3LThGMkItRUU5OEMxNUM0NDBC",
"http://forlap.dikti.go.id/perguruantinggi/detail/MTFCOEUxN0MtQ0Q0OC00RDI1LThFOTYtNDc5MzMwOUE1NDVG",
"http://forlap.dikti.go.id/perguruantinggi/detail/MjZCMzhCQ0UtNDBCNC00NjYyLThCNTYtRDdGQjI4Q0YwNzY3",
"http://forlap.dikti.go.id/perguruantinggi/detail/MjcwOTMxNTktQ0E2Ri00REI2LTkxRTAtREMyOEFGNDdCNTM0",
"http://forlap.dikti.go.id/perguruantinggi/detail/Mjk2MTgxMEMtRkZFQS00OURCLThGNzctQjE2MzQzNTcwRkQy",
"http://forlap.dikti.go.id/perguruantinggi/detail/NEUzNDk3NzYtRkY2Mi00MEEzLUE2M0ItQzVBQ0FDREU0OTQx",
"http://forlap.dikti.go.id/perguruantinggi/detail/ODFDOUNEMDQtMzYwNS00Nzk4LTlERkYtRkI0NTA4MTEwMTZD",
"http://forlap.dikti.go.id/perguruantinggi/detail/ODlBQjY5OEYtN0JFOS00RDVCLUExQzQtNDg2MTg1NkVGQzQ1",
"http://forlap.dikti.go.id/perguruantinggi/detail/OTc1MDIzQjctOENCQi00OEEzLTgzRjQtOTA2RDhDODdFNkI3",
"http://forlap.dikti.go.id/perguruantinggi/detail/OUFFNDU2NUMtRDY1RS00MTQxLUE3M0UtODc1Rjk0RUFCNkZD",
"http://forlap.dikti.go.id/perguruantinggi/detail/OUVDNkRDQUEtMzQyOC00MTU3LUI0OTYtRTEwNEFBRUFDOEU5",
"http://forlap.dikti.go.id/perguruantinggi/detail/Q0YzREY4Q0QtNjYyRi00MkVDLUIzNUUtOEQ3NDlENkQ0RjJE",
"http://forlap.dikti.go.id/perguruantinggi/detail/QTU5QTBFNzEtNDgyQy00NjJBLTg4NjItQzMzMUE5ODFDNDA4",
"http://forlap.dikti.go.id/perguruantinggi/detail/QTdCRDI3QkItMjNGOC00RUU5LUJGMDQtNEIxMjEwNTc0QTZD",
"http://forlap.dikti.go.id/perguruantinggi/detail/QUI0QURBREEtQ0UxOC00QkIxLUI5REQtNzlBRDQwMkU0REIy",
"http://forlap.dikti.go.id/perguruantinggi/detail/RDc1MTNDMDUtNzI0Mi00RURGLUE3RUQtMEM1NDI2NDE3QjhD",
"http://forlap.dikti.go.id/perguruantinggi/detail/RUE3MDE5NzAtMUE1RS00Mjk5LTg4QUEtQjEwNUY3MzhBMTZF",
"http://forlap.dikti.go.id/perguruantinggi/detail/RjJCMjcyMDItOTlGMy00OEJFLTgwQjYtRTYzMTVDQThFNjcw",
"http://forlap.dikti.go.id/perguruantinggi/detail/MDBFMTNCOEQtREI0NS00MzIzLUEyMDItQzVFMTdCQzUwQzQ3",
"http://forlap.dikti.go.id/perguruantinggi/detail/MDQyQjZCMTUtMTQ4OC00MjdCLTk3QzctMkM2NEM4QTQ1MDQy",
"http://forlap.dikti.go.id/perguruantinggi/detail/MTUyNDhGMzYtQjlGOC00REVFLUE0MUYtMEQ3QUI5Njg5OTE0",
"http://forlap.dikti.go.id/perguruantinggi/detail/MjcwMkVGMDItMUFCMC00RTAwLTg5NzctNzNEREMyNDJBMzUy",
"http://forlap.dikti.go.id/perguruantinggi/detail/MzExRTVDMTMtOUVDQy00N0RELUE1OEEtNzYyMURCMTZBNzA5",
"http://forlap.dikti.go.id/perguruantinggi/detail/N0I5RjIyQUQtNURDOS00M0E1LUJGQkYtMDVGQkUyNDBDMjlB",
"http://forlap.dikti.go.id/perguruantinggi/detail/NEExQjdBRDUtMTQ4NC00NTRCLUE1RTAtMjIwM0UwREI2QjhD",
"http://forlap.dikti.go.id/perguruantinggi/detail/NUVDQzM1RTctODAxRi00NDAxLUJDM0UtRUYzRjI0RUREOTA4",
"http://forlap.dikti.go.id/perguruantinggi/detail/NjM2NjgxQUQtQzVDNy00RTZCLThCMkUtQUQ5NEE5RjFFQkI3",
"http://forlap.dikti.go.id/perguruantinggi/detail/NjNBQjBGQTMtOEY3RS00RURGLUE1MDEtQTQ5REI2RTUzMkY2",
"http://forlap.dikti.go.id/perguruantinggi/detail/NkRDMTFDQTItQzcxMC00ODRCLThCM0QtNzNDN0NCQTkzRUZD",
"http://forlap.dikti.go.id/perguruantinggi/detail/OTM2NDc2RUEtNjg4Mi00RTlBLUI4OUUtMDI5ODUzQUJCNEJG",
"http://forlap.dikti.go.id/perguruantinggi/detail/OTVFMERDQTMtNjEyMC00NzIxLTkyQ0ItQkVEODE4N0Q3OTFB",
"http://forlap.dikti.go.id/perguruantinggi/detail/OURGRjFCREQtMUVBRS00Rjc3LTgyMjMtQUVGRkZCMTJBRDQ1",
"http://forlap.dikti.go.id/perguruantinggi/detail/QTA4RjgzQjQtRENEQS00NzdFLUI4QTQtQjU4MUZBRUM4NDg5",
"http://forlap.dikti.go.id/perguruantinggi/detail/RDFCOTA0NkMtQ0MyNS00NTRELUE2MTMtNjM0MTk2QjUyNEUw",
"http://forlap.dikti.go.id/perguruantinggi/detail/RDJBNDcyOTktMzRGNS00OThGLTgyRTctODJDMDNEODZEN0Yz",
"http://forlap.dikti.go.id/perguruantinggi/detail/REEzQzE1MzMtRkNEMy00NEJBLUExNzctMTQ3ODEwNUE2Qjcy",
"http://forlap.dikti.go.id/perguruantinggi/detail/RTc3MTUzMUItQzAwQi00QjY5LUIwMDQtM0E5QkM5QkFEQzJD",
"http://forlap.dikti.go.id/perguruantinggi/detail/RkYxNjU0RkYtMUE5QS00MUI2LUJGQkEtREQ1QjgzQkI2MTE5",
"http://forlap.dikti.go.id/perguruantinggi/detail/MTJFNUUzODYtN0RDRi00QjhBLUExMzQtMDQ1RkE0MEQ1NjM5",
"http://forlap.dikti.go.id/perguruantinggi/detail/MTJGMUM4MjYtQkYyRS00NjA2LTkwMkYtNTdCRTI5NThCMkQ3",
"http://forlap.dikti.go.id/perguruantinggi/detail/MjI0MjBBRTAtRDU0RS00MTI0LUI4NUQtRTA1QjMzRUNBREU1",
"http://forlap.dikti.go.id/perguruantinggi/detail/MjczOEVFQjctQkY4Ri00MDJGLTk3NkUtRDgzNUJEOTAwQkMx",
"http://forlap.dikti.go.id/perguruantinggi/detail/NDU5MTZCQjctNUUwOS00Q0MzLThFODQtNEFBMzRDQ0ExNkNG",
"http://forlap.dikti.go.id/perguruantinggi/detail/Nzg1NjBDQTEtMkI4Ri00NTBCLTkzM0QtRDBDOUY1QkZFQTYy",
"http://forlap.dikti.go.id/perguruantinggi/detail/NzkwRDk2QjgtN0IxQS00MzcxLUE4RjctRDkxOUE2ODU4NThE",
"http://forlap.dikti.go.id/perguruantinggi/detail/ODZGQzg1NDYtRDlBMi00RTI1LUExNDYtMTAyMTc5NDcxNjVB",
"http://forlap.dikti.go.id/perguruantinggi/detail/OEE0M0M2NjctODkwQi00OTM4LTlFNDYtNTlFQTg2RjY3MzQw",
"http://forlap.dikti.go.id/perguruantinggi/detail/OENGQUYyM0ItQTU5MC00Nzg5LTg0MTMtMjAxRUY0RTEwMDlE",
"http://forlap.dikti.go.id/perguruantinggi/detail/QTU2QUMwOTAtREQ4QS00MDJFLUFGNjctMEY3QkYxODAyRTFD",
"http://forlap.dikti.go.id/perguruantinggi/detail/QkE0MEQzNkMtNEUwNy00QjI0LUIzQkMtNUI4QjM3MTlEODI0",
"http://forlap.dikti.go.id/perguruantinggi/detail/QkFBQTFGNEEtMjUzNi00MjkzLTk3RjktMzZDRjhBOTkxREFD",
"http://forlap.dikti.go.id/perguruantinggi/detail/QzE5RUIyQ0MtQzY3NC00QzBELUIzNTktMTAxNTJBMTFDNTVE",
"http://forlap.dikti.go.id/perguruantinggi/detail/QzhDMTMwNzEtQUQ1NS00MTg3LUIyRDctREM0QzkyODBCMDYx",
"http://forlap.dikti.go.id/perguruantinggi/detail/RDIwNTNGODYtRDJEQi00M0VBLTgxQzctNTE3RjFBRkQzNDUy",
"http://forlap.dikti.go.id/perguruantinggi/detail/REIxMTFFRTItQURFRS00MzM4LUEzN0QtNjUwODRCQ0FDMjc3",
"http://forlap.dikti.go.id/perguruantinggi/detail/RTEwNzk5MTQtQTQ1Qy00RTFGLUFDMDEtN0Q3M0RBNzA3MzBC",
"http://forlap.dikti.go.id/perguruantinggi/detail/RUFFMTI2MzQtODhGQi00MTNDLUJEQTAtREVFQjk3RUJGRkIz",
"http://forlap.dikti.go.id/perguruantinggi/detail/RjExOTcxOUQtRjA3NC00MEUxLUFEOUQtRjQ5M0ZBODAwNTJC",
"http://forlap.dikti.go.id/perguruantinggi/detail/M0FCMzlCNkMtODlBRC00NjVELTg0ODMtOUE0NDA1ODA2NTNG",
"http://forlap.dikti.go.id/perguruantinggi/detail/MEE2N0Q2OTYtNkY5OC00RUZBLUExODQtRDJCNDFEODg5ODEx",
"http://forlap.dikti.go.id/perguruantinggi/detail/MTU4QTc3RDMtQTlCNS00QjE2LThCRTEtRjZEQkI5RjFCMDhE",
"http://forlap.dikti.go.id/perguruantinggi/detail/MjNCOEUyNkYtM0I0Qy00OUZGLUI5MjMtMkE0MTQzMDU1QzJC",
"http://forlap.dikti.go.id/perguruantinggi/detail/MzMyQTI3M0ItMDgyQi00REEzLTg5ODgtODc1RjcyMTlEQ0Ey",
"http://forlap.dikti.go.id/perguruantinggi/detail/NDVFMEFDNDUtRDRFQi00QkVELTgxMDktOTE5QkFEOUUyNDJE",
"http://forlap.dikti.go.id/perguruantinggi/detail/NTVBQkZDRUMtQjZDRi00MkUzLUJCMjctODczOTI4MDJBRDEw",
"http://forlap.dikti.go.id/perguruantinggi/detail/NjdEQ0NDM0ItODRDQy00OURCLTgzREQtNTgyRkNCNEJDNzA3",
"http://forlap.dikti.go.id/perguruantinggi/detail/NkFFMEE3NkQtOEQ2Mi00NEM1LTlDM0MtNDU5Q0U1MjFBQkQ1",
"http://forlap.dikti.go.id/perguruantinggi/detail/NzRBQjhFQUEtRTRCNS00RTVGLThFNUUtODBGNDNDQ0ZBMjVD",
"http://forlap.dikti.go.id/perguruantinggi/detail/ODJFQTc5QTEtQjUzMi00QkIwLUI4M0YtMjVEQ0I3QjU3MzUz",
"http://forlap.dikti.go.id/perguruantinggi/detail/OEJCNjhEMDUtRTc4OC00ODdELTkzOEItQTE0MkY1OTAzOTk1",
"http://forlap.dikti.go.id/perguruantinggi/detail/OEYwRkMzRUQtQzZEMC00NkVGLUE1NDQtOURDQzA3MDFDREY2",
"http://forlap.dikti.go.id/perguruantinggi/detail/OTVGQjMwMTItREYwMi00MzUxLUFBREEtQjhBMjk1ODdCM0NG",
"http://forlap.dikti.go.id/perguruantinggi/detail/QjFGRUVEMTktNDc0Qi00MUM5LTk5QzgtMEFBRkMxQkMzNDQ0",
"http://forlap.dikti.go.id/perguruantinggi/detail/QjQ0MTU0MjktNEU5Qi00QkMxLTgzOTMtQjczNUU3OTMxQzMx",
"http://forlap.dikti.go.id/perguruantinggi/detail/QjQ5NkY5QjQtRUI5NC00Nzk3LThDNTMtQjFBRDdGNkI2RDM2",
"http://forlap.dikti.go.id/perguruantinggi/detail/RDZGOUYwNTktNUJCRi00NTk0LUJGQUUtNUQ3RENGOEU0QzFF",
"http://forlap.dikti.go.id/perguruantinggi/detail/REQyQzlEQ0QtNzRDOC00MzJELTgxODktQjUyRDY5QTc1OTA2",
"http://forlap.dikti.go.id/perguruantinggi/detail/RkY4M0Q1RDgtQjA4Mi00NEZFLTgzMjAtOERFMUUzREU5N0Ew",
"http://forlap.dikti.go.id/perguruantinggi/detail/MEFFOUE4OTMtOUY0Ni00RTJBLUJBOTctNkUyRTBEMjUyOTk3",
"http://forlap.dikti.go.id/perguruantinggi/detail/MEU0M0VCNzgtQjBEMy00Q0I0LUI3N0QtMTAyNTZGODNEMkFE",
"http://forlap.dikti.go.id/perguruantinggi/detail/MTNBNDE1MzctOEE5Qi00N0FGLUIwNTAtMzFFMEYzMzZCRTQ0",
"http://forlap.dikti.go.id/perguruantinggi/detail/MkE5ODFDMzktMjQ2Ny00MjVDLUE2RUMtREU3RTQ0RDUzNTY4",
"http://forlap.dikti.go.id/perguruantinggi/detail/N0M0MUE5QTUtMzZCNC00RkVDLTlBNEItQjY2OTA5NEQ1RDAw",
"http://forlap.dikti.go.id/perguruantinggi/detail/NTAyNDMwMzgtODY3Qi00QjU4LUJGN0YtNkY1QUMzRTA2N0Uy",
"http://forlap.dikti.go.id/perguruantinggi/detail/NUI0QUYyRUUtOUZENC00NTkyLTg4M0MtQTY1QzA1N0EzNDcx",
"http://forlap.dikti.go.id/perguruantinggi/detail/NjExMTg2NDktRjFDMC00OTZELTlEMjEtNkVBRTVDRkQyNEJG",
"http://forlap.dikti.go.id/perguruantinggi/detail/Nzc3MThCMTAtQTcyQi00ODA0LTlDNDktNTY0RUNFNzY4ODJF",
"http://forlap.dikti.go.id/perguruantinggi/detail/ODM3RThGMDAtRjg1Ni00MTFELUJFMkUtQzNDOEIwOURDQzYz",
"http://forlap.dikti.go.id/perguruantinggi/detail/ODQxMUQ5RDktNDBCRC00Q0E2LUExRjgtQkQwMzg2RDU2ODY3",
"http://forlap.dikti.go.id/perguruantinggi/detail/OEIxREFDRjItREM5RC00RkFDLUI2OTQtMkZBMzA4MzNBRDBF",
"http://forlap.dikti.go.id/perguruantinggi/detail/OTAzODI5QTItOUU4Qy00NkRDLUE3NDctRDQ3QUM2MjU4RTMw",
"http://forlap.dikti.go.id/perguruantinggi/detail/OTY5RDZBQjEtNUM4RC00RkM2LTg4M0EtOTY5ODczMEEwQTIx",
"http://forlap.dikti.go.id/perguruantinggi/detail/OUFCOUQ0N0YtNzJCNy00QjQzLTlGMzItRkY1MEUyRERCMDM0",
"http://forlap.dikti.go.id/perguruantinggi/detail/REZCNEJGNjUtQkZBRi00MTlCLUE1MkUtQzJBNDIzRUI4MTU3",
"http://forlap.dikti.go.id/perguruantinggi/detail/RkJGNzQ1NkMtRTI5NC00RDEwLTg4REYtQzhBQkFGQjZENkY0",
			);

date_default_timezone_set("Asia/Jakarta");
echo "=========================<br>";
echo ">> Mulai : pukul " . date('h:i:s') . " WIB<br>";
echo "=========================<br>";		 

for($x=0; $x<=236; $x++)
{
    $html = file_get_contents($prodi[$x]);
    //Create a new DOM document
    $dom = new DOMDocument;

    //Parse the HTML. The @ is used to suppress any parsing errors
    //that will be thrown if the $html string isn't valid XHTML.
    @$dom->loadHTML($html);

    //Get all links. You could also use any other tag name here,
    //like 'img' or 'table', to extract other tags.
    $links = $dom->getElementsByTagName('a');

    //Iterate over the extracted links and display their URLs
    foreach ($links as $link)
    {
        //Extract and show the "href" attribute.
        //echo $link->nodeValue;
        echo $link->getAttribute('href'), '<br>';
    }
}

echo "==========================<br>";
echo ">> Selesai : pukul " . date('h:i:s') . " WIB<br>";
echo "==========================<br>";

?>
